// Portraits for the beach finds (see index.js).

module.exports = {
  pebble: {
    palette: { H: '#f6f8fa', L: '#dfe5ec', M: '#b8c2d1', m: '#a2adc0', D: '#8d99ae', S: '#6f7a96', Q: '#f1f3f6', q: '#ccd3de' },
    pixels: [
      '....LLLMMM....',
      '..LLHHLLMMMM..',
      '.LLHHLLMMMMMm.',
      '.LHHLLMMMMMMm.',
      'LLLLMMMMMMMMmm',
      'QQQLMMMMMMMmmm',
      'MMMQQQQMMMmmmD',
      'MMMMMMMqqqqmmD',
      'mMMMMMMmmmmqqq',
      '.mmMMMMmmmmDD.',
      '..mmmmmmmDDD..',
      '....DDDDSS....',
    ],
  },
  'sand-dollar': {
    palette: { H: '#fffbf0', L: '#f3e6cc', M: '#e3d0a8', D: '#c8ad80', P: '#b89a6c', p: '#a2865c', S: '#8a6c48' },
    pixels: [
      '.....LHHLL.....',
      '...LHHHLLLLL...',
      '..LHHLLPLLLLM..',
      '.LHHLLPLPLLLMM.',
      '.LHLLLPLPLLLMM.',
      'LLLPPLLPLLPPLMM',
      'LLPLLPLLLPLLPMM',
      'LLLPPLLSLLPPMMD',
      'LLLLLPLLLPLMMMD',
      'LLLLPLPLPLpMMMD',
      '.LLLPLPMpMpMMD.',
      '.LLMMPMMMpMMDD.',
      '..LMMMMMMMDDD..',
      '...MMMMMMDDD...',
      '.....DDDDD.....',
    ],
  },
  'tiny-shell': {
    palette: { H: '#ffe4d9', L: '#ffd2c2', M: '#ff9f80', D: '#ec7a63', S: '#c9545a', a: '#fff1ea', A: '#ff8a9a', p: '#e0607a' },
    pixels: [
      '............LM',
      '.........HLSSD',
      '.........SHLMD',
      '......HHLSSMMD',
      '......SHLLSSDD',
      '....HHSSLLLMD.',
      '..LHHHLSSMMMD.',
      '.aaaHHLLSSMMD.',
      '.pppaLLLLMSD..',
      'apAAaLLLMMD...',
      'aAAAaLLMMMD...',
      '.aAaLLMMMMD...',
      '.aaLMMMMMMD...',
      '..MMMMMMDD....',
      '...DDDDDSS....',
    ],
  },
  driftwood: {
    palette: { H: '#e3cba6', L: '#c9a67e', M: '#b08b66', D: '#8a6a4a', g: '#765840', S: '#5c4538', K: '#3f2e2a' },
    pixels: [
      '.L................',
      'LHLL.........L....',
      'LMHHLL......LM....',
      'MDggHHLL...LM.....',
      '.SDDMMHHLLLM......',
      '..SSDDgMHHLL......',
      '....SSDDMKHHLL....',
      '......SSDDMMHHLL..',
      '........SSDDggHHL.',
      '..........SSDDMMHL',
      '............SSDDMM',
      '..............SSDD',
      '................S.',
    ],
  },
  kelp: {
    palette: { H: '#b8f2cf', L: '#7fdcae', M: '#57cc99', D: '#2a9d8f', S: '#1b6b70' },
    pixels: [
      '......L....',
      '.....LDM...',
      '....LDMD...',
      '...LHDMD...',
      '..LHDMD....',
      '..HLDMD....',
      '..LLDMMD...',
      '...LHDMMD..',
      '...LHLDMMD.',
      '....LHDMMS.',
      '....LLDMMD.',
      '...LHLDMD..',
      '...LLDMD...',
      '....LDMD...',
      '.....DD....',
      '....LHMD...',
      '....MMDS...',
      '.....DS....',
    ],
  },
  starfish: {
    palette: { H: '#ffe2d4', L: '#ffb199', M: '#ff7a5c', D: '#e4553f', S: '#b73a3f' },
    pixels: [
      '........L........',
      '.......LMD.......',
      '.......LHD.....LM',
      '......LHMMD...LMD',
      '......LMLMD..LLD.',
      '.....LHMMMMDLMMD.',
      'LLLLLHMMLMMMMMD..',
      '.DMLMMLMMMLMMMD..',
      '...DDMMMMMMMMMD..',
      '.....MMMMMMMMD...',
      '....LMMLMLMMMD...',
      '....LMMDDMMMMMD..',
      '...LMLD...DMLMD..',
      '...LMD.....DMMD..',
      '..LMD.......DMMS.',
      '..LD.........DS..',
    ],
  },
  'urchin-shell': {
    palette: { H: '#f3d9ff', L: '#dba4ff', l: '#c77dff', M: '#9d4edd', D: '#7634b8', S: '#521f8f', T: '#ecd0ff', t: '#b56cec' },
    pixels: [
      '........l.........',
      '...l....l.....M...',
      '....l.LHHLll.M....',
      '....LHTHLTlltM....',
      '...LHLLLlllMMMD...',
      '..LLTLlTlMtMMtDD..',
      '..LLlllMMMMMMDDD..',
      'MMlTlMTMMtMDtDDSDD',
      '..lMMMMMDDDDDDSS..',
      '..MMtMDtDDtDDtSS..',
      '...DDDDDSDDSSSS...',
      '...D.SSSSSSSS.S...',
      '..D............S..',
    ],
  },
  conch: {
    palette: { W: '#ffffff', H: '#fff1e6', L: '#ffd6c8', M: '#ffb4a2', D: '#e5989b', S: '#c47482', P: '#ff8fa3', p: '#e8667f' },
    pixels: [
      '.........L..L.....',
      '.........LHLLLHH..',
      '.....L.LLHLLMMHHH.',
      '...L.LHLSLLMMMHHHH',
      '...DLHDLDLMMMpPPHH',
      '.LLDLMDMDLMMDppPPH',
      'LMMDMMDMDLMMDppPWH',
      '.DDDMDDDDMMDDppPPH',
      '...DDDSDSMMDDpPPPH',
      '......DSDMDDDSPPHH',
      '........SDDDSHPHHH',
      '.........DSSSHHHMD',
      '...........SSLLMD.',
      '..............MD..',
    ],
  },
};
