// Portraits for the codebase finds (see index.js).

module.exports = {
  'lost-semicolon': {
    palette: { H: '#f0c8ff', p: '#c77dff', P: '#9d4edd', D: '#6a2c9f', k: '#2b1d3d' },
    pixels: [
      '..HHpp..',
      '.HHpppP.',
      '.HppppP.',
      '.ppppPD.',
      '..pPPD..',
      '........',
      '........',
      '........',
      '..HHpp..',
      '.HHpppP.',
      '.HkppkP.',
      '.ppppPP.',
      '..pPPPD.',
      '...pPPD.',
      '...pPD..',
      '..pPD...',
      '.pPD....',
      'PD......',
    ],
  },
  'stray-bracket': {
    palette: { Y: '#fff3a8', y: '#ffd23f', o: '#e9a23b', O: '#b86b1f' },
    pixels: [
      '....YYyy',
      '...Yyooo',
      '...Yyo..',
      '...Yyo..',
      '...Yyo..',
      '...Yyo..',
      '...Yyo..',
      '..Yyyo..',
      'YYyyo...',
      'oyyyO...',
      '..yyyo..',
      '...Yyo..',
      '...Yyo..',
      '...Yyo..',
      '...Yyo..',
      '...Yyo..',
      '...Yyyyy',
      '....oooO',
    ],
  },
  'coffee-bean': {
    palette: { w: '#e8c49a', H: '#b07a45', h: '#8f5a2a', a: '#6f4518', A: '#52321a', b: '#2e1a0c', D: '#3b2412' },
    pixels: [
      '........hhaa...',
      '.....HHHhhaaa..',
      '....HwHHhhaaAA.',
      '...HwwHhhhaaaA.',
      '..HHHHhhhaabbD.',
      '.hHHHhhhbbbbAD.',
      '.hhhbbbbhaaaDD.',
      '.hhbhhaaAAADD..',
      '.abhaaaAADDD...',
      '.aaaAAAADDD....',
      '..AAAADDDD.....',
      '...DDDD........',
    ],
  },
  'escape-key': {
    palette: { W: '#ffffff', w: '#e0e0e0', g: '#c4c4c8', G: '#9e9e9e', S: '#7a7a85', D: '#5a5a68', c: '#3d405b' },
    pixels: [
      '.WWWWWWWWWWWWWW.',
      'gWwwwwwwwwwwwwgS',
      'gWwwwwwwwwwwwwgS',
      'gWwwccwwccwwccgS',
      'gWwcwcwcwwwcwwgS',
      'gWwcccwwcwwcwwgS',
      'gWwcwwwwwcwcwwgS',
      'gWwwccwccwwwccgS',
      'gWwwwwwwwwwwwwgS',
      'ggggggggggggggGS',
      'gGGGGGGGGGGGGGSS',
      'gGGGGGGGGGGGGGSS',
      'GSSSSSSSSSSSSSSD',
      '.DDDDDDDDDDDDDD.',
    ],
  },
  'floppy-disk': {
    palette: { B: '#8fbcff', b: '#3a86ff', A: '#2864d6', D: '#1d4499', w: '#ffffff', s: '#e8e8ee', S: '#c0c0c0', T: '#8a8a96', k: '#3d405b', l: '#fff4e4', L: '#e6d6bf', r: '#e63946', n: '#4a6bb0' },
    pixels: [
      'BBBBssssssssBBb.',
      'BbbbswSSkkSTbbbA',
      'BbbbsSSSkkSTbbbA',
      'BbbbsSSSkkSTbbbA',
      'BbbbsSSSkkSTbbbA',
      'BbbbTTTTTTTTbbbA',
      'BbbbbbbbbbbbbbbA',
      'BbllllllllllllbA',
      'BbrrrrrrrrrrrLbA',
      'BblnnllnllnnlLbA',
      'BblnlnlnlnlllLbA',
      'BblnnllnlnlnlLbA',
      'BblnlnlnlnlnlLbA',
      'BblnnllnllnnlLbA',
      'BbLLLLLLLLLLLLbA',
      'ADDDDDDDDDDDDDDD',
    ],
  },
  'actual-bug': {
    palette: { H: '#8ee6d6', t: '#2a9d8f', T: '#1f7a70', g: '#2d6a4f', b: '#1b4332', D: '#10291f', k: '#0b1a14', w: '#fff4e4' },
    pixels: [
      '..tt.......tt..',
      '....t.....t....',
      '.....tHttT.....',
      '....wktttkw....',
      '.t..ttttttT..t.',
      '..tgHgggbbbDt..',
      '...DDDDDDDDD...',
      '..gHHggkgbbbD..',
      'ttgHgggkgHbbDtt',
      '..ggggbkgbbbD..',
      '..bgggbkbbbbD..',
      '..bbgbbkbbbDD..',
      '..tbbbbkbbbDt..',
      '.t..bbbkbDD..t.',
      '......DDD......',
    ],
  },
  'rubber-duck': {
    palette: { W: '#fffbe6', Y: '#fff09a', y: '#ffd23f', O: '#e9a23b', D: '#c27a1a', q: '#ffc15e', o: '#ff9f1c', R: '#d8650f', k: '#2b2d42', e: '#ffffff' },
    pixels: [
      '........YYYy......',
      '.......YWWYyy.....',
      '......YWWYyyyy....',
      '......YWYyekyO....',
      '......YYyykkyyqqoo',
      'Yy....YyyyyyyOoooR',
      'Yyy....yyyyyyORRR.',
      'OyyY..YyyyyyyO....',
      'OyyyYWWYyyyyyyyO..',
      'OyyyYYYYYyyyyyyyO.',
      'OyyYyyyyyOyyyyyyO.',
      '.yyOyyyyOyyyyyyOD.',
      '.yyyOOOOyyyyyyyOD.',
      '.OyyyyyyyyyyyyyOD.',
      '..OOyyyyyyyyyOOD..',
      '....OODDDDDDDD....',
    ],
  },
  'golden-duck': {
    palette: { W: '#fffdf0', Y: '#fff1a0', y: '#ffd23f', m: '#f0b820', O: '#c99700', D: '#8a6100', q: '#e8b417', o: '#c99700', R: '#8a6100', k: '#2b2d42', e: '#ffffff', r: '#e63946' },
    pixels: [
      '.......Y.W.Y......',
      '.......OYrYO......',
      '........YYYy......',
      '.......YWWYyy.....',
      '......YWWYyyyy....',
      '......YWYyekyO....',
      '......YYyykkyyWqoo',
      'Wy....YyyyyyymOoqR',
      'Yyy....yyyyymORRR.',
      'OyyY..YyyyyymO....',
      'OyyyYWWYyyyyyymO..',
      'OyyyYYYYYyyyyyymO.',
      'OyyYyyyyyOyyyyymO.',
      '.yyOyyyWOyyyyymOD.',
      '.mmmOOOOmmmmmmmOD.',
      '.OYYYyyyyyyyymmOD.',
      '..OOmmmmmmmmmOOD..',
      '....OODDDDDDDD....',
    ],
  },
};
