// Portraits for the deep finds (see index.js).

module.exports = {
  pearl: {
    palette: { W: '#ffffff', H: '#f8f4ff', L: '#e9e2f7', M: '#cfc6e6', D: '#ab9fcc', R: '#f3dcec', N: '#bcc3e2', n: '#959cc8', O: '#a399b8', o: '#82789c', X: '#5d5478' },
    pixels: [
      '...oOOOOOOOOo...',
      '..oOnnnnnnnnOo..',
      '.oOnNNNNNNNNnOo.',
      '.OnNHNNNNNNNNnO.',
      'oOnNNNHHLLNNNnOo',
      'oOnNNHWHLLMNNnOo',
      '.onNHWWHLLMMNnO.',
      '..nnHHHLLRMDnn..',
      '....LHLLLRMD....',
      '.nNNLLLLRMDDNNn.',
      'nNHNNLRMMDDnNNnn',
      'OnNNNnnnnnnNNnnX',
      'OOnOnNNNNNNnOnXX',
      'OoOOoOOooOOoOoXX',
      '.oOooOooOooOoXX.',
      '..oXooXooXoXXX..',
      '....XXXoXXXX....',
    ],
  },
  'shark-tooth': {
    palette: { W: '#ffffff', H: '#f1faee', L: '#e4ede9', M: '#cfd8dc', D: '#a8b7c0', R: '#d8c9ae', r: '#b5a284', q: '#8f7c60' },
    pixels: [
      '.rRRRRRRRRRr.',
      'rRRHHRRRRRRrq',
      'rRRRRRRRRRrrq',
      '.qrrLHHLMrrq.',
      '.qLHWHLLMMDq.',
      '.LHWHLLLMMMD.',
      '..LHHLLLMMD..',
      '..HHLLLMMMD..',
      '..LHLLLMMDD..',
      '...HLLLMMMD..',
      '...LHLLMMD...',
      '....HLLMMD...',
      '....LHLMD....',
      '.....HLMD....',
      '.....LMD.....',
      '......LD.....',
    ],
  },
  ammonite: {
    palette: { H: '#f2e9e5', L: '#d7ccc8', l: '#bfaea7', M: '#a1887f', D: '#7f6760', S: '#5b4842', G: '#4a3a36' },
    pixels: [
      '.....LHLlLl.....',
      '...HlHlHlLMLM...',
      '..HLGGGGGGGMlD..',
      '.LHGGHHLLlGGlMD.',
      '.lGGHLGGGlMGGMD.',
      'LHGLLGGHGGlMGMDD',
      'HGGLGGLlMGGMGMDS',
      'LGlLGlGGMMGDGGDS',
      'lLlMGMGMDGGDGDSD',
      'LlMlGMGGGGDDGSDS',
      'lMlMGGMDDDSGGDSS',
      '.MlMDGGDSDGGSDS.',
      '.DMDMDGGGGGSDSD.',
      '..MDMDSDSDSDSS..',
      '...DMDSDSDSSS...',
      '.....DSDSSS.....',
    ],
  },
  'moon-shell': {
    palette: { W: '#ffffff', H: '#eef2ff', L: '#cfd8ff', M: '#9fb0ff', D: '#7b8bef', S: '#5563cf', N: '#3f46b0', A: '#8a98f2', a: '#f4f6ff' },
    pixels: [
      '........LM.....',
      '.......LHLM....',
      '.....LHHLLMD...',
      '...LSLHLLMMSD..',
      '..LHLSSSSSSMMD.',
      '.LHWHLLLLLLMMD.',
      '.LWHLLLLLLMMMDD',
      'LWHLLLLLLMMMMDD',
      'LWLLLLLMMMMMDDS',
      'LaaaLLMMMMMDDDS',
      'aANNaLMMMMDDDSS',
      'aAANaMMMMDDDDSS',
      '.aAAaMMMDDDDSS.',
      '..aaMMDDDSSSS..',
      '.....DSSSSS....',
    ],
  },
  'ships-bell': {
    palette: { W: '#fff7cc', H: '#ffe680', L: '#ffd23f', M: '#ecb520', D: '#c99700', S: '#946b00', N: '#5c3d00', r: '#c2ab7c', R: '#efe2c0' },
    pixels: [
      '......LMD......',
      '.....LHMMD.....',
      '......DDS......',
      '....LHLMMMD....',
      '...LHWHLMMMD...',
      '...LHWLLMMMD...',
      '...LHHLLMMMD...',
      '...LHLLLMMDD...',
      '..DDDDDDDSSSS..',
      '..LHLLLMMMMDD..',
      '..LHLLLMMMMMD..',
      '.LHLLLLMMMMMDD.',
      'LHHLLLMMMMMMMDS',
      'DLLLLMMMMMMDDDS',
      '.SDDDDDDDDDDSS.',
      '......NMN......',
      '.......r.......',
      '......rRr......',
    ],
  },
  'black-pearl': {
    palette: { N: '#121320', S: '#1d1f30', D: '#2b2d42', M: '#3b3f5c', m: '#4f5577', H: '#c8d1e0', W: '#ffffff', P: '#5b4a86', G: '#2f6f73', R: '#6f7fa8' },
    pixels: [
      '....mMMDD....',
      '..mHHmMMDDS..',
      '.mHWWHmMDDDS.',
      '.mHWHmMMDDDS.',
      'mmHmmMMMDDSSN',
      'mmmmMMMDDSSSN',
      'MMMMMMDDSSSNN',
      'PMMMMDDSSSNNN',
      'PPMDDDSSSNNRN',
      '.GPDDSSSNNRN.',
      '.GGSSSSNNRRN.',
      '..GSSNNNRRN..',
      '....NNNNN....',
    ],
  },
  'mermaid-comb': {
    palette: { W: '#fffbe0', H: '#fff09a', L: '#ffd23f', M: '#f0b429', D: '#c98a0e', S: '#8f5a00', P: '#fdf7ff', U: '#d2fbf1', V: '#a6ecdc', B: '#7fd6c2', b: '#4fb3a3', X: '#2f8a85' },
    pixels: [
      '..H.H.H.H.H.H.H..',
      'H.L.L.L.L.L.M.M.M',
      'L.L.L.L.L.M.M.M.D',
      'L.L.L.M.M.M.M.D.D',
      'M.M.M.M.M.M.D.D.D',
      'LHHWHHHHHHLLLLLMD',
      'LLPLLLMUVBMLMPMMD',
      'MMDMMMMBbXMMMDMDS',
      '.DDDDDDDDDDDDDSS.',
      '......UVBbX......',
      '.....UVBBbbX.....',
      '..UUVVBBBbbbXXX..',
      '.UVVBBb...bbbXXX.',
      'UVVB.........bXXX',
    ],
  },
};
