// Portraits for the dig-site finds (see index.js).

module.exports = {
  'pottery-shard': {
    palette: { H: '#f6c48f', b: '#e9a26a', a: '#c97b4a', A: '#a35d33', D: '#7a4224', c: '#fbe9cf', r: '#e63946' },
    pixels: [
      '.HHHHHbb.......',
      'Hbbbbbbbbbaa...',
      'HcccccccccccaaA',
      'HbbbbbbbbaaaAA.',
      'HbbrrbrrbaaaAA.',
      '.bbrrrrraaaAD..',
      '.baarrraaaAD...',
      '..aaaraaAAD....',
      '..aaaaAAD......',
      '...aaAAD.......',
      '...AAD.........',
      '....D..........',
    ],
  },
  'rusty-nail': {
    palette: { H: '#c98a5a', h: '#b06a3c', a: '#8a4b2a', A: '#6b3520', D: '#4a2414', o: '#d9773a', m: '#8d8d99' },
    pixels: [
      '..HHhha..',
      'HHhhohaaA',
      'hhaaaaAAD',
      '...hAD...',
      '...HaA...',
      '...HoA...',
      '...haA...',
      '...hmA...',
      '...HaA...',
      '...haD...',
      '...hoA...',
      '...haA...',
      '...hhaA..',
      '....haA..',
      '....hhaA.',
      '.....haD.',
      '.....aD..',
      '......D..',
    ],
  },
  arrowhead: {
    palette: { W: '#e6eaee', b: '#adb5bd', B: '#8f979f', a: '#6c757d', A: '#4f5660', D: '#353a42' },
    pixels: [
      '......W......',
      '.....Wba.....',
      '.....bbA.....',
      '....WbbaA....',
      '....bbbaA....',
      '...WBbbaAA...',
      '...bbBbAaA...',
      '..WbbbbaaaA..',
      '..bBbbbaAaA..',
      '.WbbBbbAaaAA.',
      '.bbbbBbaaaAA.',
      'WbbbbbbaaaaAD',
      'bbB..bba..AAD',
      'BB...bba...DD',
      '....bbbaA....',
      '....bbaAD....',
    ],
  },
  trilobite: {
    palette: { W: '#e8ded9', b: '#bcaaa4', B: '#a08a82', a: '#8d6e63', A: '#6d5048', D: '#4e362f', k: '#2e1f1a' },
    pixels: [
      '....bWbbba....',
      '..bbbWWbbaaA..',
      '.bbkaWbbBakaA.',
      'bbakabbbBakaAA',
      'baaaaBBBBaaaaA',
      'a.bbaWbbBaaA.A',
      'A.aADbBBADAD.D',
      'A.bbaWbbBaaA.D',
      'D.aADbBBADAD.D',
      '..bbaWbbBaaA..',
      '..aADbBBADAD..',
      '...baWbbBaA...',
      '...ADbBBADA...',
      '...baWbbBaA...',
      '....aWbBaA....',
      '.....aBAD.....',
      '......AD......',
    ],
  },
  'bug-in-amber': {
    palette: { W: '#fffbe8', b: '#fde6b8', Y: '#ffd27a', a: '#e9a23b', o: '#d4821f', O: '#b0601a', D: '#7a3d12', k: '#5d4037', K: '#3e2a22', n: '#fff0c8' },
    pixels: [
      '.....oooaaa.....',
      '...oWWbaaaaaO...',
      '..oWWkaaaakaaO..',
      '.oWbaakaakaaaaO.',
      'obaaaaaKKaaaaaaO',
      'oaaakkakkakkaaaO',
      'oaakaaKKKKaakaaO',
      'oaaakknKKnkkaaYO',
      'oaakannKKnnakaYO',
      'oaaaannKKnnaaYYO',
      'OaaaannkknnaYbYD',
      '.OaaaanaanaYbWD.',
      '..OoaaaaYYYYOD..',
      '...OOoaaaaOOD...',
      '.....DOOOOD.....',
    ],
  },
  'dino-tooth': {
    palette: { W: '#fffdf3', a: '#f1faee', e: '#e2e4d8', b: '#d6ccc2', B: '#aca2a8', D: '#7d7484', r: '#d9b48a', R: '#a87c52', d: '#6e4c33' },
    pixels: [
      '....rRRRRdd...',
      '...rrRRRRRdd..',
      '..rRRRRRRRRdd.',
      '..eWWaaaeebbBD',
      '..aWWaaaaeebbB',
      '..aWaaaaaeebBD',
      '..aWaaaaaeebbB',
      '.aWWaaaaeebBD.',
      '.aWaaaaaeebbB.',
      '.aWaaaaeebBD..',
      '.aWaaaaeebbB..',
      '.aWaaaeebBD...',
      '.aWaaeebbB....',
      '.aWaaebBD.....',
      '.aaaebbB......',
      'aWaebBD.......',
      'aaebB.........',
      'abD...........',
    ],
  },
};
