// Portraits for the garden finds (see index.js).

module.exports = {
  ladybird: {
    palette: { H: '#ffb3b3', l: '#ff6b6b', r: '#e63946', R: '#b8222f', D: '#7d1424', K: '#4a4d66', k: '#2b2d42', w: '#ffffff' },
    pixels: [
      '......Kkk......',
      '.....wkkkw.....',
      '....kKkkkkk....',
      '...lHlkkkrrr...',
      '..llHlkkkrrrR..',
      '..lHlrrkrrkkR..',
      'kllkkrrkrrkkRRk',
      '.lrkkrrkrrrrRD.',
      '.rrrrrrkrrrRRD.',
      'krrrkkrkrkkRRDk',
      '.rrrkkrkRkkRDD.',
      '..RrrrrkRRRDD..',
      '.kRRkkRkRkkDDk.',
      '....DDDkDDD....',
    ],
  },
  feather: {
    palette: { W: '#e6f6fc', a: '#8ecae6', A: '#5fb0d6', b: '#219ebc', B: '#16708f', q: '#d6eef7' },
    pixels: [
      '..............Wa',
      '............aWbA',
      '..........aWabAA',
      '........aWWabAB.',
      '.......aWWabAAB.',
      '.....aaWaabAAB..',
      '......WaabAAB...',
      '...aWaaabAA.....',
      '..aWaaabAAB.....',
      '...aWaabAB......',
      '...aaabAB.......',
      '...aabB.........',
      '..qab...........',
      '...qb...........',
      '...b............',
      '..q.............',
      '.q..............',
    ],
  },
  daisy: {
    palette: { W: '#ffffff', w: '#eef0f7', v: '#c9cde0', V: '#9fa5c4', Y: '#fff09a', y: '#ffd23f', o: '#e9a23b', O: '#b86b1f', G: '#9be3b9', g: '#57cc99', h: '#2f9e6f', H: '#1f6b4f' },
    pixels: [
      '......WWw......',
      '.WW...WWw...wv.',
      '.WWW..WWw..wwv.',
      '..WWw.Wwv.wwv..',
      '....WvYYyvw....',
      '.WWwvYWYyovwwv.',
      'WWWwvYyyyowwwvv',
      '.wwwvyyyoOvwvv.',
      '...wwvooOvvV...',
      '..wwv.wwv.vvV..',
      '.wwv..wwv..vVV.',
      '.vv...wvv...VV.',
      '......vvV......',
      '.......gh......',
      '.......gh.Ggg..',
      '.......ghGgggh.',
      '.......ghhhH...',
      '.......gh......',
    ],
  },
  'snail-shell': {
    palette: { H: '#e9a26a', a: '#c97b4a', A: '#9a5530', D: '#6b3520', c: '#fbe9cf', b: '#f3d9b1', B: '#d9b78a', k: '#3a1e12', K: '#5a2f1c' },
    pixels: [
      '....HHHHa......',
      '..HHHHHaaaa....',
      '.HHHccbbbbaa...',
      '.HHcHaaaaaaa...',
      'HHcHabbbbbaAA..',
      'HHcabaaaaaBAA..',
      'HHbababbbABAD..',
      'HababaaaBABccb.',
      'aabaabbBAABckkb',
      '.aabaaAAABckkKB',
      '.aaabBBBBAbKKKB',
      '..aaAAADDDBBBBD',
      '....AADDD..DDD.',
    ],
  },
  'seed-packet': {
    palette: { P: '#fff4dc', a: '#fde6b8', A: '#e8c88f', Q: '#c9a46a', s: '#bfe6f5', Y: '#fff09a', y: '#ffd23f', o: '#e9a23b', n: '#6b4423', g: '#57cc99', G: '#2f9e6f', t: '#c97b4a' },
    pixels: [
      'PPPPPPPPPPPA',
      'PAPAPAPAPAPQ',
      'AAAAAAAAAAAQ',
      'asssYyyysssA',
      'assYynnyossA',
      'asYynnnnyosA',
      'asyynnnnoosA',
      'assyonnoossA',
      'asssoogosssA',
      'assggGgssssA',
      'asssssgggssA',
      'aGGGGGgGGGGA',
      'aaaaaaaaaaaA',
      'atttttttttaA',
      'aaaaaaaaaaaA',
      'attttttaaaaA',
      'AAAAAAAAAAAQ',
    ],
  },
  'gnome-hat': {
    palette: { L: '#ff8a8a', r: '#e63946', R: '#b8222f', D: '#7d1424', p: '#5fa8ff', P: '#2864d6', q: '#1d4499' },
    pixels: [
      '.......LLrR..',
      '......LrrRRD.',
      '......LrR..RD',
      '.....LrrR....',
      '.....LrrRR...',
      '....LLrrRR...',
      '....LrrrRR...',
      '...LLrrrrRD..',
      '...LrrrrrRD..',
      '..LLrrppPRD..',
      '..LrrrpPPrRD.',
      '..LrrrPPqrRD.',
      '.LLrrrrrrrRD.',
      '.LrrrrrrrrRRD',
      'LLrrrrrrrrRRD',
      'RRRRRRRRRRRDD',
      '..DDDDDDDDD..',
    ],
  },
  'four-leaf-clover': {
    palette: { W: '#d8f5c0', L: '#9be3b9', b: '#57cc99', B: '#3bb07f', D: '#25805e', a: '#2a9d8f', A: '#1d7076' },
    pixels: [
      '.....LL.bb.....',
      '....LWLbbbb....',
      '....LLbBbbB....',
      '....LbbBbBB....',
      '.LLL.bbBBB.LLb.',
      'LWLbb.bDB.LWbbb',
      'LLbbbb.a.LLbbbB',
      '.bBBBDaaaBBBBB.',
      'bbbbBB.a.bbbBBD',
      'bbbBB.LBbabBBDD',
      '.bBB.LLBbbaBDD.',
      '....LWbBbBBA...',
      '....LbbBBBD.a..',
      '....bbbBBDD.A..',
      '.....bB.DD...a.',
      '.............A.',
    ],
  },
};
