// Portraits for the junk-drawer finds (see index.js).

module.exports = {
  paperclip: {
    palette: { H: '#f4f7fb', a: '#c9d1dc', b: '#a8b2c1', m: '#7f8aa0', d: '#5a6380' },
    pixels: [
      '....HHaab.....',
      '..HH.....ab...',
      '.H.........b..',
      'H...........b.',
      'H....aab....b.',
      'H...a...b...b.',
      'a...a...b...b.',
      'a...a...b...m.',
      'a...a...b...m.',
      'a...b...b...m.',
      'a...b...m...m.',
      'b...b...m...m.',
      'b...m...m....d',
      'b.......m....d',
      'm.......m.....',
      '.m.....d......',
      '..m...d.......',
      '...ddd........',
    ],
  },
  'rubber-band': {
    palette: { H: '#f5c39a', a: '#e09a66', b: '#c97b4a', m: '#9c5534', d: '#6e3526' },
    pixels: [
      '.....HHHaab.....',
      '..HHHaabbbbbbm..',
      '.Habm......mbmd.',
      '.am..........ad.',
      'Hm............ad',
      'am............ad',
      'am............bd',
      '.bm..........bd.',
      '.bbaa......abdd.',
      '..mbbaaaaaabbd..',
      '.....mmmddd.....',
    ],
  },
  button: {
    palette: { H: '#eaf4ff', a: '#b3d3ff', b: '#7fb3ff', m: '#5b8fe0', d: '#3d64b0', e: '#3f68a6', f: '#2b4a7a', g: '#1f365e', k: '#111d38', t: '#fff4dc', T: '#d9c79f' },
    pixels: [
      '.....HHHaab.......',
      '...HHHHaaaabb.....',
      '..HHaaggggabbm....',
      '.Haaggggggffbbm...',
      '.Hagkkgfffkkfbm...',
      'Hagfkgffffkgfemd..',
      'aagffftfftffeemd..',
      'aafffffttffeeemd..',
      'abfffffTTfeeeemd..',
      'bbffffTffTeeeemd..',
      'bbffkkfeeekkeedd..',
      '.bbfkgeeeektemd...',
      '.bmmeeeeeeeetmd...',
      '..bmmmeeeemddT....',
      '...mmmmdddddd.T...',
      '.....dddddd....TT.',
      '.................T',
    ],
  },
  'bottle-cap': {
    palette: { H: '#ffb3ab', a: '#ff6b6b', r: '#e63946', m: '#b8213a', d: '#7f1734', p: '#ffd6d9', P: '#f2a7b0', w: '#fff5f5' },
    pixels: [
      '....HHHaaarr....',
      '..HHaaaaarrrrm..',
      '.HaaPPPPPPPrrrm.',
      'HaaPwwppppppPrrm',
      'aaPppppppppppprm',
      'Haaappppppppprrd',
      'Hraaaappppaaarmd',
      'Hraraaaaaaarrdmd',
      'Hraramamrmrdrdmd',
      '.raramamrmrdrdm.',
      '..aramamrmrdrd..',
      '....a.a.r.r.....',
    ],
  },
  'lost-key': {
    palette: { H: '#fff2b0', a: '#f5d36a', b: '#e2b13c', m: '#b9862a', d: '#86591f', s: '#e8dcc0', c: '#fff4dc', C: '#e0cfa8', q: '#8a6a4a' },
    pixels: [
      '..HHaa............',
      '.HHaaab...........',
      'Ham..bbmam........',
      'am....amamaHHaaaab',
      'am....adbdmmmmmmmd',
      'bba.samdmd.abbbbbm',
      '.mbasmd....am.am.m',
      '..mmsd.....bd....d',
      '....s.............',
      '...ccC............',
      '..cqqcC...........',
      '..cccqC...........',
      '..ccqcC...........',
      '..ccccC...........',
      '..ccqcC...........',
      '..CCCCC...........',
    ],
  },
  'guitar-pick': {
    palette: { H: '#f6e6ff', a: '#dcaaff', b: '#c77dff', r: '#9d4edd', m: '#7b2fbf', d: '#55208f' },
    pixels: [
      '...aaabbbbr...',
      '.aHHabbbbbbbr.',
      'aHaabbbbbbbbrm',
      'aaabbbbbarbrrm',
      'babbbbbarbrrrm',
      '.bbbbbaaarrrm.',
      '.bbbbbbamrrrm.',
      '..bbbbamrrrm..',
      '..bbbbrrrrrm..',
      '...bbrrrrrm...',
      '....rrrrrm....',
      '....mrrrmd....',
      '.....rrmd.....',
      '......md......',
    ],
  },
  'usb-stick': {
    palette: { S: '#f7f7f7', s: '#c0c0c0', t: '#8d94a0', T: '#4a5163', H: '#8a8fb0', a: '#5d6285', b: '#3d405b', m: '#2b2d42', d: '#1d1e2e', w: '#fff4e4', W: '#d9cdb8', q: '#3a6ea5', f: '#e63946' },
    pixels: [
      '..SSssst..',
      '..STssTt..',
      '..STssTt..',
      '..Ssssst..',
      '..Ssssst..',
      '.Haaaabbm.',
      'Haaaabbbbm',
      'HawwwwwWbm',
      'HawqqqwWbm',
      'HawwwwwWbm',
      'aawffwfWbm',
      'aawwwwwWbm',
      'aaWWWWWWbm',
      'aabbbbbbmm',
      'abbb..bbmd',
      'abbb..bbmd',
      'bbbbaabbmd',
      '.mmmmmmdd.',
    ],
  },
  'safety-pin': {
    palette: { H: '#ffffff', a: '#e4e8ee', s: '#c0c0c0', m: '#8d94a0', d: '#5e6573' },
    pixels: [
      '..............Has.',
      '...........aaHaasm',
      '.......aHHa...Hsmd',
      '.HHaaaa........asm',
      'H...s..........asm',
      'a...m..........asd',
      's...maassssssssmmd',
      '.mmd...........md.',
    ],
  },
  battery: {
    palette: { H: '#7d82a8', K: '#4f5478', k: '#3a3d58', b: '#2b2d42', m: '#1c1d2c', Y: '#fff6c2', y: '#ffe36b', o: '#ffd23f', O: '#e6a92c', q: '#b9781c', S: '#f2f2f2', s: '#c0c0c0', t: '#8d94a0' },
    pixels: [
      '...Ssst...',
      '...sstt...',
      '.KHKkbbbm.',
      'kKHKkbbbmm',
      'kKHKkybbmm',
      'kKHKyyybmm',
      'kKHKkybbmm',
      'kKHKkbbbmm',
      'kKHKkbbbmm',
      'oyYyoooOOq',
      'oyYybboOOq',
      'oyYyoobOOq',
      'oyYyoboOOq',
      'oyYyoooOOq',
      'oyYyoboOOq',
      'oyYyoooOOq',
      'oyYyoooOOq',
      '.oooOOOqq.',
    ],
  },
  'sticky-note': {
    palette: { Y: '#fff6b8', a: '#ffe066', o: '#f2c94c', O: '#c9a227', w: '#fffbe6', k: '#3d4a7a', r: '#e63946' },
    pixels: [
      'YYYYYYYYYYYYYYYo',
      'Yaaaaaaaaaaaaaao',
      'Yaaaaaaaaaaaaaao',
      'Yakakkakaaaaaaao',
      'Yakkkkkkkaaaaaao',
      'Yaaaaaaaaaaaaaao',
      'Yakaakakaakaaaao',
      'Yakkkkkkkkkkaaao',
      'Yaaaaaaaaaaaaaao',
      'Yarrrrrrrrrrraao',
      'Yaaaaaaaaaaaaaao',
      'Yaaaaaaaaaaaaaao',
      'YaaaaaaaaaaawwYO',
      'YaaaaaaaaaaawYO.',
      'YaaaaaaaaaaaYO..',
      'YoooooooooooO...',
    ],
  },
};
