// Portraits for the night finds (see index.js).

module.exports = {
  'glow-stick': {
    palette: { W: '#f4fffb', b: '#c8fff0', a: '#80ffdb', A: '#3fd6b0', p: '#4bb8a6', P: '#2f9488', Q: '#20666a' },
    pixels: [
      '...........pp.',
      '..........ppPQ',
      '.........abbbA',
      '........abWbA.',
      '.......abWbA..',
      '......abWbA...',
      '.....abWbA....',
      '....abWbA.....',
      '...abWbA......',
      '..abWbA.......',
      '.abWbA........',
      'abbbA.........',
      'pPQQ..........',
      '.QQ...........',
    ],
  },
  moth: {
    palette: { L: '#d8caa9', a: '#b5a48b', b: '#7f6f58', B: '#5e5141', D: '#463c31', e: '#3a2f27', k: '#3a2f27', F: '#efe3c8', f: '#d2c3a2' },
    pixels: [
      '...Bb......bB...',
      '....ab....ba....',
      '......b..b......',
      '..LLLL.kk.LLLL..',
      'LLaaaaaFfaaaaaLL',
      'bbaeaaaFfaaaeabb',
      '.aaabbabBabbaaa.',
      '..BBBbaBBabBBB..',
      '..baaaabBaaaab..',
      '..baeaaBDaaeab..',
      '...BbbabBabbB...',
      '....BB....BB....',
    ],
  },
  'firefly-jar': {
    palette: { o: '#b08d67', a: '#8a6a4a', k: '#664c34', K: '#4a3626', W: '#eefcfc', L: '#c9eced', g: '#a8dadc', G: '#6aa6b0', N: '#3f7280', n: '#24485a', h: '#6e8a5c', y: '#ffd23f', Y: '#fff8d6', d: '#3a2f27' },
    pixels: [
      '........dyY...',
      '...ooooaaak...',
      '..oaaaaaaakK..',
      '..oakakakakK..',
      '..LWggggggGG..',
      '.LWLnnnnnnnNG.',
      '.LWnnnnnnynNG.',
      '.LWnnhyhnnnNG.',
      '.LWnhyYyhnnNG.',
      '.LWnnhyhnnnNG.',
      '.LWnnnnnnnnNG.',
      '.LWnnnnnhyhNG.',
      '.LWnhnnhyYyhG.',
      '.LWhYhnnhyhNG.',
      '.LWnhnnnnnnNG.',
      '.LgNNNNNNNNgG.',
      '..LgggggggGG..',
    ],
  },
  'owl-feather': {
    palette: { L: '#c9b3a8', a: '#a1887f', m: '#7d6359', b: '#5d4037', D: '#3e2a24', Q: '#e8dcd2', q: '#d6c4b6' },
    pixels: [
      '..........Lb.',
      '........bLaab',
      '.......bbbaQm',
      '......LabbbQm',
      '.....baaabQbm',
      '....bbbaaQbD.',
      '...LabbbQaaD.',
      '...LaabQbam..',
      '..bbaaQbbD...',
      '..bbbQaaD....',
      '..LbQbam.....',
      '..LQbDD......',
      '..qmm........',
      '.q...........',
      '.q...........',
      'q............',
    ],
  },
  moonstone: {
    palette: { W: '#ffffff', c: '#f4f7ff', a: '#dfe7fd', G: '#c8dcff', S: '#a9c0ff', b: '#a5b4fc', B: '#8190ee', D: '#6366d1' },
    pixels: [
      '....aaaaaab....',
      '..acccaaaaabb..',
      '.acWWcaaaaaabb.',
      'acWcaaaGGGaabbB',
      'accaaGGWGGSabbB',
      'aaaaGGGGGSSbbBB',
      'aaaaaGGSSSbbbBB',
      'baaaaaSSbbbbBBD',
      '.bbaaaabbbbBBD.',
      '..BbbbbbbbBBD..',
      '....BBBBBDD....',
    ],
  },
  'fallen-star': {
    palette: { W: '#ffffff', w: '#fff4b3', y: '#ffd23f', o: '#f5a524', O: '#e0791c', k: '#8a4210', p: '#ffab73' },
    pixels: [
      '.......yo.......',
      '.......wy.......',
      '......ywwo......',
      '......wWwy......',
      '.....ywWWwo.....',
      'yyyyywwWWwwyyyyo',
      '.ywwwwWWWWwwwyo.',
      '..ywwkWWWWkwwo..',
      '...ykwkWWkwko...',
      '....ypwWwwpo....',
      '....ywkwwkwo....',
      '...yywwkkwyoo...',
      '...yyyo..yyoO...',
      '..yyoo....yooO..',
      '..yoO......oOO..',
      '.oO..........OO.',
    ],
  },
};
