// Portraits for the pirate finds (see index.js).

module.exports = {
  'old-coin': {
    palette: { H: '#f6e4bd', L: '#e4c896', b: '#d4b483', a: '#b08d57', A: '#86643c', g: '#9aa88a' },
    pixels: [
      '......HHLL......',
      '....HHHHLLLb....',
      '...HHaaaaaabb...',
      '..HHabbbbbbbbb..',
      '.HHabbbbbbbbbaa.',
      '.HabHabHHabLbLa.',
      'HHabHHaHLaLLaLaa',
      'HHabHLHLLHLLaLaa',
      'LLabHLaLLaLLaLAA',
      'LLabHLLLLLLLaLAA',
      '.LabaaaaaaaaaLA.',
      '.ggbbbbbbbbbLAA.',
      '..gbbbbbbbbLAA..',
      '...baLLLLLLAA...',
      '....aaaaAAAA....',
      '......aaAA......',
    ],
  },
  compass: {
    palette: { H: '#f0d9a8', L: '#d4b483', a: '#b08d57', A: '#86643c', D: '#5c4330', b: '#fff4e4', F: '#e6d5bd', T: '#b39b7a', W: '#ffffff', r: '#e63946', R: '#a8243a', w: '#3d405b', K: '#25263a' },
    pixels: [
      '......La......',
      '.....L..A.....',
      '.....HLaa.....',
      '...LHAAAAaa...',
      '..HAAbTTbAaa..',
      '.LAbbWbbbbraa.',
      '.LAbWbbbbrRaa.',
      'LAbbbbbbrRbbaa',
      'LATbbbbaRbbTaa',
      'LATbbbwKbbbTLA',
      'aabbbwKbbbFFLA',
      '.aabwKbbbFFLA.',
      '.aawbbbbFFFLA.',
      '..aLLFTTFLLA..',
      '...aALLLLAD...',
      '.....AADD.....',
    ],
  },
  'tiny-anchor': {
    palette: { H: '#b8d0e6', L: '#7f9fbd', a: '#577590', A: '#3f5878', D: '#2d3d5c' },
    pixels: [
      '......La......',
      '.....L..A.....',
      '.....aLAA.....',
      '.HLLLLLLLLLLa.',
      '..aAAAAAAAAD..',
      '......LA......',
      '......LA......',
      '......LA......',
      '.L....LA....L.',
      'LLa...LA...LLa',
      '.La...LA...La.',
      '.La...LA...La.',
      '..La..LA..La..',
      '...LLLLALLa...',
      '....aAAAAD....',
    ],
  },
  'message-bottle': {
    palette: { o: '#b08d67', a: '#8a6a4a', k: '#5e4530', W: '#f0ffff', L: '#d3f0f0', c: '#a8dadc', C: '#78b8c0', G: '#4f8f9c', d: '#fff4e4', e: '#e3cfae', r: '#e63946', R: '#a8243a' },
    pixels: [
      '...oaak...',
      '...oaak...',
      '..LcccCG..',
      '...LccC...',
      '...LccC...',
      '..LWccCG..',
      '.LWccccCG.',
      'LWccccccCG',
      'LWceddecCG',
      'LWcdddecCG',
      'LWcdddecCG',
      'LWcrrrRcCG',
      'LWcdddecCG',
      'LWcdddecCG',
      'LWceddecCG',
      'LLccccccCG',
      'LcccccCCGG',
      '.CCCCCGGG.',
    ],
  },
  'treasure-map': {
    palette: { P: '#f7ecd0', a: '#e9d8a6', b: '#c9b38a', B: '#a88e64', k: '#6b4a2e', c: '#e63946', R: '#a8243a' },
    pixels: [
      'PPPPPPPPPPPPPa....',
      'PaaaaaaaaaaaBba...',
      'PaaaaaaabbaaBbba..',
      'PaaakaakaaaaBbbba.',
      'PaakakkakaaaBbbbba',
      'PaaaaaaaaaaaaBBBBb',
      'aaaaaaaaaaacacaaa.',
      'aaaaaaaaaaaacaaaab',
      '.aaaaaaaaaacaRaaab',
      'aaaaaaaaakaaabbab.',
      'aaaaaaakaaaaaaaaab',
      'aaaaakaaaaaaaaaab.',
      'akakaaaaaaaaaaaabb',
      'bbbb.bbbbbb.bbb.b.',
    ],
  },
  eyepatch: {
    palette: { l: '#62668a', s: '#3d405b', W: '#8c91b8', H: '#5d6288', L: '#43465f', k: '#2b2d42', K: '#1c1d2c', m: '#9a9fbf', n: '#6c7194' },
    pixels: [
      'ls................',
      '.ls...............',
      '..ls..............',
      '...ls..LHHLLk...ls',
      '....lLHWHLkkkkKls.',
      '.....HHLkkkkkkK...',
      '.....LkkmmmkkkK...',
      '.....kkmKmKmkKK...',
      '......kmmmmmKK....',
      '......kkmnmkKK....',
      '.......kKKKKK.....',
      '........KKKK......',
    ],
  },
  spyglass: {
    palette: { W: '#f0ffff', c: '#a8dadc', C: '#6fa8b8', H: '#fff0c4', L: '#e2c48e', a: '#b08d57', A: '#86643c', D: '#5c4330', p: '#c9a27a', n: '#a8825c', b: '#8a6a4a', B: '#664c34', N: '#463224' },
    pixels: [
      '.LLLLL............',
      'WHHHHHnnnLnnnL....',
      'WLLLLLpppHpppHHHHL',
      'caaaaabbbabbbaaaaa',
      'caaaaaBBBABBBAAAAA',
      'CAAAAANNNDNNND....',
      '.DDDDD............',
    ],
  },
  'gold-doubloon': {
    palette: { W: '#ffffff', c: '#fff4b3', L: '#ffe36e', b: '#ffd23f', m: '#eab422', a: '#c99700', A: '#a86500', D: '#7a3f00' },
    pixels: [
      '.......cLLb.......',
      '....cWWccLLbA.....',
      '...cccaaaaaA......',
      '..ccaabbbbbA......',
      '.ccaacbccccmL.....',
      '.ccacWcmcLmmbL....',
      '.cabbcbbcLmbbbcLb.',
      'ccabcmbbcLmbbcmLaa',
      'LcabccccLLcccLmLaa',
      'LLabcLLLLLLLLLmLAA',
      'LLabcmmmcLmmmcmLAA',
      '.LabmmbbcLmbbmmLA.',
      '.LbmbbbbcLmbbbLAA.',
      '.bbmmbbcLLcmbLLAA.',
      '..bbmmbmmmmmLLAA..',
      '...bbaLLLLLLAAA...',
      '....aaaaaAAAAD....',
      '.......aAAD.......',
    ],
  },
};
