// Portraits for the seasons finds (see index.js).

module.exports = {
  'candy-corn': {
    palette: { W: '#ffffff', w: '#fff4e4', v: '#e6d2c2', H: '#ffc061', o: '#ff9f1c', O: '#e8730f', n: '#ffe2b0', u: '#ffe680', y: '#ffd23f', Y: '#eba92a', Z: '#c7811f' },
    pixels: [
      '......W......',
      '.....Wwv.....',
      '.....Wwv.....',
      '....Wwwwv....',
      '....wwwwv....',
      '...HoooooO...',
      '...HnoooOO...',
      '..HHnooooOO..',
      '..HooooooOO..',
      '.HoooooooOOO.',
      '.uyyyyyyyyYY.',
      'uuyyyyyyyyyYY',
      'uyyyyyyyyyyYY',
      'uyyyyyyyyyYYZ',
      '.YYYYYYYYYZZ.',
    ],
  },
  snowflake: {
    palette: { W: '#ffffff', h: '#f2feff', a: '#c4eef5', b: '#86c8e6' },
    pixels: [
      '........h........',
      '......h.h.h......',
      '...h...hhh...a...',
      '..hh....h....aa..',
      '....h...a...a....',
      '.....h..a..a.....',
      '.h....a.a.a....b.',
      '..h....aaa....b..',
      'hhhhaaaa.aaaabbbb',
      '..h....aaa....b..',
      '.h....a.a.a....b.',
      '.....a..a..b.....',
      '....a...a...b....',
      '..aa....b....bb..',
      '...a...bbb...b...',
      '......b.b.b......',
      '........b........',
    ],
  },
  'heart-locket': {
    palette: { g: '#ffe08a', G: '#c99a3a', P: '#ffc2d1', b: '#fff4f7', a: '#ff8fab', A: '#e5638c', D: '#b8406e' },
    pixels: [
      '......gGg......',
      '......g.G......',
      '......gGG......',
      '.PPPaa.G.aaaAA.',
      'PbbPaaaGaaaaaAA',
      'PbPDDaaaaaDDaAA',
      'PPaaDaDaDaDaaAA',
      'PaaaaDDDDDaaAAD',
      '.aaaDDDDDDDaAD.',
      '..aDaDaaaDaDD..',
      '...aaaaaaAAD...',
      '....aaaaAAD....',
      '.....aaAAD.....',
      '......aAD......',
      '.......D.......',
    ],
  },
  'painted-egg': {
    palette: { W: '#ffffff', h: '#e6fff6', a: '#b8f2e6', A: '#86d6cc', D: '#5aa8b0', p: '#ffc2d1', b: '#ff8fab', B: '#e0628f', y: '#ffe08a', c: '#ffd166', C: '#eaa83a', O: '#c98426' },
    pixels: [
      '....hhaa....',
      '...hhhaaA...',
      '..hhWhaaaA..',
      '.hhWhaaaaAA.',
      '.hhabaaabaA.',
      '.phbbbabbBA.',
      'hppbabbbaBBB',
      'hhpaaabaaaBA',
      'hhaaaaaaaaAD',
      'ycccccccccCO',
      'ccccccccCCCO',
      'aaaaaaaaaAAD',
      '.aabaabaABD.',
      '..aaaaAADD..',
      '...AAADDD...',
    ],
  },
  'beach-ball': {
    palette: { W: '#ffffff', q: '#ff8a70', a: '#ff5a4a', A: '#d63a4a', Q: '#a3244a', b: '#fff4e4', B: '#d9d4e0', V: '#a9a6c4', u: '#6aa8ff', c: '#3a86ff', C: '#2a5fd6', K: '#2440a3' },
    pixels: [
      '.....uuccc.....',
      '...bbuuqaaaA...',
      '..bWbbbqaaaaA..',
      '.bbWbbbbaaaaAA.',
      '.qqbbbbbbbaAAA.',
      'aqquubbbbbbBAAQ',
      'aquuccbbbbBBBQQ',
      'aaccccbbbBBBBVQ',
      'aacccccbBBBBVVQ',
      'aacccccBBBBVVVV',
      '.acccCCCBBVVVV.',
      '.ACCCCCCBVVVVV.',
      '..CCCCCKKVVVV..',
      '...KKKKKKVVV...',
      '.....KKKKK.....',
    ],
  },
  acorn: {
    palette: { c: '#a8784f', b: '#7f5539', B: '#5e3b26', D: '#3f2617', W: '#f7d2a8', h: '#e8a56f', a: '#c97b4a', A: '#a35a35', N: '#7a3e2a' },
    pixels: [
      '......bB.....',
      '......bB.....',
      '....cbbbB....',
      '..bcbbcbbBB..',
      '.cbbcbbcbBbD.',
      'bbcbbcbbcBBbD',
      'bBBBBBBBBBBDD',
      '.AAAAAAAAANN.',
      '.hWaaaaaaaAN.',
      '.hWaaaaaaaAN.',
      '.hhaaaaaaAAN.',
      '.haaaaaaaAAN.',
      '..haaaaaAAN..',
      '...aaaaAAN...',
      '....aaAAN....',
      '.....aAN.....',
      '......N......',
    ],
  },
};
