// Portraits for the finds in no set: the seasonal extras, the fortune cookie
// and the two keepsakes (see index.js).

module.exports = {
  'fortune-cookie': {
    palette: { H: '#fde0a0', h: '#f6c56a', a: '#e9a23b', A: '#c97d26', D: '#93531c', c: '#fde6b8', C: '#e8c48a', w: '#fffaf0', W: '#e6dccb', r: '#d1495b' },
    pixels: [
      '....HHHHHH........',
      '..HHhhhhaaaaa.....',
      '.Hhhaaaaaaaaaaa...',
      'Hhhaaaaaaaaaaaaa..',
      'hhaaaaaaAaaaaaaAA.',
      'haaaaaaACAaaaaaAA.',
      'haaaaaACcCAaaaaAA.',
      'aaaaaACccwwwwwwwwW',
      'aaaaACcccwrrwrrrwW',
      'AaaaACccCWWWWWWWWW',
      '.AAADCCC.AAAAD....',
      '..DD......DD......',
    ],
  },
  'tiny-pumpkin': {
    palette: { Y: '#ffd98a', h: '#ffb547', o: '#ff9f1c', O: '#e2741a', D: '#b04f1c', G: '#5fd1bf', g: '#2a9d8f', S: '#1d6d6a', k: '#2b2d42', f: '#ffe066', F: '#ff8c1a' },
    pixels: [
      '........GS......',
      '.......GgS......',
      '...hhhhhgSoooo..',
      '.hYYhhhoSooooOO.',
      'hYYhhhoOoooooOOO',
      'hYhhhhOoooooooOD',
      'hYhkkkOoookkkOOD',
      'hhhhffOooooffOOD',
      'hhhhhOoooooooOOD',
      'hhhOoooooooookOD',
      'hhhOkkkkkkkkkOOD',
      'hhOOOffffffFOODD',
      '.hOOooFFFFOOOODD',
      '..DOOOooooOOODD.',
      '....DDDDDDDDD...',
    ],
  },
  'lost-mitten': {
    palette: { H: '#ff8a92', h: '#f2555f', r: '#e63946', R: '#b8283a', D: '#7f1730', w: '#fff4e4', W: '#e3cfbd', S: '#b9a08f' },
    pixels: [
      '.....hhhhh.....',
      '...hhHHhrrrr...',
      '..hHHhrrrrrrR..',
      '..hHrrrrrrrrRR.',
      'hh.hrrrwrrrrRR.',
      'hHhhrrwrwrrrRR.',
      'hHhDrrrwwwrrRR.',
      'hHrDrrwrwrrrRR.',
      'hrrRrrrwrrrrRR.',
      '.hrrRrrrrrrrRR.',
      '..rrrrrrrrrRRD.',
      '...RrrrrrrrRRD.',
      '...RRrrrrrRRD..',
      '..wwwwwwwwwwW..',
      '..wWwWwWwWwWS..',
      '..wWwWwWwWwWS..',
      '..SSSSSSSSSSSR.',
      '.............RR',
    ],
  },
  'candy-heart': {
    palette: { H: '#fff0f4', L: '#ffd3df', p: '#ffb3c6', P: '#f292ad', D: '#d86d8f', k: '#ff5d8f' },
    pixels: [
      '...LLLL....LLLL...',
      '.LHHHLLpp.LLppppP.',
      'LHHLLLpppppppppPPD',
      'LHLLpppppppppppPPD',
      'LLLpkkppkkkpppppPD',
      'LLppkpkpkppppppPPD',
      'pLppkkppkkpppppPPD',
      'pLppkpkpkppppppPPD',
      '.pppkkppkkkpppPPD.',
      '..pppppppppppPPD..',
      '...pkkpkpkkpkkD...',
      '....pppppppPPD....',
      '.....ppppPPPD.....',
      '......pppPDD......',
      '.......PPDD.......',
      '........DD........',
    ],
  },
  'robin-egg': {
    palette: { H: '#f2feff', L: '#c4f9ff', a: '#9bf6ff', b: '#6fd3e0', B: '#47aac0', i: '#d8f3f2', I: '#6fb3c0' },
    pixels: [
      '..L....a...b.',
      '.LLLi.aaa.ib.',
      '.LHLiIaaaIib.',
      '.LHaIIaaaIIb.',
      'LLHaaIIaIIabb',
      'LHHaaaaaaaabb',
      'LHaaaaaaaaabb',
      'LLaaaaaaaaabb',
      'Laaaaaaaaaabb',
      'aaaaaaaaaabbB',
      'aaaaaaaaaabbB',
      '.aaaaaaaabbB.',
      '.aaaaaaaabbB.',
      '.baaaaaabbBB.',
      '..bbaaabbBB..',
      '...BBBBBBB...',
    ],
  },
  'lolly-stick': {
    palette: { H: '#fbf1d2', h: '#f2e3b8', a: '#e9d8a6', A: '#cdb57f', D: '#a88b5a', k: '#4a6fa5' },
    pixels: [
      '..h...',
      '.Hha.a',
      'HhaaaA',
      'Hhaa.A',
      'HhkkaA',
      'HhakaA',
      'HhkkaA',
      'HhaaaA',
      'HhkkaA',
      'HhakaA',
      'HhkkaA',
      'HhaaaA',
      'HhkaaA',
      'HhkkaA',
      'HhaaaA',
      'hhaaAD',
      '.haAD.',
      '..DD..',
    ],
  },
  'red-leaf': {
    palette: { H: '#ff6f61', h: '#ef3b33', r: '#d62828', R: '#a8141c', D: '#7a0a14', b: '#9d0208' },
    pixels: [
      '........h........',
      '.......hhr.......',
      '.......hbr.......',
      '..H....hbr....r..',
      '..HH..hhbrr..rR..',
      'H.Hhh.hhbrr.rrR.R',
      'HHhbhhhhbrrrrDrRR',
      '.hhhbhhhbrrrDrrR.',
      '..hhhbhhbrrDrrR..',
      'hhhhhhbhbrDrrRRRR',
      '.hhbbbbbbDDDDrRR.',
      '...hhhhhbrrrRR...',
      '.....hh.b.rR.....',
      '........b........',
      '........b........',
      '.......b.........',
    ],
  },
  'cake-slice': {
    palette: { w: '#ffffff', f: '#fff4e4', F: '#f0dcc8', E: '#d6b9a6', y: '#ffd29a', p: '#f4a261', P: '#d9803f', Q: '#a85a2a', j: '#e63946', c: '#ff6b6b', C: '#e63946', K: '#a81e32', g: '#6a994e', b: '#4cc9f0', Y: '#ffd23f', m: '#ff8fab' },
    pixels: [
      '............g.....',
      '...........g......',
      '..........cCC.....',
      '.........cwCCK....',
      '.......wwfCKKKF...',
      '.....wwfbffKKfFF..',
      '...wwffffffmfffFE.',
      '.wwfmfffYffffbfFEE',
      'fffffffffffffffFEE',
      'yffyyyfyyyffyyfFEE',
      'yyfyyyyyyyyfyyyFFE',
      'pppppppppppppppFFE',
      'jjjjjjjjjjjjjjjFEE',
      'fffffffffffffffFEE',
      'ppppppppppppppPFEE',
      'PPPPPPPPPPPPPPPEE.',
      'QQQQQQQQQQQQQQQE..',
    ],
  },
  'hatch-candle': {
    palette: { R: '#f0641e', o: '#ff9f1c', y: '#ffd23f', l: '#fff3a8', W: '#ffffff', k: '#3a2a26', w: '#fff4e4', s: '#e8d6c6', S: '#c9b0a3', p: '#ff8fab', P: '#e0668b', h: '#ffe1cf', c: '#ffcdb2', C: '#f2a48c', E: '#c97a6a' },
    pixels: [
      '......R......',
      '.....oyR.....',
      '.....oyoR....',
      '....oylyR....',
      '....oylyoR...',
      '....ylWlyR...',
      '....oWWWyR...',
      '.....oyyR....',
      '......k......',
      '...WwwwwsS...',
      '...WwwppsS...',
      '...WwppwsP...',
      '...WppwwPP...',
      '...ppwwpPS...',
      '...pwwppsS...',
      '.hhccccccccC.',
      '..cCcCcCcCE..',
      '...EEEEEEE...',
    ],
  },
};
