// Portraits for the tides finds (see index.js).

module.exports = {
  'golden-wheat': {
    palette: { u: '#fff0b3', y: '#ffd166', Y: '#e9a23b', O: '#b8782a', g: '#a8844a', G: '#6e5230', r: '#d0603e', R: '#94382a' },
    pixels: [
      '.......u.......',
      '......uyY......',
      '..u...uyY...u..',
      '.uyY.uyyYO.uyY.',
      'uyyYO.uyY.uyyYO',
      '.uyY.uyyYO.uyY.',
      'uyyYO.uyY.uyyYO',
      '.uyY.uyyYO.uyY.',
      'uyyYO.uyY.uyyYO',
      '.uyY...g...uyY.',
      '...g...g...G...',
      '....g..g..G....',
      '.....rrrrR.....',
      '.....RRRRR.....',
      '.....g.g.G.....',
      '....g..g..G....',
      '...g...g...G...',
      '..g....g....G..',
    ],
  },
  'lantern-gourd': {
    palette: { s: '#4f9a5a', S: '#2b6236', l: '#7fc77a', h: '#f4a07a', o: '#e76f51', O: '#c4523a', D: '#8f3a2e', y: '#ffd166', u: '#fff6c2' },
    pixels: [
      '.......sS......',
      '.......sSll....',
      '...hhoODDoOO...',
      '.hhoOhoooODoOO.',
      'ohhoOhoooODoOOD',
      'ohhoyhoooOyoOOD',
      'ohhyuyoooyuyOOD',
      'ohhoOhoyoODoOOD',
      'ohhoOhoooODoOOD',
      'ohhyOhoooODyOOD',
      'ohooyuuOuuyoOOD',
      '.oooOyyyyyDOOD.',
      '..ooOOoooODOD..',
      '....OOOODDD....',
    ],
  },
  'ghost-lantern': {
    palette: { K: '#5c6080', k: '#2b2d42', J: '#1c1d2e', H: '#2d9a6e', g: '#57cc99', G: '#b8ffd9', w: '#f0fff7', e: '#1f6f55' },
    pixels: [
      '....KKkk....',
      '...K....k...',
      '...K....k...',
      '..KKKKKkkk..',
      '.KkgkgkgkkJ.',
      'KKkkkkkkkkJJ',
      '.KHHggggHHJ.',
      '.KHgGGGGgHJ.',
      '.KgGwwwwGgJ.',
      '.KgGewweGgJ.',
      '.KgGwwwwGgJ.',
      '.KgGweewGgJ.',
      '.KHgGwwGgHJ.',
      '.KHHggggHHJ.',
      'KKkkkkkkkkJJ',
      '.KkkkkkkkkJ.',
    ],
  },
  'cursed-doubloon': {
    palette: { W: '#f8ffd0', b: '#e0e78f', B: '#c4cf6a', a: '#9bb34a', A: '#6f8a32', D: '#4a5e22', k: '#2b2d42', G: '#b8ffd9' },
    pixels: [
      '.....bbbbb.....',
      '...bbbbbbbaa...',
      '..bbAAAAAAAaA..',
      '.bbAaabbbaabaA.',
      '.bAaabWbbBabAA.',
      'bbAabWbbbbBbaAA',
      'bbAabkGbGkBbaAA',
      'baAabkkbkkBbAAD',
      'baAaabbkbBabADD',
      'aaAaakbkbkabADD',
      '.aAaaabBBaabAD.',
      '.aaBBBBBBBBBDD.',
      '..aAAAAAAADDD..',
      '...AAAADDDDD...',
      '.....ADDDD.....',
    ],
  },
  'ice-crystal': {
    palette: { W: '#ffffff', h: '#d4f1fb', c: '#b5e3f3', i: '#8ecae6', I: '#5ea6d4', D: '#3d76b8' },
    pixels: [
      '.....W.....',
      '....Whi....',
      '...Whhhi...',
      '..WWhhhii..',
      '.WWhhhhhii.',
      'hhhcccccIID',
      'hWhcWcccIID',
      'hWhcccccIID',
      'hWhcccccIID',
      'hhhcccccIID',
      'hhhcccccIID',
      'hhhcccccIDD',
      '.cciiiiiDD.',
      '..cciiiDD..',
      '...ciiiD...',
      '....ciD....',
      '.....i.....',
    ],
  },
  'frozen-bug': {
    palette: { W: '#ffffff', h: '#eef9ff', i: '#cdeafe', j: '#b0d8f2', I: '#8ecae6', D: '#5a9cc4', r: '#e63946', R: '#a8243a', p: '#ff8f96', k: '#2b2d42' },
    pixels: [
      '...hhhhhhhhhhhh',
      '..hWhhhhhhhhhhI',
      '.hhWhhhhhhhhhII',
      'WWWWWWhhhhhhIII',
      'hiiWihiiiiijIII',
      'hiWihiiiiiijIII',
      'hWihkiikiiijIID',
      'hiiiikkiiiijIID',
      'hiiiprrRiiijIID',
      'hiikprkRkiijIID',
      'hiWirkrRiiijIID',
      'hiikiRRikiijIID',
      'hiiiiiiiiWijIDD',
      'hjjjjjjjjjjjDD.',
      'IIIIIIIIIIIDD..',
    ],
  },
  'love-letter': {
    palette: { W: '#ffffff', w: '#fff4e4', v: '#e6d5b8', V: '#cbb894', c: '#e3cfa6', b: '#c9b38a', B: '#a68d62', p: '#ffb3c6', r: '#ff5d8f', R: '#c9184a' },
    pixels: [
      'ccccccccbbbbbbbB',
      'vcbbbbbbbbbbbbBv',
      'wvcbbbbbbbbbbBvV',
      'wwvbbbbbbbbbBvwV',
      'WwwvbbbbbbbBvwwV',
      'wwwwvbbbbbBvwwwV',
      'wwwwwprbBrRwwwwV',
      'wwwwvprrrrRvwwwV',
      'wwwvwrrrrRRwvwwV',
      'wwvwwwrrRRwwwvwV',
      'wvwwwwwRRwwwwwvV',
      'vvvvvvvvVVVVVVVV',
    ],
  },
  'paired-shells': {
    palette: { c: '#fff4f7', a: '#ffc2d1', A: '#ee8fac', E: '#c96a8c', d: '#ffd6e0', b: '#ff8fab', B: '#e0698e', F: '#b04a72' },
    pixels: [
      '..AccAaaE.........',
      '.cAccAaaEA........',
      'cccAcAaEaAA.......',
      'ccaAcAaEaEEdBbbF..',
      '.caAaAaEEBddBbbFB.',
      '..aAaAaEddBdBbFbBB',
      '...AaAAEdbBdBbFbBF',
      '..aaAAAAEbBbBbFBB.',
      '...AAEEE.bBbBbFB..',
      '..........BbBBF...',
      '.........bbBBBBF..',
      '..........BBFFF...',
    ],
  },
  'feather-duster': {
    palette: { q: '#ffd1dc', p: '#ffb3c6', P: '#e88aa6', R: '#c7698a', u: '#fff0b3', y: '#ffd166', Y: '#e9a23b', O: '#c47f24', g: '#ffe08a', G: '#c99a3a', h: '#b08a64', b: '#8a6a4a', B: '#5e4632' },
    pixels: [
      '...q....uy......',
      '..qpP..uyY......',
      '..qpP.uyyY......',
      'u.qppuuyYY..qp..',
      'uyqppuuyYqqppP..',
      'uyqquuyyYqppP...',
      'uyqpuyyYYppP....',
      'uyqPuyyYYpPP....',
      '.yqPuyYYOpPPuyyY',
      '..yYgGPRRPyyYY..',
      '...gGGYYYYYYY...',
      '...hbB..........',
      '...hbB..........',
      '..hbB...........',
      '..hbB...........',
      '.hbB............',
      '.bBB............',
    ],
  },
  'pressed-flower': {
    palette: { W: '#ffffff', w: '#fff4e4', v: '#ecdcc0', V: '#cdb894', L: '#a89878', l: '#dccbae', q: '#ffc2d1', p: '#ff8fab', P: '#d9668a', y: '#ffd166', Y: '#e0a83a', g: '#57cc99', G: '#2d9a6e' },
    pixels: [
      'Wwwwwwwwww...',
      'wLLLLLLwwwV..',
      'wwwwwwwwwwvV.',
      'wllllwwlllwvV',
      'wwwwwqqpwwwwV',
      'wwwwwqppwwwwV',
      'wwwqqppppPwwV',
      'wwwqppypPPwwV',
      'wwwwppYPPwwwV',
      'wwwwppgPPwwwV',
      'wwwwpPgPPwwwV',
      'wwwwGggwwwwwV',
      'wwwwwwggGwwwV',
      'wwwwwwgwwwwwV',
      'wllwwwgwlllwV',
      'vVVVVVVVVVVVV',
    ],
  },
  'stranded-jelly': {
    palette: { W: '#ffffff', w: '#fff4e4', h: '#ecdcf5', p: '#cdb4db', q: '#b598cc', f: '#f2c6e6', P: '#9d4edd', Q: '#7a3fc0' },
    pixels: [
      '.....hhhpp.....',
      '...hhWhpppq....',
      '..hWhppppppqq..',
      '.hhhpffpffpqq..',
      '.hhpfffpfffpqq.',
      'hhppfppppfppqqq',
      'hpppppppppppqqq',
      'pqpqpqpqpqpqqqq',
      '.q...PfPfQ...q.',
      '.q...PPPPQ...q.',
      '..q.PQ...PQ.q..',
      '..q.PQ...PQ.q..',
      '.q...PQ.PQ...q.',
      '.q...PQ.PQ...q.',
      '..q..P...Q..q..',
      '..q.........q..',
    ],
  },
  'pearl-oyster': {
    palette: { b: '#c0c8d6', a: '#8d99ae', A: '#6b7590', D: '#4a5068', n: '#aebbd8', m: '#8a95bd', N: '#d4bfe0', W: '#ffffff', e: '#f6f3ff', E: '#d3cbe8', F: '#a69ec8' },
    pixels: [
      '.....bbbbbaa.....',
      '...bbnnnnnnnaa...',
      '..bnNnnnnnnnnma..',
      '..bnNnnnnnnnnmA..',
      '..annnmeeemnmmA..',
      '...mmmeWWeEmmA...',
      '.DDDDDeWeeEDDDDD.',
      'bnnmmmeeeEFmmnmAD',
      'abnNnnmEEFmmnnmAD',
      '.abbbbbbbbbbbbAD.',
      '.aAaaAaaAaaAaaAD.',
      '..aAaaAaaAaaAAD..',
      '....AAADDDDDD....',
    ],
  },
};
