// Portraits for the toy-box finds (see index.js).

module.exports = {
  'metal-jack': {
    palette: { H: '#ffffff', a: '#e4e8ee', s: '#c0c0c0', m: '#8d94a0', d: '#5e6573', D: '#434958' },
    pixels: [
      '.Ha..........Ha.',
      'Hasm........Hasm',
      'asmd........asmd',
      '.mdas......ssmd.',
      '....as....sm....',
      '.....as..sm.....',
      '......Haas......',
      '......Hasm......',
      '......asmd......',
      '......smdd......',
      '.....sm..md.....',
      '....sm....dd....',
      '.Hasm......ddHa.',
      'Hasm........Hasm',
      'asmd........asmd',
      '.md..........md.',
    ],
  },
  'toy-brick': {
    palette: { H: '#ffc4c4', p: '#ff8f8f', a: '#ff6b6b', r: '#e63946', m: '#b8213a', d: '#86172f' },
    pixels: [
      '..HHp.HHp.HHp.HHp.',
      '..arm.arm.arm.arm.',
      '..armparmparmparmp',
      '.Hppppppppppppppm.',
      'arrrrrrrrrrrrrrrmm',
      'arrrrrrrrrrrrrrrmd',
      'arrrrrrrrrrrrrrrmd',
      'arrrrrrrrrrrrrrrmd',
      'arrrrrrrrrrrrrrrmd',
      'arrrrrrrrrrrrrrrd.',
      'mmmmmmmmmmmmmmmm..',
    ],
  },
  'lucky-die': {
    palette: { W: '#ffffff', w: '#fff4e4', c: '#ecd9c0', C: '#cdb497', D: '#a68e74', k: '#2b2d42', K: '#4a4d6a' },
    pixels: [
      '....WWWWWWWWwwww.',
      '..WWWWWWWwwwwwwwC',
      '.WWWWWWwwwwwwwwCC',
      '.WWWWWWWWWWWWwcCC',
      'WwwwwwwwwwwwwcCCD',
      'WwwkkwwwwkkwwcCCD',
      'WwwkKwwwwkKwwcCCD',
      'WwwwwwwwwwwwwcCCD',
      'WwwwwwwwwwwwwcCCD',
      'WwwkkwwwwkkwwcCCD',
      'WwwkKwwwwkKwwcCCD',
      'WwwwwwwwwwwwwcCCD',
      'WwwwwwwwwwwwwcCCD',
      'WwwkkwwwwkkwwcCCD',
      'WwwkKwwwwkKwwcCD.',
      'WwwwwwwwwwwwwcD..',
      '.cccccccccccc....',
    ],
  },
  marble: {
    palette: { L: '#c2d4ff', l: '#7b97ff', b: '#4361ee', B: '#3047c4', D: '#22308f', P: '#ff8cc6', p: '#f72585', q: '#b5176a', W: '#ffffff' },
    pixels: [
      '.....lllb.....',
      '...llllbbbb...',
      '..lWWlbbbPbb..',
      '.lWWlbbbPpbbb.',
      '.lllbbbbPpbbB.',
      'lllbbbbPpqbBBB',
      'llbbbbPpqbBBBB',
      'lbbbbbPpqBBBBB',
      'bbbbbPpqBBBBlD',
      '.bbbbpqBBBBLD.',
      '.bbbpqBBBBLDD.',
      '..bbqBBBBlDD..',
      '...bBBBBBDD...',
      '.....BBBD.....',
    ],
  },
  'yo-yo': {
    palette: { L: '#9cc7ff', l: '#6aa6ff', b: '#3a86ff', B: '#2563d1', D: '#1a449a', c: '#cdeafe', C: '#8fbfe6', W: '#ffffff', s: '#ffffff', S: '#c9d3e0' },
    pixels: [
      '.ss.............',
      's..S............',
      's..S............',
      '.SS.s...........',
      '.....ss.........',
      '.......sS.......',
      '........LLLl....',
      '......LLLLllll..',
      '.....LLLBBBBlbb.',
      '....LLLBllllBbbb',
      '....LLBllWcbbLbb',
      '....LLBlWccCbLbB',
      '....LlBlccCCbLBD',
      '....llBlbCCbbLBD',
      '....lllBbbbbLBBD',
      '.....lbbLLLLBBD.',
      '......bbbBBBDD..',
      '........BBDD....',
    ],
  },
  'toy-car': {
    palette: { H: '#ffc2b5', a: '#ff8a7a', r: '#ff5a4a', m: '#d63a35', d: '#9e2430', W: '#ffffff', c: '#cdeafe', C: '#8fbfe6', k: '#2b2d42', K: '#4a4d6a', S: '#eeeeee', s: '#c0c0c0', t: '#8d94a0', y: '#ffd23f' },
    pixels: [
      '.....Haaarm.......',
      '....HWcrWccm......',
      '...accCrcccCm.....',
      '...arrrrrrrrm.....',
      '.Harrrrrrmmrraaaa.',
      'arrrrrrrrrrrrrrrry',
      'arrrrrrrrrrrrrrrrm',
      'SmmKkkmmmmmmmKkkmS',
      'ddKSSskdddddKSSskd',
      '..kSstk.....kSstk.',
      '..ksttk.....ksttk.',
      '...kkk.......kkk..',
    ],
  },
  'wind-up-crab': {
    palette: { H: '#ffd0b8', a: '#ffa585', r: '#ff7a5c', m: '#d9553e', d: '#a3373a', k: '#3d405b', K: '#5e6385', Y: '#fff1a8', y: '#ffd23f', o: '#d9a21f', O: '#9e6f17', w: '#ffffff' },
    pixels: [
      '......YY..yo......',
      '.....YYyyyyoo.....',
      '......yyoooO......',
      '........yo........',
      'a.r.....yO.....r.m',
      'a.r...Hakkrr...r.m',
      'Har..aHHaaarr..rrm',
      'arm.awwaarrwwm.rmd',
      '.m.aawkrrrrwkmm.d.',
      '.maarrrdrdrrrmmdd.',
      '..arrrrrdrdrmmmd..',
      '..YyyyyyyyyyoooO..',
      '...mmammammaddd...',
      '....dddddddddd....',
      '....k.k....k.k....',
      '...k..k....k..k...',
      '..k..k......k..k..',
    ],
  },
};
