// Which manager a project uses, which checker asks about it, and how it is run
// (src/main/depwatch/tools.js): fixed arguments, a trimmed environment, and
// nothing the project ships ever gets to run.
const { test } = require('node:test');
const assert = require('node:assert/strict');
const path = require('path');
const tools = require('../src/main/depwatch/tools');
const { findNpm } = require('../src/main/depwatch');

const win = process.platform === 'win32';

// ------------------------------------------------------------------ detecting

const detect = (files, yarnLock = '') => tools.detect({ has: f => files.includes(f), peek: f => (f === 'yarn.lock' ? yarnLock : '') }).map(d => d.manager);

test('detect: a JavaScript manager by its lockfile, Yarn 1 or 2+ by what the lockfile says', () => {
  assert.deepEqual(detect(['package.json', 'package-lock.json']), ['npm']);
  assert.deepEqual(detect(['package.json', 'pnpm-lock.yaml']), ['pnpm']);
  assert.deepEqual(detect(['package.json', 'yarn.lock'], '# THIS IS AN AUTOGENERATED FILE.\n# yarn lockfile v1\n'), ['yarn']);
  assert.deepEqual(detect(['package.json', 'yarn.lock'], '# This file is generated by running "yarn install"\n\n__metadata:\n  version: 8\n'), ['yarn-berry']);
  assert.deepEqual(detect(['package.json', 'package-lock.json', 'yarn.lock']), ['npm'], 'one JavaScript manager per folder');
  assert.deepEqual(detect(['package.json']), [], 'no lockfile, nothing to read');
  assert.deepEqual(detect(['pnpm-lock.yaml']), [], 'no package.json');
});

test('detect: Rust, Go and Python, alongside a JavaScript one', () => {
  assert.deepEqual(detect(['Cargo.lock', 'Cargo.toml', 'package.json', 'pnpm-lock.yaml']), ['pnpm', 'cargo']);
  assert.deepEqual(detect(['go.mod', 'go.sum']), ['go']);
  assert.deepEqual(detect(['Cargo.toml']), [], 'a Cargo.toml alone: cargo-audit would have to run cargo to make a lockfile');
  const py = files => tools.detect({ has: f => files.includes(f), peek: () => '' });
  assert.deepEqual(py(['requirements.txt', 'uv.lock']), [{ manager: 'python', lockfile: 'uv.lock' }]);
  assert.deepEqual(py(['requirements.txt']), [{ manager: 'python', lockfile: 'requirements.txt' }]);
  assert.deepEqual(py(['pyproject.toml']), [], 'only a lockfile or pins can be read without resolving');
});

test('packageManagerOf: plain versions only', () => {
  assert.deepEqual(tools.packageManagerOf('{"packageManager":"yarn@4.9.2+sha512.abc"}'), { name: 'yarn', version: '4.9.2' });
  assert.deepEqual(tools.packageManagerOf('{"packageManager":"pnpm@9.15.0"}'), { name: 'pnpm', version: '9.15.0' });
  assert.equal(tools.packageManagerOf('{"packageManager":"yarn@https://evil.example/yarn.tgz"}'), null);
  assert.equal(tools.packageManagerOf('{"packageManager":"yarn@4.9.2 --version"}'), null);
  assert.equal(tools.packageManagerOf('nope'), null);
});

// ------------------------------------------------------------------ finding

test('findTools: absolute PATH folders only, JavaScript tools through node, never a .cmd', () => {
  if (!win) return; // Windows paths
  const files = new Set([
    'evil\\pnpm.exe', 'C:\\nodejs\\node.exe', 'C:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
    'C:\\nodejs\\node_modules\\corepack\\dist\\corepack.js',
    'C:\\Users\\me\\AppData\\Roaming\\npm\\pnpm.cmd', 'C:\\Users\\me\\AppData\\Roaming\\npm\\node_modules\\pnpm\\bin\\pnpm.cjs',
    'C:\\Users\\me\\.cargo\\bin\\cargo-audit.exe', 'C:\\Users\\me\\go\\bin\\govulncheck.exe', 'C:\\Go\\bin\\go.exe',
    'C:\\Users\\me\\.local\\bin\\pip-audit.exe',
  ]);
  const env = { PATH: 'evil;.;C:\\nodejs;C:\\Users\\me\\AppData\\Roaming\\npm;C:\\Go\\bin', USERPROFILE: 'C:\\Users\\me' };
  const t = tools.findTools(env, { exists: f => files.has(f), platform: 'win32', findNpm });
  assert.deepEqual(t.pnpm, { file: 'C:\\nodejs\\node.exe', pre: ['C:\\Users\\me\\AppData\\Roaming\\npm\\node_modules\\pnpm\\bin\\pnpm.cjs'] });
  assert.deepEqual(t.corepack, { file: 'C:\\nodejs\\node.exe', pre: ['C:\\nodejs\\node_modules\\corepack\\dist\\corepack.js'] });
  assert.equal(t.yarn, null);
  assert.equal(t.cargoAudit.file, 'C:\\Users\\me\\.cargo\\bin\\cargo-audit.exe');
  assert.equal(t.govulncheck.file, 'C:\\Users\\me\\go\\bin\\govulncheck.exe');
  assert.equal(t.go.file, 'C:\\Go\\bin\\go.exe');
  assert.equal(t.pipAudit.file, 'C:\\Users\\me\\.local\\bin\\pip-audit.exe');
  assert.equal(t.npm.file, 'C:\\nodejs\\node.exe');
  // Nothing on PATH but a relative folder: nothing found, nothing thrown.
  const none = tools.findTools({ PATH: 'evil;.' }, { exists: f => files.has(f), platform: 'win32', findNpm });
  assert.ok(Object.values(none).every(v => v === null));
});

// ------------------------------------------------------------------ plans

const T = {
  npm: { file: '/n/node', pre: ['/n/npm-cli.js'], git: '/usr/bin/git' },
  pnpm: { file: '/n/node', pre: ['/g/pnpm/bin/pnpm.cjs'] },
  yarn: null,
  corepack: { file: '/n/node', pre: ['/n/corepack/dist/corepack.js'] },
  pipAudit: { file: '/u/.local/bin/pip-audit', pre: [] },
  cargoAudit: { file: '/u/.cargo/bin/cargo-audit', pre: [] },
  go: { file: '/go/bin/go', pre: [] },
  govulncheck: null,
};
const dir = path.resolve('/code/app');
const ENV = { PATH: '/usr/bin', HOME: path.resolve('/home/me'), NPM_TOKEN: 'npm_secret', GITHUB_TOKEN: 'ghp_x', ANTHROPIC_API_KEY: 'sk-ant', COREPACK_NPM_REGISTRY: 'https://evil.example' };
const plan = (manager, t = T, more = {}) => tools.plan({ key: dir, manager }, t, { env: ENV, ...more });
const argsOf = p => p.steps.map(s => s.args.join(' '));
const SECRETS = ['NPM_TOKEN', 'GITHUB_TOKEN', 'ANTHROPIC_API_KEY', 'COREPACK_NPM_REGISTRY'];

test('plans use fixed arguments and keep every secret out of every environment', () => {
  const plans = ['npm', 'pnpm', 'yarn', 'yarn-berry', 'cargo', 'go'].map(m => plan(m)).concat(plan('python', T, { requirements: path.resolve('/tmp/pins.txt') }));
  for (const p of plans) {
    assert.ok(p.steps?.length, JSON.stringify(p));
    for (const s of p.steps) {
      for (const k of SECRETS) assert.equal(s.env[k], undefined, `${k} in ${s.args.join(' ')}`);
      assert.equal(s.env.NoDefaultCurrentDirectoryInExePath, '1');
      assert.ok(path.isAbsolute(s.file));
      assert.ok(s.timeout > 0);
    }
  }
});

test('npm: outdated and audit, no scripts, git pinned', () => {
  const p = plan('npm');
  assert.deepEqual(argsOf(p), ['/n/npm-cli.js outdated --json', '/n/npm-cli.js audit --json']);
  assert.equal(p.steps[0].env.npm_config_ignore_scripts, 'true');
  assert.equal(p.steps[0].env.npm_config_git, '/usr/bin/git');
  assert.equal(p.steps[0].cwd, dir);
});

test('pnpm: no pnpmfile and no switching pnpm, on the command line and in the environment', () => {
  const p = plan('pnpm');
  assert.deepEqual(argsOf(p), [
    '/g/pnpm/bin/pnpm.cjs outdated --format json --config.ignore-pnpmfile=true --config.pm-on-fail=ignore',
    '/g/pnpm/bin/pnpm.cjs audit --json --config.ignore-pnpmfile=true --config.pm-on-fail=ignore',
  ]);
  const e = p.steps[0].env;
  assert.ok(e.COREPACK_ROOT, 'pnpm 10 skips switching versions under Corepack');
  assert.equal(e.pnpm_config_pm_on_fail, 'ignore');
  assert.equal(e.npm_config_ignore_pnpmfile, 'true');
  assert.equal(e.pnpm_config_ignore_pnpmfile, 'true');
  assert.equal(e.COREPACK_ENV_FILE, '0');
  assert.ok(!argsOf(p).some(a => /--fix|--ignore /.test(a)), 'nothing that writes to the project');
});

test('pnpm through Corepack only for the exact pnpm the project names; otherwise it needs pnpm', () => {
  const noPnpm = { ...T, pnpm: null };
  assert.deepEqual(argsOf(plan('pnpm', noPnpm, { pkg: '{"packageManager":"pnpm@10.33.2"}' }))[0].split(' ').slice(0, 2), ['/n/corepack/dist/corepack.js', 'pnpm@10.33.2']);
  assert.match(plan('pnpm', noPnpm).needs, /pnpm/);
});

test('yarn 1: through Corepack asked for a 1.x, never the project\'s yarnPath', () => {
  const p = plan('yarn', T, { pkg: '{"packageManager":"yarn@1.22.22"}' });
  assert.deepEqual(argsOf(p), [
    '/n/corepack/dist/corepack.js yarn@1.22.22 outdated --json --non-interactive',
    '/n/corepack/dist/corepack.js yarn@1.22.22 audit --json --non-interactive',
  ]);
  // A project that says Yarn 4 but has a Yarn 1 lockfile still gets Yarn 1: in Yarn 4, `yarn audit` runs a script.
  assert.match(argsOf(plan('yarn', T, { pkg: '{"packageManager":"yarn@4.9.2"}' }))[0], /yarn@1 outdated/);
  assert.equal(p.steps[0].env.YARN_IGNORE_PATH, '1');
  const global = plan('yarn', { ...T, yarn: { file: '/n/node', pre: ['/g/yarn/bin/yarn.js'] } });
  assert.match(argsOf(global)[0], /^\/g\/yarn\/bin\/yarn\.js outdated/);
  assert.match(plan('yarn', { ...T, corepack: null }).needs, /Yarn 1/);
});

test('yarn 2+: npm audit through Corepack asked for a 2+ release, with no .yarnrc.yml and no yarnPath', () => {
  const p = plan('yarn-berry', T, { pkg: '{"packageManager":"yarn@4.9.2+sha224.abc"}' });
  assert.deepEqual(argsOf(p), ['/n/corepack/dist/corepack.js yarn@4.9.2 npm audit --all --recursive --json']);
  const e = p.steps[0].env;
  assert.equal(e.YARN_IGNORE_PATH, '1');
  assert.equal(e.YARN_RC_FILENAME, tools.NO_YARNRC);
  assert.equal(e.COREPACK_ENV_FILE, '0');
  // In Yarn 1, `yarn npm` would run the project's "npm" script: a 1.x packageManager isn't trusted here.
  assert.match(argsOf(plan('yarn-berry', T, { pkg: '{"packageManager":"yarn@1.22.22"}' }))[0], /yarn@stable npm audit/);
  assert.match(plan('yarn-berry', { ...T, corepack: null }).needs, /Corepack/);
});

test('python: pip-audit reads only the pins file Shellby wrote, installs nothing', () => {
  const pins = path.resolve('/tmp/shellby-pins-abc.txt');
  const p = plan('python', T, { requirements: pins });
  assert.deepEqual(p.steps[0].args, ['-r', pins, '--no-deps', '--disable-pip', '-f', 'json', '--progress-spinner', 'off']);
  assert.equal(p.steps[0].cwd, path.dirname(pins), 'not the project: nothing of its is read');
  assert.match(plan('python', { ...T, pipAudit: null }, { requirements: pins }).needs, /pip-audit/);
});

test('cargo: the cargo-audit binary itself, with the lockfile, database and its URL spelled out', () => {
  const p = plan('cargo');
  const a = p.steps[0].args;
  assert.equal(p.steps[0].file, '/u/.cargo/bin/cargo-audit');
  assert.deepEqual(a.slice(0, 2), ['audit', '--json']);
  assert.equal(a[a.indexOf('--file') + 1], path.join(dir, 'Cargo.lock'));
  assert.equal(a[a.indexOf('--db') + 1], path.join(ENV.HOME, '.cargo', 'advisory-db'));
  assert.equal(a[a.indexOf('--url') + 1], 'https://github.com/RustSec/advisory-db.git');
  assert.match(plan('cargo', { ...T, cargoAudit: null }).needs, /cargo-audit/);
});

test('go: updates from go list, no toolchain downloads, go.mod left alone; no govulncheck says so', () => {
  const p = plan('go');
  assert.deepEqual(argsOf(p), ['list -m -u -json all']);
  assert.match(p.missing, /govulncheck/);
  const e = p.steps[0].env;
  assert.equal(e.GOTOOLCHAIN, 'local');
  assert.equal(e.GOFLAGS, '-mod=readonly');
  const both = plan('go', { ...T, govulncheck: { file: '/u/go/bin/govulncheck', pre: [] } });
  assert.deepEqual(argsOf(both), ['list -m -u -json all', '-scan module -format json']);
  assert.equal(both.missing, null);
  assert.match(plan('go', { ...T, go: null }).needs, /Go/);
});

test('pnpm with configDependencies is not checked; Corepack never fetches a pnpm or Yarn too old for the guards', () => {
  assert.match(plan('pnpm', T, { workspace: 'packages:\n  - "."\nconfigDependencies:\n  evil: "1.0.0+sha512-x"\n' }).refused, /configDependencies/);
  assert.ok(plan('pnpm', T, { workspace: 'packages:\n  - "."\n' }).steps);
  const noPnpm = { ...T, pnpm: null };
  assert.match(plan('pnpm', noPnpm, { pkg: '{"packageManager":"pnpm@7.33.0"}' }).needs, /pnpm/);
  assert.match(argsOf(plan('yarn-berry', T, { pkg: '{"packageManager":"yarn@2.4.3"}' }))[0], /yarn@stable /);
  assert.match(argsOf(plan('yarn', T, { pkg: '{"packageManager":"yarn@1.3.2"}' }))[0], /yarn@1 /);
  assert.equal(plan('go').steps[0].env.GOVCS, 'private:git,public:off');
});

test('npmEnv passes nothing a project .npmrc could quote, and pins git', () => {
  const env = tools.npmEnv({ file: path.resolve('/nodejs/node'), pre: [], git: null }, {
    PATH: '/usr/bin', TEMP: '/tmp', HTTPS_PROXY: 'http://proxy:8080',
    NPM_TOKEN: 'npm_secret', GITHUB_TOKEN: 'ghp_secret', ANTHROPIC_API_KEY: 'sk-ant', AWS_SECRET_ACCESS_KEY: 'x',
  });
  assert.equal(env.PATH, '/usr/bin');
  assert.equal(env.HTTPS_PROXY, 'http://proxy:8080');
  for (const k of ['NPM_TOKEN', 'GITHUB_TOKEN', 'ANTHROPIC_API_KEY', 'AWS_SECRET_ACCESS_KEY']) assert.equal(env[k], undefined, k);
  assert.equal(env.npm_config_ignore_scripts, 'true');
  assert.ok(path.isAbsolute(env.npm_config_git));
});
