// The Bugdex: every bug Claude fixes with him around gets caught and goes in
// the book. Each kind is a little sea creature with a dex number, a habitat,
// a type and a line about itself. Catch one and it's yours; the ones you
// haven't met yet sit there as silhouettes with a hint about what to look for.
// Twelve habitats to fill, and one that isn't in any of them.
//
// Pure data: no I/O, no clock. Dex numbers are given out once and never
// reused (test/bugdex-species.test.js pins them). See docs/plans/bugdex.md §2.

const { PORTRAITS } = require('./portraits');
const { inked } = require('./art');

const RARITY = Object.freeze({
  common: Object.freeze({ label: 'Common' }),
  uncommon: Object.freeze({ label: 'Uncommon' }),
  rare: Object.freeze({ label: 'Rare' }),
  legendary: Object.freeze({ label: 'Legendary' }),
  special: Object.freeze({ label: 'Mystery' }),
});

// The "element" of a bug, and the colour of its chip.
const TYPES = Object.freeze({
  runtime: Object.freeze({ label: 'Runtime', color: '#f9c74f' }),
  io: Object.freeze({ label: 'Files', color: '#a1887f' }),
  net: Object.freeze({ label: 'Network', color: '#4ea8de' }),
  vcs: Object.freeze({ label: 'Git', color: '#f3722c' }),
  ci: Object.freeze({ label: 'CI', color: '#e63946' }),
  build: Object.freeze({ label: 'Build', color: '#8d99ae' }),
  types: Object.freeze({ label: 'Types', color: '#7b6cf6' }),
  py: Object.freeze({ label: 'Python', color: '#43aa8b' }),
  sys: Object.freeze({ label: 'Systems', color: '#b5651d' }),
  test: Object.freeze({ label: 'Tests', color: '#90be6d' }),
  sec: Object.freeze({ label: 'Security', color: '#277da1' }),
  ghost: Object.freeze({ label: 'Ghost', color: '#cdb4db' }),
});

// Every phase is built; species with a later phase than this stay out of the book.
const LIVE_PHASE = 3;

const K = '#2b2d42'; // outlines and eyes

// The big shaded drawing for the book and the battle (portraits/), inked.
function portraitOf(id) {
  const p = PORTRAITS[id];
  if (!p) return null;
  const a = inked(p);
  return Object.freeze({ pixels: Object.freeze(a.pixels), palette: Object.freeze(a.palette) });
}

// Each species: pixel art (one character per pixel, '.' is empty, at most 8×8),
// its line for the book, and a hint for when you haven't caught it yet that
// says what kind of error it is without giving the creature away.
// `evolves` is [stage II, stage III] for the starters; `remedies` lists the
// fixes-by-command that still count as a catch (docs/plans/bugdex.md §4.3).
const SPECIES = Object.freeze([
  // ---- The Shallows: JS and runtime errors
  { no: 1, id: 'shapeshifter-shrimp', name: 'Shapeshifter Shrimp', habitat: 'shallows', type: 'runtime', rarity: 'common', phase: 1,
    blurb: 'Was a string a second ago. Swears it.', hint: 'A TypeError, fixed.',
    evolves: ['Morphing Prawn', 'Polymorph Lobster'],
    palette: { a: '#9d4edd', b: '#2a9d8f', k: '#fff4e4' },
    pixels: ['aaaabb.', 'akaabkb', 'aaaabbb', 'aaaabbb', 'aaaabb.', 'a.a..b.'] },
  { no: 2, id: 'nullfish', name: 'Nullfish', habitat: 'shallows', type: 'runtime', rarity: 'common', phase: 1,
    blurb: 'There\'s nothing there. That\'s the problem.', hint: 'Something was null or undefined, fixed.',
    evolves: ['Voidfish', 'Abyssal Nullshark'],
    palette: { o: '#8ecae6', k: K },
    pixels: ['..oooo.o', '.o....oo', 'o.k....o', '.o....oo', '..oooo.o'] },
  { no: 3, id: 'nameless-nudibranch', name: 'Nameless Nudibranch', habitat: 'shallows', type: 'runtime', rarity: 'common', phase: 1,
    blurb: 'Nobody declared it. It came anyway.', hint: 'A ReferenceError: something not defined, fixed.',
    palette: { p: '#c77dff', P: '#9d4edd', w: '#fff4e4', k: K },
    pixels: ['.p...p..', '..p.p...', '.pppppp.', 'pkpwwwpp', 'PPPwwwPP', '.PPPPPP.'] },
  { no: 4, id: 'syntax-slug', name: 'Syntax Slug', habitat: 'shallows', type: 'runtime', rarity: 'common', phase: 1,
    blurb: 'Left a bracket open in 2019.', hint: 'A SyntaxError, fixed.',
    evolves: ['Grammar Sea Hare', 'Linguist Nudibranch'],
    palette: { y: '#ffd23f', o: '#e9a23b', k: K },
    pixels: ['.k.k..', '.yyyy.', '.yo...', 'yy....', '.yo...', '.yyyy.', '..oooo'] },
  { no: 5, id: 'off-by-one-octopus', name: 'Off-by-One Octopus', habitat: 'shallows', type: 'runtime', rarity: 'common', phase: 2,
    blurb: 'Counts its arms from zero. Gets seven.', hint: 'An index out of range (RangeError), fixed.',
    palette: { r: '#ff7a5c', R: '#c2412d', k: K },
    pixels: ['..rrrr..', '.rrrrrr.', '.rkrrkr.', '.rrrrrr.', 'rRrRrRr.', 'R.R.R.R.', '.R.R.R..'] },
  { no: 6, id: 'ouroboros-eel', name: 'Ouroboros Eel', habitat: 'shallows', type: 'runtime', rarity: 'uncommon', phase: 2,
    blurb: 'Calls itself. Calls itself. Calls itself.', hint: 'Maximum call stack size exceeded, fixed.',
    palette: { g: '#57cc99', G: '#2a9d8f', k: K },
    pixels: ['..gggg..', '.g....gg', 'g.....gk', 'g......G', 'g......G', '.g....G.', '..GGGG..'] },
  { no: 7, id: 'broken-promise-prawn', name: 'Broken Promise Prawn', habitat: 'shallows', type: 'runtime', rarity: 'uncommon', phase: 2,
    blurb: 'Said it would resolve. Didn\'t.', hint: 'An unhandled promise rejection, fixed.',
    palette: { p: '#ff9f80', P: '#e76f51', w: '#fff4e4', k: K },
    pixels: ['pp......', 'pwp.....', '.p..ppp.', '..ppppkp', '.PPpppp.', 'PP.P.P..'] },
  { no: 8, id: 'heap-leviathan', name: 'Heap Leviathan', habitat: 'shallows', type: 'runtime', rarity: 'rare', phase: 2,
    blurb: 'Ate every byte. Still hungry.', hint: 'Out of memory, fixed for real (not just a bigger heap).',
    palette: { b: '#3d5a80', B: '#293241', w: '#e0fbfc', k: K },
    pixels: ['bbbbbbbb', 'bbbbbbbb', 'bbbbkbbb', 'bbbbbbbb', 'wwwwwbbb', 'wBwBwwbb', 'wwwwwwwb', 'BBBBBBBB'] },

  // ---- The Burrows: the filesystem
  { no: 9, id: 'shell-less-hermit', name: 'Shell-less Hermit', habitat: 'burrows', type: 'io', rarity: 'common', phase: 1,
    blurb: 'Its file was right here a minute ago.', hint: 'A file that wasn\'t there (ENOENT), fixed.',
    evolves: ['Squatter Hermit', 'Homeowner Hermit'],
    palette: { k: K, r: '#ff6b4a', R: '#c2412d', p: '#ffc2b0', P: '#e89a86' },
    pixels: ['.k.k....', '.r.r....', 'rrrrr...', 'Rrrrrpp.', '.r.rppPp', '.....pp.'] },
  { no: 10, id: 'locked-limpet', name: 'Locked Limpet', habitat: 'burrows', type: 'io', rarity: 'uncommon', phase: 2,
    blurb: 'Clamped shut. Asks for permission it\'ll never get.', hint: 'Permission denied (EACCES / EPERM), fixed.',
    palette: { s: '#a1887f', S: '#6d4c41', y: '#ffd23f', k: K },
    pixels: ['...yyy..', '...y.y..', '..syyys.', '.sssykss', 'ssssssss', 'SSSSSSSS'] },
  { no: 11, id: 'clingy-barnacle', name: 'Clingy Barnacle', habitat: 'burrows', type: 'io', rarity: 'uncommon', phase: 2,
    blurb: 'This file is being used by another process. Its.', hint: 'A file busy or locked by another process (EBUSY), fixed.',
    remedies: ['kill'],
    palette: { w: '#fff4e4', f: '#c9c4d6', b: '#8d99ae', B: '#5c677d', k: K },
    pixels: ['wwwf....', 'wkkwf...', 'wwwwwbb.', 'wkkwbBBb', 'wwwwbkBb', '.bbbbbbb'] },
  { no: 12, id: 'mixed-up-mussel', name: 'Mixed-up Mussel', habitat: 'burrows', type: 'io', rarity: 'uncommon', phase: 2,
    blurb: 'Thought it was a folder. It was a file.', hint: 'A file where a folder should be (ENOTDIR / EISDIR), fixed.',
    palette: { m: '#3d405b', f: '#ffd166', w: '#fff4e4', k: K },
    pixels: ['..mmmm..', '.mffwwm.', 'mfffwwwm', 'mfffwkwm', '.mffwwm.', '..mmmm..'] },
  { no: 13, id: 'overstuffed-pufferfish', name: 'Overstuffed Pufferfish', habitat: 'burrows', type: 'io', rarity: 'rare', phase: 3,
    blurb: 'No space left. Not even for air.', hint: 'A full disk (ENOSPC), fixed.',
    remedies: ['cache'],
    palette: { y: '#ffd23f', o: '#e9a23b', k: K },
    pixels: ['o..o..o.', '.yyyyyy.', 'oyykyyyy', '.yyyyyyo', 'oyyyyyyy', '.yyyyyy.', 'o..o..o.'] },

  // ---- The Currents: network and HTTP
  { no: 14, id: 'closed-clam', name: 'Closed Clam', habitat: 'currents', type: 'net', rarity: 'uncommon', phase: 2,
    blurb: 'Knocked. Nobody home.', hint: 'Connection refused (ECONNREFUSED), fixed.',
    remedies: ['service'],
    palette: { c: '#e5989b', C: '#b5838d', k: K },
    pixels: ['..cccc..', '.cccccc.', 'cccccccc', 'kkkkkkkk', 'CCCCCCCC', '.CCCCCC.'] },
  { no: 15, id: 'port-squatter', name: 'Port Squatter', habitat: 'currents', type: 'net', rarity: 'uncommon', phase: 1,
    blurb: 'Got there first. Won\'t move.', hint: 'A port already in use (EADDRINUSE), fixed.',
    evolves: ['Port Warden', 'Harbour Master'], remedies: ['kill'],
    palette: { g: '#b08d57', w: '#a8dadc', r: '#ff6b4a', k: K },
    pixels: ['..gggg..', '.gwwwwg.', 'gwkwwkwg', 'gwrrrrwg', 'grrrrrrg', '.grwwrg.', '..gggg..'] },
  { no: 16, id: 'slowpoke-snail', name: 'Dawdling Snail', habitat: 'currents', type: 'net', rarity: 'uncommon', phase: 2,
    blurb: 'Still on its way.', hint: 'A timeout, fixed (not just by waiting longer).',
    palette: { a: '#9e9e9e', s: '#e0e0e0', b: '#c9b38a', k: K },
    pixels: ['....a...', '..aaaaa.', 'k.asksa.', 'b.askka.', 'b.aaaaa.', 'bbbbbbbb'] },
  { no: 17, id: 'snapped-line', name: 'Snapped Line', habitat: 'currents', type: 'net', rarity: 'uncommon', phase: 2,
    blurb: 'Hung up on you. Rude.', hint: 'A connection reset or socket hang up, fixed.',
    palette: { l: '#dfe5ec', r: '#e63946', w: '#fff4e4', h: '#8d99ae' },
    pixels: ['l.....', '.l....', '......', '...l..', '..rrr.', '..www.', '...l.h', '...hh.'] },
  { no: 18, id: 'nameless-buoy', name: 'Nameless Buoy', habitat: 'currents', type: 'net', rarity: 'uncommon', phase: 3,
    blurb: 'Can\'t find where it\'s going. Or where it is.', hint: 'A hostname that wouldn\'t resolve (ENOTFOUND), fixed.',
    palette: { k: K, y: '#ffd23f', r: '#e63946', w: '#fff4e4', b: '#4ea8de' },
    pixels: ['...kyyy', '...kyky', '...kyyy', '..rrr..', '.rwwwr.', '.rrrrr.', 'bbbbbbb'] },
  { no: 19, id: 'border-crab', name: 'Border Crab', habitat: 'currents', type: 'net', rarity: 'uncommon', phase: 3,
    blurb: 'Your origin isn\'t on the list.', hint: 'A CORS error, fixed.',
    palette: { c: '#3d405b', r: '#ff6b4a', s: '#8a6a4a', k: K },
    pixels: ['..cccc..', '.cccccc.', '..rkrk.s', 'r.rrrr.s', 'rrrrrrkk', '.r.r.r..'] },
  { no: 20, id: 'lost-parcel-crab', name: 'Lost Parcel Crab', habitat: 'currents', type: 'net', rarity: 'common', phase: 3,
    blurb: 'Delivered to an address that doesn\'t exist.', hint: 'An HTTP 404, fixed.',
    palette: { b: '#c97b4a', B: '#8a5a3a', r: '#ff6b4a', k: K },
    pixels: ['.bbbbbb.', '.bBBBBb.', '.bbbbbb.', 'r.rrrr.r', 'rrkrrkrr', '.rrrrrr.', 'r.r..r.r'] },
  { no: 21, id: 'meltdown-medusa', name: 'Meltdown Medusa', habitat: 'currents', type: 'net', rarity: 'uncommon', phase: 3,
    blurb: 'Something went wrong. On their end. Probably.', hint: 'An HTTP 500, fixed.',
    palette: { s: '#dfe5ec', r: '#e63946', R: '#9d0208', k: K },
    pixels: ['s..s..s.', '.s..s..s', '..rrrr..', '.rrrrrr.', 'rrkrrkrr', 'RRRRRRRR', 'R.R..R.R', '.R.RR.R.'] },

  // ---- Tangled Nets: git
  { no: 22, id: 'two-headed-crab', name: 'Two-Headed Crab', habitat: 'nets', type: 'vcs', rarity: 'uncommon', phase: 1,
    blurb: 'Both heads are right. That\'s the problem.', hint: 'A merge conflict, resolved.',
    evolves: ['Three-Way Crab', 'Octopus Merge'],
    palette: { k: K, b: '#4ea8de', o: '#ff9f1c', m: '#9d4edd' },
    pixels: ['k.k..k.k', 'bbb..ooo', 'bbbbmooo', '.bbmmoo.', '..bmmo..', '.b.mm.o.'] },
  { no: 23, id: 'bounced-bottle', name: 'Bounced Bottle', habitat: 'nets', type: 'vcs', rarity: 'uncommon', phase: 2,
    blurb: 'Sent it. The sea sent it back.', hint: 'A rejected git push, sorted out.',
    palette: { a: '#8a6a4a', c: '#a8dadc', d: '#fff4e4', b: '#4ea8de' },
    pixels: ['..cccc..', 'acddddcc', '..cccc..', 'b...b..b', '.bbb.bb.'] },
  { no: 24, id: 'gatekeeper-goby', name: 'Gatekeeper Goby', habitat: 'nets', type: 'vcs', rarity: 'uncommon', phase: 2,
    blurb: 'Checks every commit at the door.', hint: 'A failing pre-commit hook, passed properly.',
    palette: { a: '#8d6e63', g: '#e9c46a', G: '#b08d57', k: K },
    pixels: ['a.a.....', 'aaa.ggg.', 'a.agkggg', 'aaagggGg', 'a.a.GGG.'] },
  { no: 25, id: 'lockfile-lobster', name: 'Lockfile Lobster', habitat: 'nets', type: 'vcs', rarity: 'common', phase: 3,
    blurb: 'Another git process seems to be running. It\'s this one.', hint: 'A stuck git index.lock, cleared.',
    remedies: ['lock'],
    palette: { r: '#d62828', y: '#ffd23f', k: K },
    pixels: ['r.....r.', 'rr.kk.rr', '.rrrrrr.', '..rrrr..', '.yyyyyy.', '.yykkyy.', '.yyyyyy.'] },

  // ---- The Lighthouse: CI
  { no: 26, id: 'red-tide', name: 'Red Tide', habitat: 'lighthouse', type: 'ci', rarity: 'common', phase: 1,
    blurb: 'The whole bay went red. Then it didn\'t.', hint: 'A red CI build Shellby helped turn green.',
    palette: { y: '#ffd23f', w: '#fff4e4', r: '#e63946', R: '#ff8f8f' },
    pixels: ['...y....', '..www...', '..wrw...', '..www...', 'R.wrw.R.', 'rRwwwRrR', 'rrrrrrrr', 'rrrrrrrr'] },
  { no: 27, id: 'matrix-hydra', name: 'Matrix Hydra', habitat: 'lighthouse', type: 'ci', rarity: 'rare', phase: 3,
    blurb: 'Fine on two systems. Bit the third.', hint: 'A CI matrix red on just one OS, turned green.',
    palette: { g: '#57cc99', r: '#e63946', b: '#2a9d8f', k: K },
    pixels: ['gg.gg.rr', 'gk.gk.rk', '.g..g.r.', '.g..g.r.', '..bbbb..', '.bbbbbb.', 'bb.bb.bb'] },
  { no: 28, id: 'sunken-deploy', name: 'Sunken Deploy', habitat: 'lighthouse', type: 'ci', rarity: 'uncommon', phase: 3,
    blurb: 'Launched. Sank. Refloated.', hint: 'A failed deploy check, turned green.',
    palette: { w: '#fff4e4', s: '#8a6a4a', b: '#4ea8de' },
    pixels: ['.....w..', '....ww..', '...www..', '..s.w...', '.sss....', 'bsssbbbb', 'bbssbbbb', 'bbbbbbbb'] },
  { no: 29, id: 'stalled-galleon', name: 'Stalled Galleon', habitat: 'lighthouse', type: 'ci', rarity: 'uncommon', phase: 3,
    blurb: 'No wind. Six hours. Cancelled.', hint: 'A CI check that timed out, fixed.',
    palette: { S: '#5d4037', w: '#e9d8a6', s: '#8a6a4a', b: '#4ea8de' },
    pixels: ['..S..S..', '..w..w..', '.ww.ww..', '..w..w..', 'ssssssss', '.ssssss.', 'bbbbbbbb'] },
  { no: 30, id: 'the-kraken', name: 'The Kraken', habitat: 'lighthouse', type: 'ci', rarity: 'legendary', phase: 3,
    blurb: 'Every check, red. Every one, green again.', hint: 'Legendary: three or more red checks on a PR, all fixed in one push.',
    palette: { y: '#ffd23f', w: '#fff4e4', p: '#7b2cbf', P: '#c77dff' },
    pixels: ['...y....', '..www...', 'p.www.p.', 'pPwpwPp.', '.pwwwp..', 'p.wpw..p', 'pppppppp', '.P.P.P.P'] },

  // ---- The Reef Workshop: tooling, builds, installs, servers
  { no: 31, id: 'stray-module-minnow', name: 'Stray Module Minnow', habitat: 'workshop', type: 'build', rarity: 'common', phase: 1,
    blurb: 'Swam off from node_modules and never came back.', hint: 'A module that couldn\'t be found, fixed.',
    evolves: ['Module Mackerel', 'Monorepo Marlin'], remedies: ['install'],
    palette: { c: '#adb5bd', f: '#8ecae6', F: '#219ebc', k: K },
    pixels: ['cc..cc..', 'c.c.c...', '.cc.....', '...fff.F', '..fkfffF', '...fff.F'] },
  { no: 32, id: 'tangled-tree-crab', name: 'Tangled Tree Crab', habitat: 'workshop', type: 'build', rarity: 'uncommon', phase: 2,
    blurb: 'Its peer dependencies have peer dependencies.', hint: 'A dependency conflict (ERESOLVE and friends), fixed.',
    palette: { t: '#8a6a4a', r: '#ff6b4a', k: K },
    pixels: ['t.t..t.t', '.t.tt.t.', 't.t..t.t', '.trrrrt.', 'rrkrrkrr', '.rrrrrr.', 'r.r..r.r'] },
  { no: 33, id: 'collapsed-castle', name: 'Collapsed Castle', habitat: 'workshop', type: 'build', rarity: 'common', phase: 2,
    blurb: 'Built it. Watched it fall. Built it again.', hint: 'A failed build, fixed.',
    evolves: ['Rebuilt Keep', 'Citadel'],
    palette: { f: '#e63946', s: '#e9c46a', S: '#c9a227' },
    pixels: ['......f.', '......s.', '.s....s.', '.ss..sss', 'ssss.sss', 'SsssssSs', 'SSSSSSSS'] },
  { no: 34, id: 'lint-louse', name: 'Lint Louse', habitat: 'workshop', type: 'build', rarity: 'common', phase: 2,
    blurb: 'Small. Annoying. Everywhere.', hint: 'Lint errors, fixed (not silenced).',
    palette: { l: '#adb5bd', L: '#6c757d', r: '#e63946', k: K },
    pixels: ['..ll....', '.lkll...', 'lllll...', '.L.L....', 'r.r.r.r.', '.r.r.r.r'] },
  { no: 35, id: 'beached-whale', name: 'Beached Whale', habitat: 'workshop', type: 'build', rarity: 'uncommon', phase: 1,
    blurb: 'Ran aground on npm run dev.', hint: 'A dev server that crashed, back up and running.',
    evolves: ['Refloated Whale', 'Humpback of Uptime'],
    palette: { w: '#cdeafe', b: '#4ea8de', B: '#3a6ea5', s: '#e9c46a', k: K },
    pixels: ['..w.w...', '...w....', '.bbbbb.b', 'bkbbbbbb', 'bBBBBbb.', 'ssssssss', 'ssssssss'] },
  { no: 36, id: 'old-salt', name: 'Old Salt', habitat: 'workshop', type: 'build', rarity: 'uncommon', phase: 3,
    blurb: 'Only runs on the version it grew up with.', hint: 'An unsupported engine or version mismatch, fixed.',
    palette: { r: '#ff6b4a', w: '#f1faee', t: '#ffd23f', k: K },
    pixels: ['.k..k...', 'rrrrrr..', 'rwwwwr.t', '.wwww.tt', '..ww..tt', 'r.r.r.r.'] },

  // ---- The Kelp Maze: type checkers
  { no: 37, id: 'mismatched-mantis', name: 'Mismatched Mantis Shrimp', habitat: 'kelp', type: 'types', rarity: 'common', phase: 2,
    blurb: 'Punched a string into a number slot.', hint: 'A type mismatch the type checker caught, fixed.',
    palette: { o: '#ff9f1c', b: '#4ea8de', g: '#2a9d8f', k: K },
    pixels: ['oo....b.', 'ooo..bb.', '.okggk..', '..gggg..', '..gggg..', '...gg...', '..g..g..'] },
  { no: 38, id: 'missing-fin-pipefish', name: 'Missing-Fin Pipefish', habitat: 'kelp', type: 'types', rarity: 'common', phase: 2,
    blurb: 'Property \'fin\' does not exist on type \'Pipefish\'.', hint: 'A property that doesn\'t exist on a type, fixed.',
    palette: { d: '#adb5bd', p: '#e9c46a', k: K },
    pixels: ['...d.d..', '..d...d.', 'pkpppppp', '.ppppp.p'] },
  { no: 39, id: 'undeclared-urchin', name: 'Undeclared Urchin', habitat: 'kelp', type: 'types', rarity: 'uncommon', phase: 2,
    blurb: 'Could not find a declaration file. It is one.', hint: 'A missing declaration file, fixed.',
    palette: { u: '#7b2cbf', U: '#c77dff', d: '#adb5bd', k: K },
    pixels: ['u.u.u...', '.UUU....', 'uUkUu...', '.UUU.ddd', 'u.u.ud.d', '.....ddd'] },
  { no: 40, id: 'anything-anemone', name: 'Anything Anemone', habitat: 'kelp', type: 'types', rarity: 'common', phase: 2,
    blurb: 'Accepts anything. Trusts nothing.', hint: 'An implicit any, typed properly.',
    palette: { p: '#ff8fab', y: '#ffd23f', b: '#4ea8de', g: '#57cc99', A: '#f72585' },
    pixels: ['p.y..b.g', '.p.yb.g.', '..pybg..', '..AAAA..', '..AAAA..', '.AAAAAA.'] },
  { no: 41, id: 'optional-oarfish', name: 'Optional Oarfish', habitat: 'kelp', type: 'types', rarity: 'uncommon', phase: 2,
    blurb: 'Possibly undefined. Definitely long.', hint: 'An "object is possibly undefined" error, fixed.',
    palette: { r: '#e63946', o: '#c0c0c0', l: '#e8ecf1', k: K },
    pixels: ['rrrr.r..', 'okoool.l', 'oooo.l..'] },
  { no: 42, id: 'hinted-hermit', name: 'Hinted Hermit', habitat: 'kelp', type: 'types', rarity: 'uncommon', phase: 2,
    blurb: 'Its hints and its code disagree.', hint: 'A Python type-hint error (mypy, pyright), fixed.',
    palette: { n: '#ffe066', s: '#c97b4a', r: '#ff6b4a', k: K },
    pixels: ['nnnn....', 'nkkn....', 'nnnn.ss.', '.k.kssss', 'rrrrssss', 'r.r.rss.'] },
  { no: 43, id: 'type-tangle', name: 'Type Tangle', habitat: 'kelp', type: 'types', rarity: 'common', phase: 1,
    blurb: 'error TS-something. It all looks the same in the kelp.', hint: 'A TypeScript error, fixed (not suppressed).',
    evolves: ['Kelp Knot', 'Generic Grouper'],
    palette: { g: '#2a9d8f', G: '#57cc99' },
    pixels: ['.g..g...', 'g.gg.g..', '.G..G.g.', 'g.GG.G..', '.g..g.G.', '..gg.g..', '...g....'] },

  // ---- The Sea-Snake Pool: Python
  { no: 44, id: 'keyless-krill', name: 'Keyless Krill', habitat: 'pypool', type: 'py', rarity: 'common', phase: 2,
    blurb: 'Looked up a key that was never in the dict.', hint: 'A Python KeyError, fixed.',
    palette: { y: '#ffd23f', p: '#ff9f80', k: K },
    pixels: ['....yyy.', '...y...y', '....yyy.', '.ppppp..', 'pkppppp.', '.p.p.p..'] },
  { no: 45, id: 'wonky-whelk', name: 'Wonky Whelk', habitat: 'pypool', type: 'py', rarity: 'common', phase: 2,
    blurb: 'Four spaces. No, a tab. No, four spaces.', hint: 'An IndentationError, fixed.',
    palette: { w: '#f3e6cc', b: '#c9b38a' },
    pixels: ['....w...', '...wbw..', '..wbw...', '..wbbbw.', '.wbwbw..', 'wwwwwww.'] },
  { no: 46, id: 'circular-sea-snake', name: 'Circular Sea Snake', habitat: 'pypool', type: 'py', rarity: 'uncommon', phase: 2,
    blurb: 'Imports the module that imports it.', hint: 'A circular import, untangled.',
    palette: { y: '#ffd23f', k: K, r: '#e63946' },
    pixels: ['..ykyk..', '.k....y.', 'y......k', 'k......y', '.y...rk.', '..kyk...'] },
  { no: 47, id: 'attribute-anglerfish', name: 'Attribute Anglerfish', habitat: 'pypool', type: 'py', rarity: 'common', phase: 2,
    blurb: 'Has no attribute. Has a lot of teeth.', hint: 'A Python AttributeError, fixed.',
    palette: { l: '#8d99ae', a: '#3d405b', e: '#ffd23f', w: '#f1faee' },
    pixels: ['.lll....', '.l..aaa.', '..aaaaaa', 'aeaaaaaa', 'wawaaaaa', 'aaaaaaa.', '.aaaaa..'] },
  { no: 48, id: 'off-value-oyster', name: 'Off-Value Oyster', habitat: 'pypool', type: 'py', rarity: 'common', phase: 2,
    blurb: 'Right type. Wrong value.', hint: 'A Python ValueError, fixed.',
    palette: { o: '#a1887f', O: '#d7ccc8', w: '#f8f4ff' },
    pixels: ['.oooooo.', 'oOOOOOOo', '.oOwwOo.', '.oOwwOo.', 'oOOOOOOo', '.oooooo.'] },
  { no: 49, id: 'zero-dab', name: 'Divide-by-Zero Dab', habitat: 'pypool', type: 'py', rarity: 'uncommon', phase: 2,
    blurb: 'Shared the pie with nobody.', hint: 'A division by zero, fixed.',
    palette: { f: '#c9b38a', k: K },
    pixels: ['.ff..ff.', 'f..ff..f', 'fk.ff..f', 'f..ff..f', '.ff..ff.'] },

  // ---- The Deep Trench: Rust, Go, native
  { no: 50, id: 'borrowing-hermit', name: 'Borrowing Hermit', habitat: 'trench', type: 'sys', rarity: 'uncommon', phase: 2,
    blurb: 'Hermit crabs borrow shells. Not two at once.', hint: 'A Rust borrow-checker error, fixed.',
    palette: { s: '#c97b4a', S: '#e9a26a', r: '#ff6b4a', k: K },
    pixels: ['ss....SS', 'sss..SSS', 'ssrrrrSS', '.rkrrkr.', 'r.r..r.r'] },
  { no: 51, id: 'rusty-nautilus', name: 'Rusty Nautilus', habitat: 'trench', type: 'sys', rarity: 'common', phase: 2,
    blurb: 'Compiles eventually. Eventually.', hint: 'A Rust compile error, fixed.',
    palette: { n: '#f3e6cc', b: '#c97b4a', r: '#8a4b2a', k: K },
    pixels: ['..nnnn..', '.nbnbnn.', 'nbrnbnrn', 'nnnbrnnn', 'knnnnrn.', 'nnn.nn..'] },
  { no: 52, id: 'panicked-prawn', name: 'Panicked Prawn', habitat: 'trench', type: 'sys', rarity: 'uncommon', phase: 2,
    blurb: 'Called unwrap() on None. Is now unwell.', hint: 'A Rust panic, fixed.',
    palette: { p: '#ff9f80', P: '#e76f51', r: '#e63946', k: K },
    pixels: ['p..r..p', 'p..r..p', '.p...p.', '.p.r.p.', '.ppppp.', '.pkpkp.', '..PPP..', '.P.P.P.'] },
  { no: 53, id: 'nil-gopherfish', name: 'Nil Gopherfish', habitat: 'trench', type: 'sys', rarity: 'uncommon', phase: 2,
    blurb: 'Dereferenced the void. The void didn\'t like it.', hint: 'A Go nil pointer dereference, fixed.',
    palette: { g: '#00add8', w: '#fff4e4', d: '#adb5bd', k: K },
    pixels: ['.gggg...', 'gkggkg..', 'gggggggd', 'ggwwgg..', '.gggg..d', '..g.g...'] },
  { no: 54, id: 'knotted-eels', name: 'Knotted Eels', habitat: 'trench', type: 'sys', rarity: 'rare', phase: 2,
    blurb: 'All goroutines are asleep. These two especially.', hint: 'A deadlock, fixed.',
    palette: { a: '#57cc99', b: '#ff9f1c', k: K },
    pixels: ['ka....bk', '.aa..bb.', '...ab...', '...ba...', '.bb..aa.', 'b......a'] },
  { no: 55, id: 'segfault-squid', name: 'Segfault Squid', habitat: 'trench', type: 'sys', rarity: 'rare', phase: 2,
    blurb: 'Touched memory it doesn\'t own. Inked everywhere.', hint: 'A segmentation fault, fixed.',
    palette: { s: '#c77dff', S: '#9d4edd', i: K },
    pixels: ['...ss...', '..ssss..', '.ssssss.', '.sissis.', '..SSSS..', '.S.SS.S.', 'S.S..S.S', 'ii.iii.i'] },

  // ---- The Proving Pools: tests
  { no: 56, id: 'red-snapper', name: 'Red Snapper', habitat: 'proving', type: 'test', rarity: 'common', phase: 1,
    blurb: 'Red. Then green. Then snapped up.', hint: 'A failing test, passing again.',
    evolves: ['Ripening Snapper', 'Evergreen Snapper'],
    palette: { r: '#e63946', R: '#9d0208', w: '#fff4e4', k: K },
    pixels: ['..rrr...', '.rrrrr.R', 'rwkrrrRR', 'rrrrrrRR', '.rrrrr.R', '..rRr...'] },
  { no: 57, id: 'assertive-lobster', name: 'Assertive Lobster', habitat: 'proving', type: 'test', rarity: 'common', phase: 2,
    blurb: 'Expected one thing. Received another. Said so loudly.', hint: 'A failed assertion, passing again.',
    palette: { r: '#d62828', w: '#fff4e4', k: K },
    pixels: ['.k.k...w', '.rrr.www', 'rrrrrrw.', '.rrr.www', 'r.r.rw..'] },
  { no: 58, id: 'mirror-mullet', name: 'Mirror Mullet', habitat: 'proving', type: 'test', rarity: 'uncommon', phase: 2,
    blurb: 'Doesn\'t look like it used to.', hint: 'A snapshot mismatch, fixed (not just re-recorded).',
    palette: { M: '#6c757d', m: '#adb5bd', g: '#a8dadc', h: '#8a6a4a', k: K },
    pixels: ['.....gg.', 'Mmmm.ggg', 'Mmmkmggg', 'Mmmm.ggg', '.....gg.', '......h.', '......h.'] },

  // ---- The Sunken Vault: security
  { no: 59, id: 'leaky-clam', name: 'Leaky Clam', habitat: 'vault', type: 'sec', rarity: 'rare', phase: 2,
    blurb: 'Its pearl was an API key. Now it\'s in .env.', hint: 'A secret caught before a push and moved somewhere safe.',
    palette: { c: '#e5989b', y: '#ffd23f', C: '#b5838d' },
    pixels: ['.cccccc.', 'cccccccc', '........', '.yy.....', 'yyyyyyy.', '.yy..y.y', 'CCCCCCCC', '.CCCCCC.'] },
  { no: 60, id: 'barnacled-anchor', name: 'Barnacled Anchor', habitat: 'vault', type: 'sec', rarity: 'uncommon', phase: 2,
    blurb: 'Known vulnerabilities. Known, now fixed.', hint: 'A vulnerable dependency, patched.',
    palette: { a: '#577590', b: '#dfe5ec' },
    pixels: ['...a...', '..aba..', '...a...', 'aaaaaaa', '..bab..', 'a..a..b', 'ab.a.ba', '.aaaaa.'] },
  { no: 61, id: 'cert-cuttlefish', name: 'Cert Cuttlefish', habitat: 'vault', type: 'sec', rarity: 'rare', phase: 3,
    blurb: 'Its certificate expired at sea.', hint: 'A TLS certificate error, fixed (without switching checks off).',
    palette: { c: '#b5a48b', C: '#7f6f58', r: '#d62828', k: K },
    pixels: ['.ccccc..', 'cCcCccc.', 'kcccccrr', 'ccccc.rr', 'C.C.C.r.'] },

  // ---- The Haunted Wreck: ghosts
  { no: 62, id: 'flaky-phantom', name: 'Flaky Phantom', habitat: 'wreck', type: 'ghost', rarity: 'rare', phase: 1,
    blurb: 'Fails when you look away. Not any more.', hint: 'A flaky test, made steady.',
    evolves: ['Poltergeist', 'Banshee'],
    palette: { w: '#f4f1ea', g: '#c9c4d6', k: '#1a1a22', d: '#ff5d73' },
    pixels: ['..www...', '.wwwwg..', 'wkwwkwg.', 'wwwwwwgd', 'wwwkwwdd', 'wwwwwwg.', 'w.w.w.g.'] },
  { no: 63, id: 'heisenbug', name: 'Heisenbug', habitat: 'wreck', type: 'ghost', rarity: 'legendary', phase: 3,
    blurb: 'Observed it. It changed. Caught it anyway.', hint: 'Legendary: a flake that haunted you for days, gone for good.',
    palette: { w: '#e0fbfc', g: '#a8dadc', k: K },
    pixels: ['..wwww..', '.gggggg.', 'wwkwwkw.', 'gggg.g.g', 'wwwwww..', 'g.gg..g.', 'w.w..w..'] },
  { no: 64, id: 'race-wraith', name: 'Race Wraith', habitat: 'wreck', type: 'ghost', rarity: 'rare', phase: 3,
    blurb: 'Arrives before itself.', hint: 'A data race, fixed.',
    palette: { d: '#8d6e63', w: '#f1faee', g: '#cdeafe', k: K },
    pixels: ['dddddddd', 'dwwwgggd', 'dkwkgkgd', 'dwwwgggd', 'dw.wg.gd', 'd......d'] },
  { no: 65, id: 'cache-ghoul', name: 'Cache Ghoul', habitat: 'wreck', type: 'ghost', rarity: 'uncommon', phase: 3,
    blurb: 'Lives in the cache. Rent-free.', hint: 'A stale cache, cleared.',
    remedies: ['cache'],
    palette: { g: '#b8f2e6', b: '#c97b4a', B: '#8a5a3a', k: K },
    pixels: ['..ggg...', '.gkgkg..', '.ggggg..', 'bbbbbbbb', 'bBbbbbBb', 'bbbbbbbb', 'bBBBBBBb'] },
  { no: 66, id: 'zombie-process', name: 'Zombie Process', habitat: 'wreck', type: 'ghost', rarity: 'uncommon', phase: 3,
    blurb: 'Its parent left. It didn\'t.', hint: 'A leftover process that wouldn\'t let go, laid to rest.',
    palette: { z: '#b9fbc0', Z: '#80ed99', s: '#adb5bd', k: K },
    pixels: ['.k.k..s.', '.z.z.sss', 'zzzzzsks', 'ZzzzZsss', 'z.z.zsss'] },

  // ---- The second wave: newer finds, one or more for each habitat that had a gap
  { no: 67, id: 'garbled-jellyfish', name: 'Garbled Jellyfish', habitat: 'shallows', type: 'runtime', rarity: 'common', phase: 3,
    blurb: 'Expected JSON. Got a web page.', hint: 'Text that wouldn\'t parse as JSON, fixed.',
    palette: { j: '#ff99c8', J: '#e0609c', t: '#c77dff', k: K },
    pixels: ['..jjjj..', '.jjjjjj.', 'jjkjjkjj', 'JJJJJJJJ', 't.t..t.t', '.t.tt.t.', 't..t..t.'] },
  { no: 68, id: 'spinning-top-shell', name: 'Spinning Top Shell', habitat: 'shallows', type: 'runtime', rarity: 'uncommon', phase: 3,
    blurb: 'Rendered. Changed. Rendered. Changed.', hint: 'A render loop (maximum update depth), fixed.',
    palette: { s: '#ffb703', S: '#fb8500', w: '#fff4e4', k: K },
    pixels: ['..ssss..', '.sSSSSs.', 'sSwwwSSs', 'sSwSkwSs', 'sSwSSwSs', '.sSwwSs.', '..sSSs..', '...ss...'] },
  { no: 69, id: 'hydration-hydroid', name: 'Hydration Hydroid', habitat: 'shallows', type: 'runtime', rarity: 'uncommon', phase: 3,
    blurb: 'Grew one way on the server and another in the browser.', hint: 'A hydration mismatch, fixed.',
    palette: { h: '#90e0ef', H: '#0077b6', p: '#ffadad', k: K },
    pixels: ['.h.h.p..', '.h.h.p..', '..hpp...', '..hkp...', '..HHH...', '...H....', '...H....', '..HHH...'] },
  { no: 70, id: 'duplicate-dory', name: 'Duplicate Dory', habitat: 'burrows', type: 'io', rarity: 'uncommon', phase: 3,
    blurb: 'Already exists. Swears it\'s a different fish.', hint: 'A duplicate key or unique constraint, fixed.',
    palette: { b: '#4361ee', y: '#ffd23f', k: K },
    pixels: ['bbbb.y..', 'kbbbyy..', 'bbbb.y..', '........', 'bbbb.y..', 'kbbbyy..', 'bbbb.y..'] },
  { no: 71, id: 'tableless-turtle', name: 'Tableless Turtle', habitat: 'burrows', type: 'io', rarity: 'common', phase: 3,
    blurb: 'Went to sit at its table. There was no table.', hint: 'A database table or column that wasn\'t there, fixed.',
    palette: { g: '#a7c957', G: '#6a994e', s: '#f2e8cf', k: K },
    pixels: ['..gggg..', '.gGgGgss', 'gGgGgGsk', 'gggggggs', '.s.s.s..'] },
  { no: 72, id: 'crowded-sardines', name: 'Crowded Sardines', habitat: 'currents', type: 'net', rarity: 'common', phase: 3,
    blurb: 'Too many requests. Every one of them a sardine.', hint: 'Rate limited (429 Too Many Requests), fixed.',
    palette: { a: '#adb5bd', A: '#6c757d', k: K },
    pixels: ['kaa.kaa.', 'AAA.AAA.', '.kaa.kaa', '.AAA.AAA', 'kaa.kaa.', 'AAA.AAA.'] },
  { no: 73, id: 'castaway-cod', name: 'Castaway Cod', habitat: 'nets', type: 'vcs', rarity: 'common', phase: 3,
    blurb: 'Not a git repository. Not anyone\'s.', hint: 'Git outside a repo, or histories that never met, fixed.',
    palette: { c: '#c9ada7', C: '#9a8c98', s: '#f4d35e', b: '#4ea8de', k: K },
    pixels: ['........', '.cccc.c.', 'kccccccc', '.CCCC.C.', '.ssssss.', 'bbbbbbbb'] },
  { no: 74, id: 'trampled-sand-dollar', name: 'Trampled Sand Dollar', habitat: 'nets', type: 'vcs', rarity: 'uncommon', phase: 3,
    blurb: 'Your local changes would be overwritten. It was.', hint: 'Git refused to overwrite local changes, settled.',
    palette: { d: '#f2e8cf', D: '#bc6c25', k: K },
    pixels: ['..dddd..', '.dDddDd.', 'ddDDDDdd', 'dDDkkDDd', 'ddDDDDdd', '.dDddDd.', '..dddd..'] },
  { no: 75, id: 'nowhere-narwhal', name: 'Nowhere Narwhal', habitat: 'nets', type: 'vcs', rarity: 'common', phase: 3,
    blurb: 'Points confidently at a branch that isn\'t there.', hint: 'A branch, ref or pathspec git couldn\'t find, fixed.',
    palette: { n: '#a2d2ff', N: '#5e81ac', w: '#fff4e4', k: K },
    pixels: ['w.......', '.w......', '..nnnnn.', '.nnknnnn', '.NNNNNNn', '..NN..Nn'] },
  { no: 76, id: 'docked-whale-shark', name: 'Docked Whale Shark', habitat: 'workshop', type: 'build', rarity: 'rare', phase: 3,
    blurb: 'Carries every container. Won\'t leave the dock.', hint: 'A Docker daemon or image that wouldn\'t cooperate, fixed.',
    remedies: ['service'],
    palette: { d: '#264653', D: '#1b2f38', w: '#e9f5f9', r: '#e76f51', R: '#f4a261', k: K },
    pixels: ['...rR...', '..rRrR..', '.dwdddd.', 'dkdwdwdd', 'ddddwddd', 'wwwwwwdD', '.D.D.DD.'] },
  { no: 77, id: 'mojibake-moray', name: 'Mojibake Moray', habitat: 'pypool', type: 'py', rarity: 'uncommon', phase: 3,
    blurb: 'Its name had one accent. Now it has three odd letters.', hint: 'A text encoding error (UnicodeDecodeError), fixed.',
    palette: { m: '#7b2cbf', M: '#3c096c', y: '#ffd23f', k: K },
    pixels: ['.mmm....', 'mkmmm...', 'mmMmmm.y', '.y.mMmm.', '...ymMmm', '.....mMm', '....y.mM'] },
  { no: 78, id: 'idle-isopod', name: 'Idle Isopod', habitat: 'trench', type: 'sys', rarity: 'common', phase: 3,
    blurb: 'Declared. Never used. Go won\'t build around it.', hint: 'A Go variable or import declared and not used, fixed.',
    palette: { i: '#8d99ae', I: '#5c677d', z: '#e0e0e0', k: K },
    pixels: ['......zz', '.....z..', '.iiiii..', 'iIiIiIi.', 'kiIiIiIi', '.i.i.i..'] },
  { no: 79, id: 'sleepy-seahorse', name: 'Sleepy Seahorse', habitat: 'proving', type: 'test', rarity: 'uncommon', phase: 3,
    blurb: 'Dozed off halfway through the test.', hint: 'A test that timed out, fixed (not just given longer).',
    palette: { o: '#f4a261', O: '#e76f51', z: '#e0e0e0', k: K },
    pixels: ['......zz', '.ooo..z.', 'ookoo...', '..ooO...', '..oO....', '..ooO...', '...oO...', '..oO....'] },
  { no: 80, id: 'hollow-halibut', name: 'Hollow Halibut', habitat: 'proving', type: 'test', rarity: 'uncommon', phase: 3,
    blurb: 'All passed. None ran.', hint: 'A test run that found no tests, fixed.',
    palette: { h: '#d4a373', H: '#a98467', e: '#fefae0', k: K },
    pixels: ['..hhhhh.', '.hkeeehh', 'hheeeeeh', '.hheeehh', '..hhhhh.', '...H.H..'] },
  { no: 81, id: 'turned-away-turbot', name: 'Turned-Away Turbot', habitat: 'vault', type: 'sec', rarity: 'uncommon', phase: 3,
    blurb: 'Knocked with the wrong key. Twice.', hint: 'A 401 or 403 (not allowed in), fixed.',
    palette: { t: '#f6bd60', T: '#d08c60', r: '#e63946', w: '#fff4e4', k: K },
    pixels: ['rrr.....', 'rwr.ttt.', 'rrrttktt', '..tttttT', '..tTtTtT', '...ttt..'] },
  { no: 82, id: 'unset-sea-star', name: 'Unset Sea Star', habitat: 'vault', type: 'sec', rarity: 'uncommon', phase: 3,
    blurb: 'Missing an arm. The arm was an env var.', hint: 'A missing environment variable or secret, fixed.',
    palette: { s: '#ff8fa3', w: '#fff4e4', k: K },
    pixels: ['...s....', '...s....', 'sssssss.', '.skwks..', '..sss...', '.ss.ss..', 's.....s.'] },
  { no: 83, id: 'sealed-scallop', name: 'Sealed Scallop', habitat: 'vault', type: 'sec', rarity: 'uncommon', phase: 3,
    blurb: 'Permission denied (publickey). It has a key. Wrong one.', hint: 'Git or SSH wouldn\'t authenticate, fixed.',
    palette: { c: '#ffcad4', C: '#d68c9f', y: '#ffd23f', Y: '#c98a1a', k: K },
    pixels: ['.cCcCc..', 'cCcCcCc.', 'CcCcCcC.', 'kkkkkkk.', '.CCyCC..', '..yYy...', '...y....'] },

  // ---- tide events (events.js): no habitat, only about while their event is
  // on, and only ever along with a real catch. Never in "of N" or a badge.
  { no: 101, id: 'harvest-mouse', name: 'Harvest Mouse', habitat: null, event: 'harvest', type: 'test', rarity: 'rare', phase: 3,
    blurb: 'Lives in the wheat. Only comes out for a clean first try.', hint: 'Harvest Moon only: a fix that works first try.',
    palette: { b: '#c9a26b', B: '#8a6a3a', p: '#ffb4a2', y: '#ffd166', k: K },
    pixels: ['.....y..', '.bb..y..', 'bpbb.y..', 'bkbbbby.', 'bbbbbbby', '.B.B..y.'] },
  { no: 102, id: 'will-o-wisp', name: 'Will-o\'-Wisp', habitat: null, event: 'haunting', type: 'ghost', rarity: 'rare', phase: 3,
    blurb: 'A light over the wreck. Follows anyone still fixing bugs at night.', hint: 'The Haunting only: a fix after 9 pm.',
    palette: { g: '#b8ffd9', G: '#57cc99', w: '#ffffff', k: K },
    pixels: ['...g....', '..gGg...', '.gGwGg..', '.GwkwkG.', '.GwwwwG.', '..GwwG..', '...GG.g.', '.g..G...'] },
  { no: 103, id: 'frost-mite', name: 'Frost Mite', habitat: null, event: 'frostbite', type: 'sys', rarity: 'rare', phase: 3,
    blurb: 'Too small to see. Turns up on the busiest, coldest days.', hint: 'Frostbite only: your third catch in a day.',
    palette: { i: '#cdeafe', I: '#8ecae6', w: '#ffffff', k: K },
    pixels: ['i..w..i.', '.i.w.i..', '..iiii..', 'wiIkIkiw', '..iIIi..', '.i.ii.i.', 'i.i..i.i'] },
  { no: 104, id: 'lovebug', name: 'Lovebug', habitat: null, event: 'penpal', type: 'runtime', rarity: 'rare', phase: 3,
    blurb: 'Never found alone. Shows up when two of you work on one bug.', hint: 'Pen Pal Week only: a bug beaten with a helper crab.',
    palette: { r: '#ff5d8f', R: '#c9184a', p: '#ffb3c6', k: K },
    pixels: ['.k....k.', '..k..k..', '.rrRrr..', 'rpRRRrr.', 'rRkRkRr.', 'rrRRRrr.', '.r.r.r..'] },
  { no: 105, id: 'dust-bunny', name: 'Dust Bunny', habitat: null, event: 'spring-clean', type: 'build', rarity: 'rare', phase: 3,
    blurb: 'Made of code nobody needed. Gets bigger every year.', hint: 'Spring Clean only: a fix that deletes more than it adds.',
    palette: { g: '#d6d3cc', G: '#a8a39a', p: '#ffb3c6', k: K },
    pixels: ['.g...g..', '.gp.gp..', '.gg.gg..', 'gggggggG', 'gkggkggG', 'gggpgggG', '.GGGGGG.'] },
  { no: 106, id: 'tide-pool-nudibranch', name: 'Tide-Pool Nudibranch', habitat: null, event: 'low-tide', type: 'runtime', rarity: 'rare', phase: 3,
    blurb: 'Stranded when the sea went out. Very happy to be in a jar.', hint: 'Low Tide only: any catch in the Shallows.',
    palette: { o: '#ff9f1c', O: '#ff5a4a', b: '#4ea8de', w: '#fff4e4', k: K },
    pixels: ['.o.o.o..', 'o.o.o.o.', '.bbbbbb.', 'bwbbbbbb', 'bkbwwbbO', 'OOOOOOOO'] },

  // ---- kept apart: not in any habitat, hidden until caught
  { no: 99, id: 'missingno', name: 'UNDEFINED.', habitat: null, type: 'ghost', rarity: 'special', phase: 3,
    blurb: 'This one isn\'t in any book.', hint: 'Not in any habitat. Something glitchy.',
    palette: { a: K, b: '#f72585', c: '#4ea8de', d: '#fff4e4', e: '#7b2cbf' },
    pixels: ['aab.cdaa', 'daceabdc', 'aaadd.ab', 'cbaeadaa', 'aadcabea', 'abaaaacd', 'deacbaaa', 'aabdaeca'] },
].map(s => Object.freeze({
  ...s,
  event: s.event || null,
  evolves: s.evolves ? Object.freeze([...s.evolves]) : null,
  remedies: s.remedies ? Object.freeze([...s.remedies]) : null,
  pixels: Object.freeze([...s.pixels]),
  palette: Object.freeze({ ...s.palette }),
  portrait: portraitOf(s.id),
})));

// Each habitat has a boss: catch it and you earn the habitat's badge. Badges
// are 13×13 medals drawn like the bugs (gifts.js format), each its own shape so
// the silhouette of one you haven't earned still says which it is.
const HABITATS = Object.freeze([
  { id: 'shallows', name: 'The Shallows', icon: '🌊', boss: 'heap-leviathan',
    badge: { name: 'Tide Badge', palette: { o: '#0b2f5c', d: '#123f80', a: '#1d6fd1', b: '#4ea8de', c: '#ffffff', e: '#caf0f8' }, pixels: [
      '......o......',
      '.....oco.....',
      '.....obo.....',
      '....obcao....',
      '...obcbbao...',
      '..obcbbbbao..',
      '..obbbbbbao..',
      '.oeebbbeeeao.',
      '.obbeeebbbeo.',
      '.obbbbbbbbdo.',
      '..oabbbbbdo..',
      '...oaaaddo...',
      '....ooooo....'] } },
  { id: 'burrows', name: 'The Burrows', icon: '🕳️', boss: 'overstuffed-pufferfish',
    badge: { name: 'Burrow Badge', palette: { o: '#2a1a10', d: '#5d4037', a: '#8d6e63', b: '#b08968', e: '#d7b899', c: '#1a0f08', f: '#3f8f3a', g: '#80c95a' }, pixels: [
      '...ooooooo...',
      '..ofgfgfgfo..',
      '.ofgfgfgfgfo.',
      'obbebbbbbbbao',
      'obbaacccaaado',
      'obaacccccaado',
      'obacccccccado',
      'obacccccccado',
      'oaaacccccaado',
      '.oaaaaaaaado.',
      '..odaaaaado..',
      '...odddddo...',
      '....ooooo....'] } },
  { id: 'currents', name: 'The Currents', icon: '🌀', boss: 'meltdown-medusa',
    badge: { name: 'Current Badge', palette: { o: '#0d3b66', d: '#1f5f8b', a: '#4ea8de', b: '#2a7fba', e: '#caf0f8', c: '#ffffff' }, pixels: [
      '....ooooo....',
      '..ooaaaaaoo..',
      '.oaabbbbbaao.',
      '.oabeeeeebdo.',
      'oabebbbbbebdo',
      'oabbbeeebebdo',
      'oabbebcebebdo',
      'oabbebbbbebdo',
      'oabbbeeeebbdo',
      '.oabbbbbbbdo.',
      '.odabbbbbddo.',
      '..oodddddoo..',
      '....ooooo....'] } },
  { id: 'nets', name: 'Tangled Nets', icon: '🪢', boss: 'two-headed-crab',
    badge: { name: 'Knot Badge', palette: { o: '#5c2205', d: '#b5480f', a: '#f3722c', b: '#f8961e', c: '#fff1d6', e: '#ffd6a5', f: '#c9813a' }, pixels: [
      '......o......',
      '.....oco.....',
      '....obcbo....',
      '...obbbbao...',
      '..obeeeeeao..',
      '.obefbbbfeao.',
      'oeefbbbbbfeeo',
      '.obefbbbfedo.',
      '..oaeeeeedo..',
      '...oaaaddo...',
      '....oaddo....',
      '.....odo.....',
      '......o......'] } },
  { id: 'lighthouse', name: 'The Lighthouse', icon: '🗼', boss: 'matrix-hydra',
    badge: { name: 'Beacon Badge', palette: { o: '#1a1030', n: '#1b2a4a', m: '#8ea9db', y: '#ffe66d', g: '#fff6b8', a: '#e63946', d: '#9b1d28', c: '#ffffff', e: '#ced4da', r: '#5c636a', s: '#8f979f' }, pixels: [
      '....ooooo....',
      '..oonnnnnoo..',
      '.onmnndnnnno.',
      '.oggyyyyyggo.',
      'onnnndddnnnno',
      'onnnnaadnnmno',
      'onnnnccennnno',
      'onmnnaadnnnno',
      '.onnnccennno.',
      '.onnaaaadnno.',
      '..orsrrrsro..',
      '...orrrrro...',
      '....ooooo....'] } },
  { id: 'workshop', name: 'The Reef Workshop', icon: '🛠️', boss: 'tangled-tree-crab',
    badge: { name: 'Wrench Badge', palette: { o: '#2b3036', d: '#6c757d', a: '#8f979f', b: '#c3c9cf', c: '#ffffff', e: '#d9792f' }, pixels: [
      '.ooooooooooo.',
      '.occbbbbbbdo.',
      '.ocbbbbebedo.',
      '.obbbbbeeedo.',
      '.obbbbeebbdo.',
      '.obbbeebbbdo.',
      '.obbeebbbbdo.',
      '.obeebbbbbdo.',
      '.oaebbbbbado.',
      '..oabbbbado..',
      '...oabbado...',
      '....oaado....',
      '.....ooo.....'] } },
  { id: 'kelp', name: 'The Kelp Maze', icon: '🌿', boss: 'optional-oarfish',
    badge: { name: 'Kelp Badge', palette: { o: '#0b3d2e', d: '#1b6b52', a: '#2a9d8f', b: '#52b788', c: '#d8f3dc', e: '#80ed99' }, pixels: [
      '......o......',
      '.....oco.....',
      '....obcao....',
      '...obcbbao...',
      '..obcbebbao..',
      '..obbbebbao..',
      '.obbbebbbbao.',
      '..obbbebbdo..',
      '..obbebbbdo..',
      '...obebbdo...',
      '....oebdo....',
      '.....oeo.....',
      '......o......'] } },
  { id: 'pypool', name: 'The Sea-Snake Pool', icon: '🐍', boss: 'circular-sea-snake',
    badge: { name: 'Coil Badge', palette: { o: '#3a2a00', y: '#ffd43b', z: '#b8860b', n: '#123c3a', a: '#43aa8b', b: '#ffd43b', c: '#ffffff' }, pixels: [
      '...ooooooo...',
      '..oyyyyyyyo..',
      '.oyynnnnnyzo.',
      'oyynababanzzo',
      'oynannnnnbnzo',
      'oynnnabananzo',
      'oynnancanbnzo',
      'oynnbnnnnanzo',
      'oynnnababnnzo',
      'oyynnnnnnnzzo',
      '.ozynnnnnzzo.',
      '..ozzzzzzzo..',
      '...ooooooo...'] } },
  { id: 'trench', name: 'The Deep Trench', icon: '🌑', boss: 'knotted-eels',
    badge: { name: 'Abyss Badge', palette: { o: '#1a0533', e: '#3c096c', d: '#5a189a', a: '#7b2cbf', b: '#9d4edd', c: '#e0aaff', f: '#ffffff' }, pixels: [
      '......o......',
      '.....oco.....',
      '..f.ocbao....',
      '...ocbbado...',
      '...obbbado...',
      '.o.obbaado.o.',
      'oco.obaado.oc',
      'obao.badoobdo',
      'obaoobaddoado',
      '.odooaaddoeo.',
      '..o.oadeo.o..',
      '.....odo.....',
      '......o......'] } },
  { id: 'proving', name: 'The Proving Pools', icon: '🧪', boss: 'mirror-mullet',
    badge: { name: 'Flask Badge', palette: { o: '#1e3a14', c: '#ffffff', b: '#d8f3dc', d: '#8fb3a0', e: '#b5e48c', g: '#90be6d', f: '#e9ffd9', h: '#55803b' }, pixels: [
      '....ooooo....',
      '....ocbdo....',
      '....ocbdo....',
      '...ocbbbdo...',
      '..ocbbbbbdo..',
      '..oeeeeeeeo..',
      '.oeggfgggfgo.',
      '.oggggfggggo.',
      'oegggggggggho',
      'oegggfgggghho',
      'ohgggggggghho',
      'ohhhhhhhhhhho',
      '.ooooooooooo.'] } },
  { id: 'vault', name: 'The Sunken Vault', icon: '🔐', boss: 'cert-cuttlefish',
    badge: { name: 'Key Badge', palette: { o: '#5a3a00', d: '#a06a00', a: '#ffc15e', b: '#ffd98a', c: '#fff8dc', e: '#c48a1a', k: '#2a1a00' }, pixels: [
      '.ooooooooooo.',
      'oacbbbbbbbado',
      'ocbbbbbbbbbdo',
      'obebbbkbbbedo',
      'obbbbkkkbbbdo',
      'ocbbbkkkbbbdo',
      'obbbbbkbbbbdo',
      'obbbbbkbbbbdo',
      'obbbbkkkbbbdo',
      'obebbbbbbbedo',
      'obbbbbbbbbbdo',
      'oaddddddddddo',
      '.ooooooooooo.'] } },
  { id: 'wreck', name: 'The Haunted Wreck', icon: '👻', boss: 'race-wraith',
    badge: { name: 'Lantern Badge', palette: { o: '#0c2a1e', a: '#2f6b4f', d: '#1b4433', b: '#b8ffd9', c: '#57cc99', f: '#ffffff' }, pixels: [
      '.....ooo.....',
      '.....o.o.....',
      '....ooooo....',
      '...oaaaaao...',
      '..oaaaaaaao..',
      '..oabbcbbdo..',
      '..oabcfcbdo..',
      '..oacfffcdo..',
      '..oacfffcdo..',
      '..oabcccbdo..',
      '..oaaaaaado..',
      '...odddddo...',
      '....ooooo....'] } },
].map(h => Object.freeze({
  ...h,
  badge: Object.freeze({ name: h.badge.name, palette: Object.freeze({ ...h.badge.palette }), pixels: Object.freeze([...h.badge.pixels]) }),
  members: Object.freeze(SPECIES.filter(s => s.habitat === h.id).map(s => s.id)),
})));

// After the badges, the league: the Deep Four and the champion. Catching all
// of them, with every badge, puts you in the Hall of Fame.
const LEAGUE = Object.freeze({
  elite: Object.freeze(['segfault-squid', 'leaky-clam', 'flaky-phantom', 'the-kraken']),
  champion: 'heisenbug',
});

/** 'elite', 'champion' or null: a species' place in the league. */
const leagueOf = id => (id === LEAGUE.champion ? 'champion' : LEAGUE.elite.includes(id) ? 'elite' : null);

/** The habitat a species is the boss of, or null. */
const bossOf = id => HABITATS.find(h => h.boss === id) || null;

const BY_ID = new Map(SPECIES.map(s => [s.id, s]));
const speciesById = id => BY_ID.get(id) || null;

/** The tide events' own bugs (events.js), kept out of every habitat. */
const eventSpecies = () => SPECIES.filter(s => s.event);

/** The species that count toward "of N": built, and living in a habitat (not the hidden glitch, #099). */
const live = () => SPECIES.filter(s => s.phase <= LIVE_PHASE && s.habitat);

module.exports = { SPECIES, HABITATS, TYPES, RARITY, BY_ID, LIVE_PHASE, LEAGUE, speciesById, live, eventSpecies, leagueOf, bossOf };
