// Portraits for the Burrows' species (see index.js).

module.exports = {
  'shell-less-hermit': {
    palette: { H: '#ffa07a', r: '#ff6b4a', R: '#c2412d', D: '#7f2430', q: '#ffe1d6', p: '#ffc2b0', P: '#e89a86', Q: '#b86a6a', t: '#9ad8ff', w: '#fff4e4', k: '#2b1d2a' },
    pixels: [
      '..ww...ww..........',
      '.wwkw.wwkw.........',
      '.wkkw.wkkw.........',
      't.ww...ww.qqqPqqP..',
      't..R...R.qppPppPPP.',
      'H.H.HHHHrRppPppPpP.',
      'HrH.HHrrrrRpPppPppP',
      'HrrDHrrrrrRpPppPppP',
      'HrrDrrrrrRRpPpPPppP',
      'RrRDrrrrRRRPPPPpppP',
      '.RDRRRRRRDQ...PPPPP',
      '...HR.HR.HR...qPpPQ',
      '..HR..RD..R..qPPPP.',
      '..RD...R..D.qppPPQ.',
      '............PPPQ...',
    ],
  },
  'locked-limpet': {
    palette: { h: '#cbb2a6', s: '#a1887f', S: '#6d4c41', D: '#4a3029', f: '#8a6a62', F: '#634843', g: '#8d99ae', G: '#5c677d', Y: '#fff09a', y: '#ffd23f', o: '#c99a1a', O: '#8a6512', w: '#fff4e4', k: '#2b1d1a' },
    pixels: [
      '......YYYo.........',
      '.....Yo..Yo........',
      '.....Yo..Yo........',
      '....YYYYYYYos......',
      '...hYyyyyyyOsss....',
      '..hhYyykkyyOssss...',
      '.hhhYyykkyyODsssS..',
      '.hhhYyyykyyOsDssS..',
      'hhhsoooooooODsDsSS.',
      'hhshhshsssssDssDSS.',
      'DDDDDDDDDDDDDDDDDDD',
      '.fwwkDfffDwkffffff.',
      '.fwkkwfFfwkkffffFF.',
      '.ffwwfFfFfwwfffFFF.',
      '..FFFFFFFFFFFFFFF..',
      'ggggggggggggggggggg',
      'GGGGGGGGGGGGGGGGGGG',
    ],
  },
  'clingy-barnacle': {
    palette: { w: '#fff4e4', g: '#c9c4d6', G: '#9a94ad', l: '#8d99ae', f: '#dfe3ec', b: '#9aa6bb', B: '#66728a', D: '#3e465c', c: '#f2c79a', C: '#d29a63', p: '#ff9fb2', k: '#2b2d42' },
    pixels: [
      'wwwwwwg......c.c......',
      'wwwwwwgg.....CcC......',
      'wlllwwGg..f.bDkkDb.B..',
      'wwwwwwww..ffbDDDDbBBD.',
      'wllllwwg..ffBbbbbbBBD.',
      'wwwwcccccCfBbbbbbbBDD.',
      'wlllcCCCCffBbbbbbbBDD.',
      'wwwwCwwg.ffwwbbwwbBDD.',
      'wllllwwg.fwwkwbwkwBDD.',
      'wwwwwwwg.fwkkwbkkwBBD.',
      'wlllwwwg.ffwwbbwwbBBDD',
      'wwwwwwwg.fppbDDbpbBBDD',
      'gggggggGfffbBbbbbbBBDD',
      '........ffbBbbbbbBBBDD',
      '........ffbbBbbbbbBBDD',
      '........DDDDDDDDDDDDDD',
    ],
  },
  'mixed-up-mussel': {
    palette: { m: '#3d405b', F: '#ffe79a', f: '#ffd166', o: '#e0a538', O: '#a8741c', w: '#fff4e4', g: '#d6cfc4', G: '#a59d93', l: '#8d99ae', k: '#2b2d42' },
    pixels: [
      '....FFFo............',
      '...FFffoFFFFFFf.....',
      '..FFffffffffffffo...',
      '.FFfwwffFwwffffffoo.',
      '.FfkkwwffwwkfffffooO',
      'FffkwwwffwkkffffffoO',
      '.ooowwooowwooooooooO',
      'mmmmmmmmmmmmmmmmmmmm',
      '.mmmmwwwwwwwwwwwwgG.',
      '..wwwwwwwwwwwwwwwwgG',
      '..wwllllllllllwwwgg.',
      '..wwwwwwwwwwwwwwwgg.',
      '...wwllllllllllwggG.',
      '....wwwwwwwwwwwggG..',
      '.....ggllllllgGG....',
      '........GGGGG.......',
    ],
  },
  'overstuffed-pufferfish': {
    palette: { Y: '#fff09a', y: '#ffd23f', o: '#e9a23b', O: '#b86b1f', c: '#fff4d6', C: '#efd29a', S: '#f28f5c', T: '#c2502d', r: '#ff8c69', x: '#8a4b16', w: '#ffffff', p: '#e8e4f0', l: '#8d99ae', k: '#2b1d1a' },
    pixels: [
      '........T....T........',
      '.......TTS..TSS.......',
      '.......TTSSTTSS.......',
      '...TSSYYyyyyyyS.TTT...',
      '...TSSYwYYyyyyyyTSS...',
      '...TxxYYYyyyxxyyySS...',
      '....yxxxyyxxyyyyyy....',
      '..ywwwwyyywwyyyyyySSS.',
      '..wwwwkwywwkwyyyyyoSSS',
      '..wwwkkwywkkwyyyyyoTTS',
      '..ywwwwyyywwyyyyyyoSS.',
      '..yrrryyyyrryyyyyooSS.',
      'ppOyyccccccccccCoooTT.',
      'plOyycccccccccCCCoOTTT',
      'ppOyccccccccccCCCCTTT.',
      '....cccccccccCCCCC....',
      '...TTccccccCCCCCCSS...',
      '...TTSCCCCCCCCCCTTS...',
      '...SSS.TCCCCCCS.TTS...',
      '.......TTSSTTSS.......',
      '.......TTS..TSS.......',
      '........S....S........',
    ],
  },
};
