// Portraits for The Currents' species (see index.js).

module.exports = {
  'closed-clam': {
    palette: { h: '#ffd3cf', c: '#eba0a3', p: '#cd7d8c', P: '#a25a72', R: '#c06a82', L: '#d9a6ae', C: '#b5838d', M: '#8c5f74', D: '#5e3a55', x: '#3a1f33', w: '#ffffff', k: '#2a1426', a: '#cfe8ff' },
    pixels: [
      '......hhhhhhcc......',
      '....hhhhhhhhcccc....',
      '...hhhhRRRRRRpppp...',
      '..hhhRRhhcccpRRppP..',
      '.hhhRhhccccccppRpPP.',
      '.hhRhhcRRRRRcppPRPP.',
      'hhhRhcRcccccRppPRPPP',
      'hhRhcRcccccccRpPPRPP',
      'ccRccRcccccccRpPPRPP',
      '.xxwwwxxwwwxxxxxxxx.',
      '.xxakwxxakwxxxxxxxx.',
      '.xxkkwxxkkwxxxxxxxx.',
      'LLLLLLLLLLLLCCCCCCCC',
      '.CCCCCCCCMMMMMMDDDD.',
      '.CCCCCCCMMMMMMDDDDD.',
      '..CCCCCMMMMMMDDDDD..',
      '...CCCMMMMMMDDDDD...',
      '.....MMMMMMDDDD.....',
    ],
  },
  'port-squatter': {
    palette: { G: '#ecc983', g: '#b98f52', b: '#81602f', B: '#523a20', a: '#a8dadc', A: '#5f9db3', q: '#3d6788', H: '#ffa07a', r: '#ff6b4a', R: '#c4403c', D: '#7a2430', w: '#ffffff', n: '#ffffff', k: '#2b1622' },
    pixels: [
      '.......GGGGGGg.......',
      '.....GGGGgggggbb.....',
      '....GGgggggggggbb....',
      '...GGgggqqqqqgggbb...',
      '..GGggqqqqqqqqqggbb..',
      '..GggqqAAAAAAAAAgbb..',
      '.GgggqARRRARRRAagbbB.',
      '.GggqAAnkwAnkwAaagbB.',
      '.GggqAAkkwAkkwaaagbB.',
      '.gggqAAARAAARAaaagbB.',
      '.gggqAHHHrrrrrRaabbB.',
      '.HHrqHHrrrrrDrrRaHrr.',
      'HHrrrRrrrrDDDrrrHrrRR',
      'HrrRRDrrrrrrrrrHrrRRD',
      'HrgRDgRRRRRRRRRrRDbrD',
      'rR.gDggbDDDDDDbbDBB.D',
      '.R..gggbbbbbbbbbBB...',
      '.....bbbbbbbbbBBB....',
      '.......bbBBBBB.......',
    ],
  },
  'slowpoke-snail': {
    palette: { M: '#f2f2f4', a: '#a9a9b4', A: '#6c6c7c', N: '#474758', f: '#fbf7ec', F: '#d4cdbc', r: '#e63946', y: '#ead8ae', b: '#c9b38a', B: '#977f5f', D: '#64523e', w: '#ffffff', k: '#2a2430', g: '#cfe8ff' },
    pixels: [
      '..yb..yb..MaA......',
      '..bB..bB...a.......',
      '...b..b..MMMMM.....',
      '...b.b.MMMMMMMaa...',
      '..yybbMMMFFAFFaaa..',
      '.yybbbMMFFFkFFFaa..',
      'yBBBBMMFFFFkFffFaA.',
      'ygkwwMMFFFFkffffaA.',
      'ykkwwMMAFFfrrrrAAA.',
      'ybbbbaaFFfffffffAN.',
      'bDDbbbaaFffffffAA..',
      'bbbbbbaaaffAffAAN..',
      'bbbbbBBAaaAAAANNbB.',
      'ybbbbbbbbAAANNbBBBB',
      '.BBBBBBBBBBBBBBBDD.',
    ],
  },
  'snapped-line': {
    palette: { l: '#eef2f6', L: '#9aa5b8', y: '#ffd23f', H: '#ff8080', r: '#e63946', R: '#a3203f', D: '#5e1530', c: '#fff4e4', C: '#d9c7b0', E: '#a69077', t: '#ff9fb2', h: '#8d99ae', w: '#ffffff', k: '#2a1426' },
    pixels: [
      '..........l...',
      '..........l...',
      '.........l.l..',
      '..............',
      '......l.l.....',
      '.......l......',
      '.....HHyy.....',
      '...HHHHHrrr...',
      '..HHHHHrrrrr..',
      '.HRRRHHRRRrrr.',
      '.HwwkHrwwkrrr.',
      '.HwkkrrwkkrrR.',
      'rrrDDDDDDrrrRD',
      '.cccttDcccccC.',
      '.cccttcccccCC.',
      '.cccccccccCCE.',
      '..ccccccCCCE..',
      '...cccCCCCE...',
      '.....CCCE.....',
      '......L.......',
      '......L.h.....',
      '......hhh.....',
    ],
  },
  'nameless-buoy': {
    palette: { K: '#4a4458', y: '#ffd23f', Y: '#d99a2b', k: '#2a1426', H: '#ff8080', r: '#e63946', R: '#a3203f', D: '#5e1530', c: '#fff4e4', C: '#d9c7b0', B: '#a8e0f7', b: '#4ea8de', N: '#2f6fb0', w: '#ffffff' },
    pixels: [
      '.....Ky...........',
      '.....Kyyyyyy......',
      '.....KykkyyyY.....',
      '.....Kyyykyy......',
      '.....Kyykyyy......',
      '.....Kyyyyyy......',
      '.....KyykyY.......',
      '.....HHrrR........',
      '...HHHrrrrrRR.....',
      '..HHrrrrrrrrRR....',
      '..Hkkwrrrwwwrr....',
      '.HHkwwrrrwwkrrr...',
      '.Hrwwwrrrwkkrrr...',
      '.ccccDcDcccccCC...',
      '.ccccccccccCCCC...',
      '.rrrrrrrrrrrRRD...',
      '.RBBbRRRRRRBBbD...',
      'BBbbbBBBBBBbbbBBBb',
      'bbbbbbbbbbbbbbbbbN',
      '.NbbbNNbbbbNNbbbN.',
    ],
  },
  'border-crab': {
    palette: { L: '#5f6488', c: '#3d405b', C: '#23253b', y: '#ffd23f', H: '#ff8a5c', r: '#e04a33', R: '#a32c34', D: '#5c1828', s: '#a07a52', T: '#5a4029', K: '#2b2d42', i: '#e63946', w: '#ffffff', k: '#1c1a2c' },
    pixels: [
      '......LLLccc......ss.',
      '.....LLcccccC....sssT',
      '.....LccyyccC..HrrsT.',
      '.....LccyyccC..rRRsT.',
      'CCCCCCCCCCCCCC..rKKKK',
      '....CccccccccC.rR.iii',
      '....HHrrrrrrrrrrR....',
      '...HCCCCrCCCCrrR.....',
      'H.rHwwwkrwwwkrrRR....',
      'H.rRwwkkrwwkkrrrr....',
      'HrrRrrrrrrrrrrrRR....',
      'rrRDrrDDDDDrrrRRD....',
      '.RDrrrrrrrrrrRRRD....',
      '...RRRRRRRRRRRRD.....',
      '....DDDDDDDDDDD......',
      '...RD.RD...RD.RD.....',
      '..RD.RD.....RD.RD....',
      '..D..D.......D..D....',
    ],
  },
  'lost-parcel-crab': {
    palette: { P: '#ecc193', T: '#fbe7bd', b: '#c97b4a', B: '#8a5236', i: '#d62828', H: '#ffc89a', o: '#f4945a', O: '#c8623a', Q: '#7e3528', w: '#ffffff', a: '#bfe8f5', k: '#2b1622' },
    pixels: [
      '.PPPPPPTTPPPPPP.',
      'PPPPPPPTTPPPPPPB',
      'bbbbbbbbbbbbbbBB',
      'bbibibiiibibibBB',
      'bbiiibibibiiibBB',
      'HobbibiiibbbiboO',
      'HoObbbbbbbbbbboO',
      'ooOBBBBBBBBBBBoO',
      '.oOHoooooooooOOQ',
      '.HHwwwooowwwoOa.',
      '.Howakooowakooa.',
      '.oowkkoooowkkOO.',
      '.ooooooQQoooOOQ.',
      '..OOOOOOOOOOOQ..',
      '.OQ.OQ....OQ.OQ.',
      '.Q..Q......Q..Q.',
    ],
  },
  'meltdown-medusa': {
    palette: { s: '#eef2f6', S: '#a9b6cc', H: '#ff8f7a', r: '#e63946', R: '#b21e4b', D: '#6f1240', p: '#f26d7d', O: '#ff9f1c', Y: '#ffe08a', w: '#ffffff', n: '#ffffff', k: '#2a0f2a' },
    pixels: [
      '...ss........ss.......',
      '..sssS.ss...sssS......',
      '...SS..sS....SS.......',
      '......................',
      '.......HHHHrrrr.......',
      '.....HHHHrrrrrrrR.....',
      '....HHHrrrrrrrOOrRR...',
      '...HHHrrrrrrrOYYOrRR..',
      '..HHrrrrrrrrrrOOrrrRR.',
      '.HHrDDDDrrDDDrrrrrrRRR',
      '.HrrwwnkrrwnkrrrrrRRRR',
      'HrrrwwkkrrwkkrrrrRRRRR',
      'rrrrrrrrrDrrrrrrRRRRRD',
      'RRrrrDDDDrrrrrrRRRRRDD',
      'DRpRDRpRDRpRDRpRDRRDD.',
      '..pR...pR...pR...pR...',
      '.pR...pR.....pR...pR..',
      '.pR...pR......pR..pR..',
      '..RD...pR....pR...RD..',
      '...D....pR..pR.....D..',
      '........RD..RD........',
      '.......D.....D........',
    ],
  },
  'crowded-sardines': {
    palette: { H: '#e9ecef', a: '#adb5bd', A: '#6c757d', D: '#495057', w: '#ffffff', k: '#2b2d42' },
    pixels: [
      'wkaaaaD.wkaaaaD.',
      'HaaaaAAAHaaaaAAA',
      '.AAAAD..AAAAD...',
      '...wkaaaaD.wkaaa',
      '...HaaaaAAAHaaaa',
      '....AAAAD..AAAAD',
      'wkaaaaD.wkaaaaD.',
      'HaaaaAAAHaaaaAAA',
      '.AAAAD..AAAAD...',
    ],
  },
};
