// Portraits for the tide-event species and the hidden UNDEFINED. (see index.js).

module.exports = {
  'harvest-mouse': {
    palette: { L: '#e8c992', b: '#c9a26b', B: '#8a6a3a', D: '#5e4526', c: '#f6e7c8', p: '#ffb4a2', P: '#e07a6a', u: '#fff0b3', y: '#ffd166', Y: '#e0a83a', O: '#a8742a', k: '#2b2d42', W: '#ffffff' },
    pixels: [
      '...LLLB......u..u..u',
      '..LLppbB.bbD..u.u.u.',
      '..LpPPpBbbBBD..uyuy.',
      '..BpPPpBDBBDD.uyYyYu',
      '...BppBBDDDD..yYOyYO',
      '..LLLbbbbBD..uyYyYyY',
      '.LLkkbbbbbBD..yYOyYO',
      'BLbkWbbbbBBD..yYyYyY',
      'PBBkkbbbbBDD...YOyYO',
      '.DDBbppbbBD.....YOO.',
      '.BBDbbbbbBD...LbOY..',
      '....LbbbbbBD.bbBOY..',
      '...LLcccbbbBD...OY..',
      '...LccccbbbBD...OY..',
      '...BccccbbBBD...OY..',
      '...DcccbbBBDD...OY..',
      '....DccBBBDD....OYY.',
      '.....DDDDDD.p...OY.Y',
      '....pp....pp.ppPPP..',
      '................OP..',
      '................PY..',
      '................OY..',
    ],
  },
  'will-o-wisp': {
    palette: { w: '#ffffff', c: '#eafff3', g: '#b8ffd9', G: '#57cc99', H: '#2d9a6e', J: '#1f6f55', k: '#1b3a33', W: '#ffffff', p: '#ffb3c6' },
    pixels: [
      '..................JJ',
      '.............J...HJ.',
      '............HJ..HgJ.',
      '..G....J...GgJ.HHg..',
      '......gg..gGgGGHJJ..',
      '.....ggg.gggggGHJ...',
      '....ggggggggggGHJ...',
      '...ggccccccgggGHJ..g',
      '..ggcccwccccgggHJ...',
      '..gcWkwwWkcccggGHJ..',
      '.GgckkwwkkwccggGHJ..',
      '.HgckkwwkkwccggHHJ..',
      '.JgpwwwwwpwccggHJJG.',
      '..JgckwwkwccggHJJ...',
      '...ggckkcccgggJJ....',
      'g...gggccggggJJ.....',
      'G.....gggggJJ.......',
      '.G......JJJ.........',
      '.GG...........g.....',
    ],
  },
  'frost-mite': {
    palette: { h: '#f2fbff', i: '#cdeafe', I: '#8ecae6', D: '#4f8fc0', w: '#ffffff', k: '#2b2d42', W: '#ffffff', p: '#a9c8ff' },
    pixels: [
      '............w......',
      '...........wwh.....',
      '...........whI..w..',
      '........h..whI.whh.',
      '.......whh.whI.whI.',
      '.......whI.whIwhhI.',
      '.......whIwwhIwhII.',
      '......hhhIIhhIIhI..',
      '....hhhiiiiiiiiID..',
      '...hhiiiiiiiiiiiID.',
      '..hhhhDiiiiiiiiiID.',
      '.WkiWkiIiiiiiiiIID.',
      'hkkikkiIiiiiiiIIDD.',
      'hkkikkiIiiiiIIIDDD.',
      'piiiipDIIIIIIDDD.D.',
      '.DDiiDDIDDDDDD...D.',
      '..DIDD.I..I..DI...D',
      '..I...I...I...I....',
      '..I..I....I....I...',
      '..w..w.....w...w...',
    ],
  },
  lovebug: {
    palette: { p: '#ffb3c6', r: '#ff5d8f', R: '#c9184a', E: '#8a1038', k: '#2b2d42', K: '#4a4d6a', M: '#ff5d8f', W: '#ffffff' },
    pixels: [
      '...........p.........',
      '............k...rE.rE',
      '.............KKKKRrrE',
      '............KWWkkRRRE',
      'p...p.......KkWkkRRRE',
      '.k...k.......KkpERREE',
      '..k..k.ppRE..ppREEEE.',
      '......ppprREEprrRE...',
      '..KKKKKprrrrEprrRE...',
      '.KKkkkkKrrrrErrrrRE..',
      'KWWkWWkkrrrrErrrRRE..',
      'KWkkWkkkrrrrErrRREE..',
      'KkkkkkkkrrrrErRREE...',
      '.KpkkpkERrrrERREE....',
      '..KMMk..ERrrEREE.....',
      '.........ERREEE......',
      '..........EREE.......',
      '...........EE........',
      '......k..k..k........',
      '.......k..k..k.......',
    ],
  },
  'dust-bunny': {
    palette: { h: '#eeebe4', g: '#d6d3cc', G: '#a8a39a', D: '#7c776e', p: '#ffb3c6', k: '#2b2d42', b: '#7fa6d0', B: '#4f6f96' },
    pixels: [
      '...hG....hhhG........',
      '..hpgG..hhGGGG.......',
      '..hppG..hpG..GG......',
      '..hppG..hpG...G.....g',
      '..hpGG..hpG..........',
      '..GgGGD.hGD.GD.......',
      '..hhhhghhhghhgGD.....',
      '.hhggggggggggggGD.D..',
      '.hgggghgggggggggGD...',
      'GhggggghggggggggGD...',
      'DgkkgggkkgggggGggGD..',
      '.hgggggggggggggGgGD..',
      '.hgggpgggggggbbggGD..',
      'GhggGgGggggggbgggGD..',
      'DGggggggggggBgggGGD..',
      '.DgggggggGgggbgGGDD..',
      '..GGgGggggGgGbbGDD...',
      '..DGDDGGGGGDDGDDD....',
      '...DD.DDDDDD.DD......',
    ],
  },
  'tide-pool-nudibranch': {
    palette: { L: '#8fd0f5', b: '#4ea8de', B: '#2f74b5', D: '#22528a', w: '#fff4e4', u: '#ffe08a', o: '#ff9f1c', O: '#ff5a4a', R: '#c23a3a', k: '#2b2d42', W: '#ffffff', p: '#ff9fb0' },
    pixels: [
      '.u..u.......oO........',
      '.o..o....oO.OR........',
      '.O..O....OR.OR.oO.....',
      '..O.O...uuRuuR.OR.....',
      '......uuoORoORuuR.....',
      '..LLLBoOoORoORoOR.....',
      '.LLbbboOoORoORoORuu...',
      'LWkbWkoOoORoORoORoO...',
      'BkkbkkOROR.oO.oO.oOwBD',
      'pBbbbpOROR.OR.OR.ORBBD',
      '.kbbkbbbBD.OR.OR.ORDDD',
      '..kkbbbbbbLLLLLLBBDD..',
      '..BbbbbbbbbbbbBBBDD...',
      '..wBBBBBBBBBBBBDDD....',
      '...wwwDDDDDDDDDD......',
      '.....wwwwwwwwwww......',
    ],
  },
  missingno: {
    palette: { a: '#2b2d42', A: '#14141f', b: '#f72585', B: '#a3195b', c: '#4ea8de', C: '#2a6f9e', d: '#fff4e4', D: '#cbbfa8', e: '#7b2cbf', E: '#a66be0', F: '#4f1a85', W: '#ffffff', G: '#9fd6f5' },
    pixels: [
      '............EEEEbbbb..',
      '..bb........EeeeBBBB..',
      '..bB........Eeeebbbb..',
      '............EeeeBBBB..',
      '....EEEEEEEEddddeeeF..',
      '....ddddddeedAAdeeeF..',
      '....ddddddeedAWdeeeF..',
      '....ddAAddeeDDDDeeeF..',
      'EEEEddAWddeeeeeecccc..',
      'EeeeddddddeeeeeecCCc..',
      'EeeeDDDDDDeeeeeecCCc..',
      'Eeeeeeeeeeeeeeeecccc..',
      '..Eeeeeeeeeeeeeeeecdcd',
      '.EddeeddeeeeeeeeedcdcB',
      'Edeeeedeeeeeeeeecdcdbb',
      'FddFeddeeeeeeeeFdcdcBB',
      '....GcccaAaAcccC......',
      '..GcccAaAacccC........',
      '....GcccaAaAcccC......',
      '....CCcCAaAaCCcC......',
      '......EF......EF......',
      '......FF......FF......',
    ],
  },
};
