// Portraits for the Kelp Maze's species (see index.js).

module.exports = {
  'anything-anemone': {
    palette: { R: '#ff9ccc', A: '#f72585', a: '#b5179e', V: '#7a0f6e', p: '#ffb3c6', P: '#e0607e', y: '#ffe680', Y: '#e0a41c', b: '#7cc6f2', B: '#2f6fb0', g: '#8ee6b5', G: '#2f9a6e', w: '#ffffff', k: '#1d2333' },
    pixels: [
      '.....yy...bb......',
      'pp...yY...bB..gg..',
      'pP....yY.bB...gG..',
      '.pP...yY.bB..gG.pp',
      '..pP...yYbB.gG..pP',
      '...pP..yYbBgG.ppP.',
      '....RRRRRAAAAaa...',
      '....RRAAAAAAAaa...',
      '....RVVVAAVVVaa...',
      '....RkkwAAkkwaa...',
      '....RAAAAAAAAaV...',
      '....AAAVVAAAaaV...',
      '....AAAAAAAaaVV...',
      '...RAAAAAAAaaaVV..',
      '..RRAAAAAAaaaaVVV.',
      '...aaaaaaaVVVVVV..',
    ],
  },
  'hinted-hermit': {
    palette: { S: '#f4b98a', s: '#c97b4a', z: '#94512e', Z: '#61311f', R: '#ffa48a', r: '#ff6b4a', q: '#c8402c', Q: '#8a2a24', N: '#fff6b0', n: '#ffe066', m: '#d9a93a', i: '#4f63b8', w: '#ffffff', k: '#1d2333' },
    pixels: [
      '................SS..',
      '.......ww..NNNNnnSsz',
      '...ww..kww.NiiiinSsz',
      '..wkww.kkw.Nnnnnnssz',
      '..wkkw.ww..niininszz',
      '...ww...qSSnnnnnmszz',
      '....q...qSSnnnnmsszZ',
      '....q...qSSSSSzzzszZ',
      '....qRRRqSSSSzsSszzZ',
      '.RRr.RrrrqqSzsSzsszZ',
      'RRrrqrrrrqqZzszZzszZ',
      'r..qqrrrqqqZszssszZ.',
      'rrrqqqqqQQQZsszzzZZ.',
      '.qqQ.r.r.rZZzzzZZ...',
      '.....q.q.q..........',
      '.....Q.Q.Q..........',
    ],
  },
  'mismatched-mantis': {
    palette: { G: '#9be8b0', g: '#3bb39a', h: '#227a80', H: '#17506a', O: '#ffd685', o: '#ff9f1c', q: '#d4560f', B: '#b5e2ff', b: '#4ea8de', j: '#2c5fa8', w: '#ffffff', k: '#1d2333' },
    pixels: [
      '....ww...ww.....',
      '...wkww.wkww....',
      '...wkkw.wkkw....',
      '....ww...ww.....',
      '.Bb..g...h......',
      'BBbjgGGGGgg.....',
      'BbbjhGGGgggh....',
      'bbjjhHgggghh....',
      '.jj..gGGGggh....',
      '.OOo.hhhhhhH....',
      'OOooqgGGgghh....',
      'Ooooqhhhhhhhgg..',
      'ooooqgGggghgGGg.',
      '.qqq.H.H.hhgGgGh',
      '..........hHhhH.',
    ],
  },
  'optional-oarfish': {
    palette: { l: '#f4f7fb', o: '#c3ccd8', O: '#8d99b0', Q: '#5b6684', r: '#ff8a80', R: '#e63946', x: '#9e1b3c', f: '#8090ae', g: '#56668c', w: '#ffffff', k: '#1d2333' },
    pixels: [
      '......r...r...........',
      '.....R...R...rr.......',
      '....R...R...R.........',
      '....R..R..RR..........',
      '..llllllrrrrrrr.......',
      '.lllQQllllllllrrr.....',
      'llQQwwlooooooooooRR...',
      'llwkwwooooooooooooRR..',
      'lowkkwoOOOOOOOOooooR..',
      'ooowwoOQ....QOOOoooOR.',
      'QQQOoOQ........ooooOR.',
      '.QQQQQ..........oooOx.',
      '................loOOx.',
      '..............llloOQx.',
      '........lllllloooOQxx.',
      '.......loooooooOOQxx..',
      '......loOOOOOOQQxxx...',
      '.....loOQxxxxxxxx.....',
      '.....looOQ............',
      '......oOOQQ.ff..f.....',
      '.......QQQ..gg..g..gg.',
    ],
  },
  'missing-fin-pipefish': {
    palette: { Y: '#fff0a8', p: '#e9c46a', P: '#c48a3f', Q: '#8a5530', v: '#34466e', d: '#b9c2d0', w: '#ffffff', k: '#1d2333' },
    pixels: [
      '.........d..d....',
      '.................',
      '...YYYp.d.....d..',
      '..YYwwYp.........',
      '.YYwkwwpp......d.',
      'YYpwkkwpYYpYYpYY.',
      'PPppwwppppPppPppp',
      '..QPPPPPPPQPPQPPp',
      '....QQQQQQQQQQQPp',
      '...............Pp',
      '.............YpPp',
      '.............pPPQ',
    ],
  },
  'type-tangle': {
    palette: { G: '#b4f2c8', g: '#57cc99', h: '#2a9d8f', H: '#1d6b70', D: '#11404d', w: '#ffffff', k: '#1d2333' },
    pixels: [
      '.....GGGgggg.....',
      '....GwwwgwkkhGG..',
      '....GkwwgwwkhgG..',
      '....gkkwgwwwhgh..',
      '....GghhgghhhH...',
      '....ghH...DDDh...',
      '....ghHDggggG....',
      '..GDghhDhhggggg..',
      '.GGDgghDHHhhhggg.',
      '.GgDggh...DDhhgg.',
      'GghDgggg.GghDgggh',
      'DgH..ggDGGhH..ggh',
      'Dgh...DGGgh...Ggh',
      'DgggGGGghhHDGGghH',
      '.ghgggghHDDggghH.',
      '..hhhhHH.hhhhHH..',
    ],
  },
  'undeclared-urchin': {
    palette: { L: '#f3d6ff', U: '#c77dff', u: '#8f3fd1', m: '#5a1d94', d: '#f1f3f6', D: '#b8c0ca', s: '#6e7887', t: '#d9a85b', w: '#ffffff', k: '#1d2333' },
    pixels: [
      '........u..........',
      '..u.....u.....u....',
      '...u....u....u.....',
      '....u.LLLLU.u......',
      '....LLLLLUUUu......',
      '..uuLLLLUUUUumm....',
      '...LLwwLUwwUuu.....',
      '...LwwkwUwkkuu.....',
      'uuuUwkkwUwkkuummm..',
      '...UUwwUUwwuum.....',
      '...UUUmmUuuuumt....',
      '..mmUuuuuuumm..t...',
      '....uuuuuummm.dtdD.',
      '...m..mmmmm.m.dsddD',
      '..m.....m.....ddddD',
      '.m......m.....ddddD',
      '........m.....ddddD',
      '..............DDDDs',
    ],
  },
};
