// Portraits for the Lighthouse's species (see index.js).

module.exports = {
  'red-tide': {
    palette: { h: '#ffd0c4', R: '#ff8f8f', r: '#e63946', q: '#b0213a', Q: '#6e1235', w: '#fff4e4', g: '#d8c8cc', G: '#9a8794', y: '#ffd23f', Y: '#fff3a8', k: '#2a0f1a' },
    pixels: [
      '.......hwwRr......',
      '....hwwwRRRrrq....',
      '..hwwRRRrrrrrrq...',
      '.hwRRqqq...qrrrrq.',
      '.wR...q...hRRrrrrq',
      '.R...yYy..RwwrwwwQ',
      '.....qqq..RkwrwkwQ',
      '.....wgG..RRRrkkwq',
      '.....rrq..RRrrrrQq',
      '.....wgG..RRQQQQrq',
      '.....wgG..RRRrrrrq',
      '....hrrq.hRRRrrrqq',
      '..hRRwgGhRRRrrrrqq',
      'hRRwwhRRRwwRRrrwwq',
      '.wwhhwwwhhwwwwhhw.',
    ],
  },
  'matrix-hydra': {
    palette: { L: '#b7f0c8', g: '#57cc99', n: '#2f9e78', N: '#1d6b5e', S: '#ff8a8a', r: '#e63946', q: '#a4161a', x: '#4a0d1c', w: '#ffffff', k: '#1b1b2f', B: '#6fd0c0', b: '#2a9d8f', D: '#1f7275', E: '#164a5c' },
    pixels: [
      '........LLgn..........',
      '......LLgNNnn.........',
      '.....LggwkNgn.........',
      '.....gNNnnggn.........',
      '......nnnnnN.....LLgn.',
      '...SSSrq.Lgn...LLgNNnn',
      '.SSrrqqrqggn..LggwkNgn',
      'SrrrqwwrqLgn..gNNnnggn',
      'rrrrrkwrq.ggn..nnnnnN.',
      'wqqqqrrrq.Lgn...Lgn...',
      'xxxxxqrrq.ggn...ggn...',
      'Swxxqrrq..ggnn..Lgnn..',
      '.qqqqrrq..ggnn.LggnN..',
      '....qrrr.BBBBBbbgnN...',
      '...SrrrrqBBBBbbbbbD...',
      '....rrrrqqBBbbbbbbbDDE',
      '....bqqqqbbbbbbbbbDDDE',
      '....bbbbbbbbbbbbbDDDE.',
      '.....bbbbbbbbbbDDDDE..',
      '.....bbbbbbbbDDDDDEE..',
      '......DDDDDDDDDDEEE...',
      '......DD..DE....EE....',
    ],
  },
  'sunken-deploy': {
    palette: { S: '#c49a6c', s: '#8a6a4a', d: '#5d4037', D: '#3b2a3a', m: '#4a3328', w: '#fff4e4', W: '#c9c2dc', f: '#57cc99', k: '#1d1a2e', B: '#a8def7', b: '#4ea8de', n: '#2d6aa8' },
    pixels: [
      '........mff.........',
      '........mwW.........',
      '.........mwwW...B...',
      '.........mwwwwW.b...',
      '..........mwwwwwW.SS',
      '..........mwwwwWSSss',
      '...........mwwWSsssd',
      '...........mWSSssssd',
      '...........SSsssssdD',
      '..........Ssssssddd.',
      '........SSsssssdddD.',
      '......SSsssssdddDD..',
      '.....SwwwssddddD....',
      '...SSskwwsdddDD.....',
      '.SwwsskwwddDD.......',
      'SskwskddddD.........',
      'bBBbbbBBbbbbBBbbbBB.',
      '.bbbbbbbbbbbbbbbbbn.',
      '...nnnnnnnnnnnnnn...',
    ],
  },
  'stalled-galleon': {
    palette: { S: '#5d4037', s: '#8a6a4a', h: '#b88a5e', d: '#4a3328', W: '#f6ecc9', w: '#e9d8a6', V: '#c4ad7a', v: '#9a845a', b: '#4ea8de', B: '#9ad6f5', n: '#2d6aa8', e: '#fffaf0', k: '#1d1a2e', f: '#e63946' },
    pixels: [
      '......Sf......Sf....',
      '......Sf......Sf....',
      '..SSSSSSSS.SSSSSSSS.',
      '...WWwVwwV..WWwVwwV.',
      '...WwwVwwv..WwwVwwv.',
      '...WwwVwvv..WwwVwvv.',
      '...wwvVwvv..wwvVwvv.',
      '...wv.Vvv...wv.Vvv..',
      '......S.......S.....',
      '......S.......S.hhhs',
      'S.....S.......S.hsss',
      '.Shhhhhhhhhhhhhhssss',
      '.hSSSSsSSSSssssssssd',
      '.heeeeseeeessssssssd',
      '.hekkesekkesSssSsssd',
      '..hssskkssssssssddd.',
      '...dddddddddddddddd.',
      'bBBBBBBBBBBBBBBBBBBb',
      '.bbbbbbbbbbbbbbbbbb.',
      '...nnnnnnnnnnnnnn...',
    ],
  },
  'the-kraken': {
    palette: { h: '#f2c6ff', P: '#c77dff', m: '#9d4edd', p: '#7b2cbf', d: '#45198f', s: '#ffc8e6', w: '#fff4e4', k: '#1a0b2e', g: '#b9b2cc', G: '#7d7598', r: '#e63946', R: '#9b1d2a', y: '#ffd23f', Y: '#fffbd0' },
    pixels: [
      '......hhPm.........r..',
      '....hhhPPPPm......rrR.',
      '..hhhPPPPPPmmp...YyYyY',
      '.hhPPPPPPmPmmpp..rrrrR',
      '.hPPPmPPPPmmmpp...wgG.',
      'hPPPmmPPPPmmmpp...rrR.',
      'hddPPPPPdddmmpp...rrR.',
      'PYydPmmdYYymmpp...wgG.',
      'PykymmYykyymppd...wgG.',
      'mykymmpykypmppd...rrR.',
      'mmmmmpppmmmpppd...rrRm',
      'PmpdPmpdPmmppmmmmwwgGp',
      'Pmp.Pmp.PPmpmPPPPPPPmm',
      'Pms.Pmp..Pmp.pspspspmp',
      'Pmp..Pms.Pmp.ppd......',
      'Pms..Pmp..Pms..ppd....',
      'Pmp...Pms..Pmp..ppd...',
      'Pmp...Pmp...Pms..ppd..',
      'PmmpP.Pmp....Pmp..ppd.',
      '.psmp..Pmp....Pmp..ppd',
      '..ss...pssp...pssp..pd',
      '.....................d',
    ],
  },
};
