// Portraits for Tangled Nets' species (see index.js).

module.exports = {
  'two-headed-crab': {
    palette: { L: '#a8dcf7', b: '#4ea8de', B: '#2f72b8', V: '#22407c', P: '#ffd38c', o: '#ff9f1c', O: '#dc661c', Q: '#963a1e', m: '#9d4edd', M: '#5f2a9c', l: '#e2c8fa', w: '#ffffff', n: '#ffffff', k: '#1d1530' },
    pixels: [
      '......wwV....Qww......',
      '.....wwnk....nkww.....',
      '.....wwkk....kkww.....',
      'LL..b.ww......ww.P..PO',
      'Lb..b..B......O..o..oO',
      'Lb.bB..B......O..Po.oO',
      'LbbbB.LLbbBPPooO.PoooO',
      'bbbBV.LbbbbMPoooQooOOQ',
      '.bBVLLbbbbBmPooooOQoOQ',
      '..BVLbbbVVbMoQQoooOOQ.',
      '..BVbbbbbbbmoooooOOQ..',
      '...BbbbbbbBMoooooOQ...',
      '...BBMllllllllllllMQ..',
      '...VBMmmmmmmmmmmmmMQQ.',
      '...VBMllllllllllllMQQ.',
      '....VVVVVVVMQQQQQQQ...',
      '..VB.VB.VB..OQ.OQ.OQ..',
      '.VB.VB.VB....OQ.OQ.OQ.',
      '.V..V..V......Q..Q..Q.',
    ],
  },
  'bounced-bottle': {
    palette: { a: '#a8784e', A: '#6e4b30', G: '#eafcfb', c: '#a8dadc', C: '#6eaab8', V: '#3f6f8c', d: '#fff4e4', D: '#d9b98a', r: '#e63946', B: '#bfeaf7', b: '#4ea8de', N: '#2c62a6', w: '#ffffff', k: '#1d2840' },
    pixels: [
      '...............BBBBB.',
      '.............BBbbbbbN',
      '............BbbN..bbb',
      '............Bb.....bb',
      '.......GGGGGGGGGGc.bb',
      '.....GGccccccccccCCbb',
      'aAGGGcVVcVVcdddDcCVbb',
      'aAccccwkcwkcdrddcCVbb',
      'aACCCckkckkcddddcCVbb',
      '.....CCccccccccccCV..',
      '.......VVVVVVVVVVV...',
      '...BBb......BBBb.....',
      '.BBbbbbBBBBBbbbbbBBB.',
      'Bbbbbbbbbbbbbbbbbbbbb',
      'bbbNNbbbbbNNNbbbbNNbb',
      '.NN..NNNNN...NNNN.NN.',
    ],
  },
  'gatekeeper-goby': {
    palette: { h: '#fde49a', g: '#f0c453', G: '#c88c3a', D: '#86501f', L: '#b8907a', a: '#7a5a50', A: '#4a3029', y: '#d8dde6', Y: '#8d99ae', w: '#ffffff', k: '#2a1c14' },
    pixels: [
      '.......G.G.G.........',
      '.......GgGgG.........',
      '.......ggggG.GGGG....',
      '...hhhhgggggGggggGGG.',
      '.DDDDhDDDggggggGGGggG',
      'hwwwkgwwkgGggggGGGggg',
      'hwwkkgwkkggGgggGGGGgg',
      'hgggggggggGggggGGGggD',
      'DDDgggggggGggggGG.GD.',
      'LggLggLggLggggGG.....',
      'LagLyyLaGLaGGGD......',
      'LLLLyYLLLLAD.........',
      'La.La.La.LaD.........',
      'La.La.La.LaD.........',
      'LLLLLLLLLLA..........',
      'La.La.La.La..........',
      'AA.AA.AA.AA..........',
    ],
  },
  'lockfile-lobster': {
    palette: { H: '#ff7a5c', r: '#e03030', R: '#a51d36', D: '#5e0f24', h: '#fff3a8', y: '#ffd23f', Y: '#e09a28', G: '#a8621a', K: '#4a2a12', w: '#ffffff', n: '#ffffff', k: '#2b1020' },
    pixels: [
      '...R.....R.......',
      'H..rR...R..H..r..',
      'Hr.rRR.R...Hr.rR.',
      'HrrrRHrrR..HrrrR.',
      'rrrRDRRRRRRrrrRD.',
      '.rRDnkwrnkwRrRD..',
      '..RDkkwrkkwR.RD..',
      '..RrwwrrwwrR.RD..',
      '...rrDDDDDrRrrR..',
      '...RrrrrrrRD.HrR.',
      '.hhyyRyyyRyyY.rRD',
      '.hyyyyyyyyyyYHHrR',
      '.yyyyyKKyyyyYGrRD',
      '.yyyyyKKyyyyYG...',
      '.yyyyyyKyyyyYG...',
      '.YyyyyyKyyyyYG...',
      '.YYYYYYYYYYYGG...',
      '..GGGGGGGGGGG....',
    ],
  },
};
