// Portraits for the Proving Pools' species (see index.js).

module.exports = {
  'red-snapper': {
    palette: { H: '#ff8f7e', r: '#e63946', R: '#9d0208', D: '#5c0a2a', p: '#ffb4a2', w: '#fff4e4', k: '#2b2d42' },
    pixels: [
      '.....R.R.R.R......',
      '....RrRrRrRrR.....',
      '....HHHHHrrrrR.rrR',
      '...HHHrrrrrrrrRrrR',
      '..HHwwwrrrrrrrRrR.',
      '.HHrkkwrrwrrwrRR..',
      'HHrrkwwrrrwwrrRR..',
      'wDw.rrrrrrwwrrRR..',
      '.DDw.rrrrwrrwrRRrR',
      'wDDprrrrrrrrRRDrRR',
      '..pppprrRRRRD..rRD',
      '...RRRRRRDD.....RD',
    ],
  },
  'assertive-lobster': {
    palette: { H: '#ff7a5c', r: '#d62828', R: '#97182a', D: '#561330', w: '#fff4e4', E: '#ffffff', k: '#2b2d42' },
    pixels: [
      '...w.............',
      'wwwww..........RR',
      '..w...DD...DD.R..',
      'wwwww.kEE.kEER...',
      '.w....kkE.kkE....',
      '.......r...r.....',
      '.HH....r...r.....',
      'HrrH..HHHrrrrR...',
      '..DrR.HrDDDrrR...',
      'HrrrRrrrrrrrrRHrR',
      '.RRD..RrrrrrRRrrR',
      '......DRrrrrRDRRD',
      '.....D.RrrrR.D...',
      '......D.RRRD.....',
      '.......HrrrR.....',
      '......HrRrRrR....',
      '......rRD.DRD....',
    ],
  },
  'mirror-mullet': {
    palette: { L: '#eef3f6', m: '#adb5bd', M: '#6c757d', N: '#434b60', V: '#9a8fbf', v: '#5f5680', G: '#effdfd', g: '#a8dadc', c: '#5f9fae', H: '#c49a6c', h: '#8a6a4a', w: '#ffffff', k: '#2b2d42' },
    pixels: [
      '.........V.V..........',
      '..hhh...VVVVVv........',
      '.hGGGh.VvvvvvvVV......',
      'hGGGggh.vvvLvvvvvV....',
      'HGGgggh.mLLLmvvvvvvv..',
      'HGGgggh.mNNLmmmmvvvvv.',
      'HGkkggh.Mmmmmmmmmvvvvv',
      'HGkggch.MwwMmmmmmm.vvv',
      'hggggchMwwwwMmmmmm..vv',
      'hgggcchMkwwwmMmmmm.mmM',
      'hgggcchMkkwwmMmmmMmmM.',
      'hgcccchmMwwMmMmmMMmM..',
      'hgkgkchNmmmmmMMmMMMM..',
      '.hgkch.mNmmmmMmMMMmM..',
      '..hhh..mmmmmmMMMNNmMM.',
      '...hH..LLmmmMMMMN..mMN',
      '....hH.mMMMMMNNN....MN',
      '.....hHMM.NNNN........',
      '......h...............',
    ],
  },
  'sleepy-seahorse': {
    palette: { H: '#ffd6a5', o: '#f4a261', O: '#e76f51', D: '#9c3d26', k: '#2b2d42', z: '#e0e0e0', c: '#a8dadc' },
    pixels: [
      '.........zzz....',
      '...HHo.....z....',
      '..HooooO..z.....',
      '.HoookkoO.zzz...',
      'ooooooooOO......',
      '...HooooO.......',
      '....HoooOO......',
      '.c..HoooOOO.....',
      '.cc.HooooOO.....',
      '..c..HoooOO.....',
      '.c....ooOO......',
      '.cc...ooO.......',
      '..c....ooO..O...',
      '........oOOOD...',
      '.........DDD....',
    ],
  },
  'hollow-halibut': {
    palette: { H: '#e9d5b5', h: '#d4a373', D: '#a98467', e: '#fefae0', w: '#ffffff', k: '#2b2d42' },
    pixels: [
      '....HHhhhhhD......',
      '..HhhhhhhhhhhD....',
      '.Hhwkeeeeeeehhh..h',
      'Hhhkkeeeeeeeeehhhh',
      'hheeeeeeeeeeeeehhD',
      'hhheeeeeeeeeeehhhD',
      '.Dhhheeeeeeehhh..D',
      '..DDhhhhhhhhhD....',
      '....DDDDDDDD......',
    ],
  },
};
