// Portraits for the Sea-Snake Pool's species (see index.js).

module.exports = {
  'attribute-anglerfish': {
    palette: { A: '#8a8fba', a: '#4f5480', d: '#363a62', D: '#222443', l: '#b8c2d4', L: '#6d7891', t: '#f6f7ee', m: '#7a2140', M: '#4a1230', f: '#6a78b8', w: '#ffffff', k: '#1d2333' },
    pixels: [
      '....llll...........',
      '...l....l..........',
      '..l......l.........',
      '.LlL.....l.........',
      '.L.L.....AlAa......',
      '.......AAwwAaaa....',
      '.....AAAwkkwaaaa.f.',
      '....AAAAwkwwaaaaafa',
      '...AAAAAAwwaaaaadfa',
      '..AAAAAAAaaaaaaddfa',
      '.mtmtmtmMaaaaaddDd.',
      'mmmmmmmMaaaaddddd..',
      'tmtmtmMaaaafdddDd..',
      'aAaAaaaaaffdddDD...',
      '.dddddddddddDDD....',
      '...DDDDDDDDD.......',
    ],
  },
  'zero-dab': {
    palette: { F: '#f2e2b8', f: '#c9b38a', s: '#98805e', S: '#665240', w: '#ffffff', k: '#1d2333' },
    pixels: [
      '...FFFF......FFFF.....',
      '.FFFFwwwf..FFFFffff...',
      'FFffFkwwffFFffffffff..',
      'FwwwfkkwffFffsssffff..',
      'FkwwSssfffffsSSSfffsFf',
      'fkkw..sffffsSS..fffsfs',
      'Sfss..FFffffff..Fffsfs',
      'ffffFFFffsffffFFFffsss',
      'ffffffffsSffffffffsSS.',
      'ffffffssSSssfffffsSS..',
      '.ssssssSS..ssssssSS...',
      '...SSSS......SSSS.....',
    ],
  },
  'keyless-krill': {
    palette: { P: '#ffd6c4', p: '#ff9f80', q: '#e0604f', Q: '#9e3b4e', Y: '#fff2a0', y: '#ffd23f', o: '#c98a1a', w: '#ffffff', k: '#1d2333' },
    pixels: [
      '.q...q............',
      '..q...q...........',
      '...q..q...........',
      '....q..q..........',
      '.....wwPPPpppp....',
      '....wwkwPPpppppq..',
      '....wkkwPppppqpqq.',
      '.....wwpppqppqpqq.',
      '.YYyy.qqqQqqQqpq..',
      'Y....oQ.Q.Q...qpq.',
      'y....o........qPpq',
      'y....o.......qPpqQ',
      '.yooo.........qQqQ',
    ],
  },
  'off-value-oyster': {
    palette: { O: '#e6dad3', o: '#b09489', b: '#7d645c', B: '#4e3b42', n: '#d9c8e8', P: '#ffd0d6', p: '#f29aa6', q: '#c4687c', v: '#ece6ff', V: '#b9a9e3', u: '#7f6fb3', w: '#ffffff', k: '#1d2333' },
    pixels: [
      '...........OOOob..',
      '..OOOOOOOOOoooobb.',
      '.OOwwwOwwwoooobbB.',
      '.OowkkowkkoobbbB..',
      '..bwkkbwkkbbbbB...',
      '..nnnnnnnnnnnnnB..',
      '..PPPPPwwwwVPPpq..',
      '..Pppppwvvvupppq..',
      '..ppppqwvvvuppqq..',
      '.oqpppqwvvvupqqob.',
      'oOOOooVuuuuoooobb.',
      'OOooooobooooobbbB.',
      '.ooobooooboooobB..',
      '..bbbbobbbbbbBB...',
      '....BBBBBBBBB.....',
    ],
  },
  'circular-sea-snake': {
    palette: { B: '#8cc0f0', b: '#3d7cc9', c: '#2a5694', C: '#1b3566', Y: '#fff4b0', y: '#ffd43b', o: '#e09a1c', O: '#a3601a', w: '#ffffff', k: '#1d2333' },
    pixels: [
      '...BBBb..YYYYY........',
      '..BBbbbbcYYyyybb......',
      '.BBbCCbbcYyyyybbbb....',
      '.BCwwwbbcyyyyobbbbby..',
      'BbwkwwbbcoyyocbbbyyY..',
      'bbwkkwbccOoooccbyyyy..',
      'bbbwwbcCC.....cyyyyyo.',
      'CCcCwC.........yyyycc.',
      'YyCbb..........yybbcc.',
      '.yobc...........bbbccc',
      '...yo...........BbbccC',
      '...yo...........YyyooC',
      '...bc..........YYyyooO',
      '...bbc.........BYyyoO.',
      '...bbbb.......BBbyooO.',
      '....bbyyy...YYBbbccO..',
      '....byyyybBBYyybccCC..',
      '.....ooobbbbyyyccCC...',
      '......ooccccooooCC....',
      '........ccccoOOO......',
    ],
  },
  'wonky-whelk': {
    palette: { W: '#fffaf0', w: '#f3e6cc', b: '#c9b38a', B: '#8f7a5a', D: '#5e4c3a', L: '#a8cdf5', l: '#5a8fd0', m: '#33609e', e: '#ffffff', k: '#1d2333' },
    pixels: [
      '...........Ww.....',
      '...........wb.....',
      '..........WwwB....',
      '.....ee...bbbB....',
      '....eeke...WWwwwb.',
      '.ee.ekke...wwwwbB.',
      'ekee.ee....bbbbBB.',
      'ekke.l..WWwwwwwb..',
      '.ee..l..wwwwwwbB..',
      '..l..l..bbbbbbBB..',
      '.LLLll.WWwwwwwwbB.',
      'LLLLlllwwwwwwwwbBB',
      'LLmLllmbwwwwwwbBBB',
      'LllllllmDbbbbbBBB.',
      '.mmmmmmmmmmmmmmm..',
    ],
  },
};
