// Portraits for the Shallows' species (see index.js).

module.exports = {
  'shapeshifter-shrimp': {
    palette: { L: '#d199f5', a: '#9d4edd', A: '#7032b8', D: '#4a2185', T: '#6ad6bf', b: '#2a9d8f', B: '#1d7076', E: '#14485a', n: '#e3b8ff', w: '#fff4e4', k: '#1d1a33' },
    pixels: [
      'n........nn......',
      '.n......n........',
      '..n....n.TTTB....',
      '...nLLn..TbbB....',
      '..LLLLaaaTbbBTTTB',
      '.LLDDaaaaaBBETbbB',
      'aLwwwwaaaabBBBbbB',
      'awwwkwaaaTAbbBBBE',
      'awwkkwaaaAbbbBTTB',
      'aawwwaaaATDbbBbbB',
      'aaaaaaaAAABbbBbbB',
      'DDaaaAAADDTTTBBBE',
      '..AAAAADD.TbbB...',
      '.....D.TTBTbbB...',
      '...A.A.AbBBBBE...',
      '.......BBE.......',
    ],
  },
  nullfish: {
    palette: { L: '#d6f1fb', o: '#8ecae6', O: '#5a9cc4', D: '#3a6c99', f: '#bfe6f5', v: '#2a3555', V: '#121a30', n: '#e0fbfc', s: '#46557a', w: '#ffffff', k: '#1d2333' },
    pixels: [
      '.......ff...........',
      '.....ffffoo.........',
      '.....fffooo.........',
      '.....oooooO......f..',
      '....LLLLLLoo...fffoo',
      '..LLLLLLLLoooo.fffoo',
      '.wwwLLLLLLoooooffooO',
      '.wwkwLLLLvvoooooooOO',
      'LwkkwLLLvsVvooOOoOOO',
      'LLwwLLLvsVVVnoOOoO..',
      'oLLLooovVVVnvOOOOf..',
      'ooooooovVVnVvOODOfoo',
      'DDoooooovnVvOODfffoo',
      '.ooooooonvvOODDffooO',
      '..OooOOOOOODDD.oooOO',
      '....OOOOOOOD...OoOOO',
      '......OOOOOD.....O..',
      '.......OODD.........',
    ],
  },
  'nameless-nudibranch': {
    palette: { L: '#e4b5ff', p: '#c77dff', P: '#9d4edd', D: '#6a2c9f', c: '#ffd0f0', C: '#f39ad6', Y: '#ffe066', y: '#ffb347', w: '#fff4e4', g: '#d6c8bd', r: '#e63946', k: '#2b1d3d' },
    pixels: [
      '.L...L....Yy.......',
      '.p...p....cC.Yy....',
      '..P..P.Yy.cC.cC....',
      '.LLLLp.cC.cC.cC.Yy.',
      'LLLppp.cC.cC.cC.cC.',
      'LLwwLpLLpLLppppppP.',
      'LwwkwppppppppppppPP',
      'pwkkwppprrrrrrpppPP',
      'ppwwpppPwwwwwgppPPD',
      'pDDppPPPwwwwwgpPPDD',
      '.PpPPPPPggggggPPPD.',
      '...DDDDDDDDDDDDD...',
    ],
  },
  'syntax-slug': {
    palette: { Y: '#fff09a', y: '#ffd23f', o: '#e9a23b', O: '#b86b1f', w: '#fff4e4', k: '#3a2410' },
    pixels: [
      '.....yyyo.yyo..',
      '.....wwkw.wkw..',
      '.....wkkw.kkw..',
      '......ww..ww...',
      '.......o...o...',
      '......YyYYYyy..',
      '....YYyyyyyyyo.',
      '...YyyyyyyyyyoO',
      '...YyyoooyyyOO.',
      '..YyyoO..oOOO..',
      '..Yyyo.........',
      '..Yyyo.........',
      '.Yyyo..........',
      'Yyyyo..........',
      'oyyyo..........',
      '.oyyyo.........',
      '..Yyyo.........',
      '..Yyyo.........',
      '..Yyyo.........',
      '..YyyyyyyyyyY..',
      '...oyyyyyyyyyo.',
      '....oooooooooOO',
    ],
  },
  'off-by-one-octopus': {
    palette: { H: '#ffb08a', r: '#ff7a5c', R: '#c2412d', D: '#86253a', w: '#fff4e4', k: '#3a1420' },
    pixels: [
      '.................HHr.',
      '.......HHHHr....H...R',
      '.....HHHHrrrrR.H....R',
      '....HHHrrrrrrrRH....R',
      '...HHrrrrrRRrrrRr...R',
      '..HRRRrrrrrrrrRR.r..R',
      '..HrrrrrrrrrrrrR..rR.',
      '..HwwwrrrrwwrrrR.HR..',
      '..wwwkwrrwwkrrRRHRD..',
      '..wkkkwrrwkkrrrRRD...',
      '..wkkkwrrrwwrrrRD....',
      '.HHwwwrDDrrrrrRR.....',
      '.HrRHrRHrRHrRHrRHr...',
      '.HR.HR.HR.HR.HR.HR...',
      '.HR.HR.HR.HR.HR.HR...',
      'HR..HR.HR.HR..HR.HR..',
      'HR.HR..HR..HR.HR.HR..',
      'RD.RD...RD.RD.RD..RD.',
    ],
  },
  'ouroboros-eel': {
    palette: { H: '#a5f0c5', g: '#57cc99', G: '#2a9d8f', D: '#1d6b6f', c: '#d8f5c0', w: '#fff4e4', k: '#123030' },
    pixels: [
      '...HHG............',
      '.HHgggHHHHHG......',
      'HgwwwgggggggHG....',
      'HwwkkwggggggggG...',
      'HwkkkwgggggggggG..',
      'gggwwgggGGGGggggG.',
      'DwcccDgGD...GgggG.',
      '.DgggGGD.....GgggG',
      '.HggGD........cggG',
      'HgggG.........cggG',
      'HgggG.........cggG',
      'GgggG.........cgGD',
      '.HgggG.......cggG.',
      '.GggggG.....cggGD.',
      '..GggggcccccggGD..',
      '...GgggggggggGD...',
      '....GGgggggGGD....',
      '......GGGGGD......',
    ],
  },
  'broken-promise-prawn': {
    palette: { H: '#ffd2bd', p: '#ff9f80', P: '#e76f51', D: '#a8433a', x: '#6e2a2a', n: '#ffc9b0', w: '#fff4e4', k: '#3a1a1a' },
    pixels: [
      '.HH......nn...........',
      '.Hp.H...n.............',
      '.Hp.pP..n.............',
      'HpxppP.n..HHHHHP......',
      'HppxpP.nHHpppPppHP....',
      '.PpPxD.HpppppPppppP...',
      '..PPDHpppPpppPppppPP..',
      '.....HPDppPppPPppPppP.',
      '....HpwwpppPPPPPPpppP.',
      '....HwwwkpPD....PpppPP',
      '....HwwkkpP......PPPPP',
      '....HpwwppP.......HppP',
      '....DppppPD.......HpPD',
      '....HPPPPD........HpP.',
      '....P.P.P........HpPD.',
      '......P.P........HpP..',
      '................HpppP.',
      '...............HpPpPD.',
      '...............PD.PD..',
    ],
  },
  'heap-leviathan': {
    palette: { H: '#a9c6e8', h: '#6b8fb8', b: '#3d5a80', B: '#293241', D: '#1b2130', g: '#98c1d9', G: '#6f97b8', w: '#e0fbfc', m: '#4a1f3a', n: '#8c3b5c', y: '#ffd23f', c: '#7ae7ff', e: '#ff5d5d', k: '#121621' },
    pixels: [
      '.........hhhhhhhbbbbbb',
      '......hhhhHHhhhbbbbbbb',
      '....hhhHHhhbbgbbbbbbbB',
      '...hhhhhhbbbggbbbgbbbB',
      '..hhhbbbbbbbbbDDbbbbbB',
      '.hhbbbbbbbbbDDDbbbbbbB',
      '.hbbbbbbbDDDwwBbbbbbBB',
      'hhbbbbbbwwweekwBbbbbBB',
      'hbbbbbbbBwwekkwbbbbbBB',
      'hbbbbbbbbBBBBBbbbbbBBB',
      'bbbbbbbbbbbbbbbbbbbBBB',
      'BBBBBBBBBBBBBbbbbbbBBD',
      '.wmwmwmwmwmmmBbbbbbBBD',
      '..mmmmmmmmmmmmBbbbbBBD',
      '..mmccnyymmnmmBbbbBBDD',
      '..mmccnyynnnmBbbbbBBDD',
      '.wmwmwmwmwmmBbbbbBBBDD',
      '.hhhhhhhhhhhbbbbbbBBDD',
      '..gggggggggggGbbbbBBDD',
      '...BBBBBBBBBBBBbbbBBDD',
      '...gggggggggggGGbBBBDD',
      '....BBBBBBBBBBBBBBBDDD',
    ],
  },
  'garbled-jellyfish': {
    palette: { H: '#ffd6f0', j: '#ff99c8', J: '#e0609c', D: '#a3245c', w: '#ffffff', k: '#2b2d42', t: '#ffc6ff', T: '#c77dff', g: '#fff3a8' },
    pixels: [
      '....HHjjjjjj....',
      '..HHjjjjjjjjJJ..',
      '.HjjjjjjjjjjjJJ.',
      'HjjjjjjjjjjjjjJD',
      'jjwkjjjjjjwkjjJD',
      'jjkkjjjjjjkkjjJD',
      'JjjjjjgJgJjjjJJD',
      'DJJJJJJJJJJJJJDD',
      '.t.T.t.gT.t.T.t.',
      '.t.T.t..T.t.T.t.',
      't..T..tg.T..T..t',
      't.T..t..T..t.T.t',
      '.t.T..t.gT.T..t.',
      '..t.T.t..T.t.T..',
    ],
  },
  'spinning-top-shell': {
    palette: { H: '#ffe8a3', s: '#ffb703', S: '#fb8500', D: '#a35400', w: '#fff4e4', k: '#2b2d42', b: '#8ecae6' },
    pixels: [
      '......HHss......',
      '....HsssssSS....',
      '...HsSSSSSSsS...',
      'b.HsSwwwwwwSsS.b',
      '..sSwwSSSSwwSsD.',
      'b.sSwSSkkSSwSsDb',
      '..sSwSkwwkSwSsD.',
      'b.sSwSSkkSSwSsDb',
      '..sSwwSSSSwwSsD.',
      'b.DsSwwwwwwSsDDb',
      '...DsSSSSSSsDD..',
      '....DDssssDDD...',
      '......DDDD......',
      '.......DD.......',
    ],
  },
  'hydration-hydroid': {
    palette: { h: '#90e0ef', H: '#48cae4', D: '#0077b6', p: '#ffadad', P: '#e5383b', w: '#ffffff', k: '#2b2d42', d: '#caf0f8' },
    pixels: [
      '.h..h..p..p...',
      '..h.h..p.p..d.',
      '...hhhpppp..d.',
      '..hHHHPPPPp.dd',
      '.hHwkHPwkPPp..',
      '.hHkkHPkkPPp..',
      '..hHHHPPPPp...',
      '...DHHPPPD....',
      '....DHPPD.....',
      '....DHPPD..d..',
      '...DDHPPDD.dd.',
      '..DDDDDDDDD...',
    ],
  },
};
