// Portraits for the Deep Trench' species (see index.js).

module.exports = {
  'borrowing-hermit': {
    palette: { a: '#e8995e', s: '#c97b4a', z: '#86452e', L: '#ffd9a6', S: '#e9a26a', Q: '#b8724f', q: '#7a4646', p: '#ff9c78', r: '#ff6b4a', R: '#c93b42', D: '#7c2440', w: '#ffffff', k: '#2b2d42' },
    pixels: [
      '........www.........',
      '........kww.........',
      '....www.kkw.........',
      '....kww..r..LLLS....',
      '....kkw..r.LLLLSSS..',
      '.....r...rLLLLQQQSS.',
      '.a...r...rLLLQSSSQS.',
      '.az..r...RLLQSSQQSQQ',
      'aass..R..RLLQSQSLQSQ',
      'zzzz..R..RSSQSQSQSSQ',
      'aasss.ppprSSSQSSQSQQ',
      'asssprpppprrSSQQSQQ.',
      'zzzprRDppDrrSSSSQQq.',
      'assrRRrDDrrRDSQQQq..',
      '.zzzRrrrrRRDQQQQq...',
      '....RRRRRRR.........',
      '...D.D.D.D..........',
    ],
  },
  'rusty-nautilus': {
    palette: { N: '#fff8e8', n: '#f3e6cc', m: '#d6c0a6', M: '#9a8a92', b: '#c97b4a', B: '#8a4b2a', r: '#d9622b', R: '#8f3524', o: '#f5a25c', t: '#f2bf98', T: '#c98068', w: '#ffffff', k: '#2b2d42' },
    pixels: [
      '.........bNNbb...',
      '.......NbbNbbnbb.',
      '......NbbNNbnnbbn',
      '.....NbbNNbnnnnBn',
      '...bbbbNNbnnnnnBB',
      '..bbbbbbNNnMMMnnB',
      '.bbbbbbbBnMnnnMnm',
      '.BBBBBBBBnMnmMnMm',
      '.twkwwwTtnMnnMnMm',
      'ttwkkwwTtnnMMnnom',
      'ttwwwwTTtnnnnorrm',
      '.TtwwtTTnonnnrrRM',
      'TtTTTTBTnrRnmrRMM',
      'T.T.TTB.nmmmmmMM.',
      'B.B.B.B..mmmmMM..',
      '..........MMM....',
    ],
  },
  'panicked-prawn': {
    palette: { h: '#ffd2b8', p: '#ff9f80', P: '#e76f51', D: '#9c3a4a', r: '#ff4d5e', R: '#b81d3a', b: '#bdeeff', B: '#5aa9e6', w: '#ffffff', k: '#2b2d42' },
    pixels: [
      '.h.h...........rR',
      '.pPp....h.h....rR',
      '..P.....pPp....rR',
      '..P......P.b...RR',
      '...P.ww..P.B.....',
      '...PwwwwP......rR',
      '....wkwwPhhhh..RR',
      '...hhwwhhpppPhh..',
      'hphhhpppppppPpph.',
      '.hpppppppPppPpppP',
      '.DDpppppPPPPDppPP',
      '..DPPPPPD..DPPpPP',
      '...D.D.D....PpPPD',
      '..D.D.D....hPppPD',
      '...........hpPPD.',
      '..........hpPPD..',
      '........hhpPPD...',
      '........hpP.D....',
      '........pP.......',
    ],
  },
  'nil-gopherfish': {
    palette: { G: '#8ff0ea', g: '#00add8', B: '#0076a8', V: '#264275', w: '#fff4e4', W: '#e2c7ae', n: '#5a3a4a', T: '#ffffff', E: '#ffffff', k: '#2b2d42', d: '#c4cbd2', D: '#6c7488' },
    pixels: [
      '.........GGg..GGg.....',
      '.........GWB..GWB.....',
      '.........gGGGGGgB.....',
      '........GGGGGggggg..Gg',
      '.......GGgEEgggggg.Ggg',
      '.......GgEEEEggggggggB',
      '.......GgkEEEgggggggB.',
      '.......GgkkEEggggggB..',
      '......GggggggggggggB..',
      '.....nnwwwwgggggggBBB.',
      '.....wwwwwwggggggBBBBV',
      '.....wwwwwWgggggBBBBBV',
      '.ddd..wWWWWggggBBBV.BV',
      'd..dD.WTTgggBBBBVV....',
      'd.d.D.GGggBBBBBV......',
      'dd..D..BBV............',
      '.DDD..................',
    ],
  },
  'knotted-eels': {
    palette: { A: '#b4f5b8', a: '#57cc99', m: '#2f9a86', M: '#1f5f6b', f: '#8fd8c0', B: '#ffd27a', b: '#ff9f1c', o: '#d9622b', O: '#8f3a3a', F: '#ffc46b', z: '#e8f1ff', Z: '#9fb4d8' },
    pixels: [
      '..................zzzz',
      '.......f.fff..f....zZ.',
      '.....fffAAAAAAAf..zZ..',
      '....AAAAAAaaaaaa..zzzz',
      '..AAAaaaaaaaaaaaaa....',
      '.AAaaaaaammmmaaaaa....',
      'AaMaaMaaamMMmmaaaaa...',
      'AaaMMaaaaM.....aaaaa..',
      'aaaaaaaam.......aaaa..',
      'BbOMMMmmm.......aaam..',
      '.bmmmmmmM........aam..',
      '..bMMMMM.........Aam..',
      '...bbbo..........Aam..',
      '...bbbb..........am...',
      '...bbbbb........BbmbB.',
      '...FbbbbbB..BBBBbOOObb',
      '...FbbbbbbBBBBbbbbbbbb',
      '.....bbbbbbbbbbbObbObb',
      '.....FoobbbbbbbbbOObbo',
      '......FFooooobbbbbbbbo',
      '.......F.FFOOOoobbbboo',
      '..........FF...ooooOO.',
    ],
  },
  'segfault-squid': {
    palette: { L: '#e7b8ff', s: '#c77dff', S: '#9d4edd', D: '#5a2a8c', i: '#3a2552', I: '#2a1c3e', n: '#d9b3ff', w: '#ffffff', k: '#2b2d42', r: '#ff5c8a' },
    pixels: [
      '................Lsss.',
      '..............LLLsss.',
      '.............LLLssssS',
      '............LLLssssSs',
      '...........LLLsssssSS',
      '..........sLLsssssSSS',
      '..........LLsssssSSS.',
      '..........sssssssSSD.',
      '.........sLLLssSSSD..',
      '.........LLDDssSSD...',
      '........LDDwDssSD....',
      '....i...DwkkwsSD.....',
      '.iiiiSs.swkrwSD......',
      'iiiiiiDSSSwwSDss....s',
      'iiiiiiiiii.sssssss.SD',
      'ininnninnn.ssssSSSSD.',
      'iniiinininIssss..D...',
      'iniinninnnIssSss.....',
      'iniiiniiin.ss.Sss....',
      '.ninnninnn.Ss..SSSD..',
      '..iiiiII....ss.......',
      '.............DD......',
    ],
  },
};
