// Portraits for the Sunken Vault' species (see index.js).

module.exports = {
  'leaky-clam': {
    palette: { P: '#ffd3d0', c: '#e5989b', C: '#b5838d', D: '#6e4a66', i: '#2e1838', f: '#ff8fa8', F: '#c4506e', w: '#ffffff', k: '#2b2d42', l: '#fff3a8', y: '#ffd23f', Y: '#c98a1a' },
    pixels: [
      '...PcPPc.PPcPc.Cc.....',
      '..PPcPPPccccCcccDCC...',
      '.PPcPPPPccccCcccCDCC..',
      'PPcPPPPcPcccCcccCDCCC.',
      'cCcccccCcCCCDCCCDDDDD.',
      'CcccccCccCCCDCCCDDDDDD',
      'DDDDDDDDDDDDDDDDDDDDDD',
      '.FfFfFfFfFfFfFffFiiii.',
      '..ikwwiiiikwwiiyyyiCC.',
      '.iiikwiiiiikwiyliyyiD.',
      'lyyyyyyyyyyyyyyiiyYiD.',
      'fYfYYffffffffffYYYfDC.',
      'cYPYYPcPPPPPcPcCCCDCCC',
      'cycccccCccccCccCCCDCC.',
      '.YCccccCccccCccCCDCC..',
      '..CDCCCCDCCCDCCDDDD...',
      '...CDCCCDCCCDCCDDD....',
      '....CDCCDCCCDCCD......',
    ],
  },
  'barnacled-anchor': {
    palette: { A: '#a9c3d9', a: '#577590', N: '#34486a', b: '#eef2f6', B: '#a3aab8', o: '#5a5068', r: '#e63946', w: '#ffffff', k: '#2b2d42' },
    pixels: [
      '......AAAa.......',
      '.....Aa..aN......',
      '.....a....N......',
      '...b..aNNN..b....',
      '..bobAAAaaabobN..',
      '..BBBaaaaNNBBBN..',
      '.......AaN.......',
      '.....AaaaaaN.....',
      '.....NNNaNNN.....',
      '.....wkwawkw.....',
      '.....wwwawww.....',
      '.....AaNNNaN...b.',
      'A.....AaaaN.....a',
      'AA.....Aab.....aN',
      'Aa.....Abrb....aN',
      '.Ab....ABBB..baN.',
      '.bob...AaN..bobN.',
      '.BBBbB.AaN..BBB..',
      '...NaaaaaaaaaN...',
      '.....NNNNNNN.....',
    ],
  },
  'cert-cuttlefish': {
    palette: { L: '#f3e9d2', c: '#b5a48b', C: '#7f6f58', D: '#4f4438', f: '#e9c9a6', F: '#b48e72', s: '#ff7a6b', r: '#d62828', R: '#861426', w: '#ffffff', k: '#2b2d42' },
    pixels: [
      '..........fFfFfFf.....',
      '.........fFLLLLLcfF...',
      '.......fLLLLLLLcccccf.',
      '......fLLLLLLLLccccccF',
      '.....fLLCCLCCCLCCcCCcF',
      '....DDDDDDLLLccccccccF',
      '...LwwwwwDLCCCLCCcCCcF',
      '..LLkkwkkDcccccccccCCF',
      '..LcwkwkwDcCCcCCCcCCCF',
      '..cccwwwcDccccsssrcCCF',
      '.ccccccccDCccssDrrRCCF',
      'LcccccCCCDccCsrrDrRCDF',
      'ccCcccCCDDCCCrrDrRRDF.',
      'cCcCcCCD.fCCCrrrDRRF..',
      'C.cC.cC..fFfFCRRRRfF..',
      '.C..C.D...fFfFrR.rR...',
      '..............rR.rR...',
      '..............r...R...',
    ],
  },
  'turned-away-turbot': {
    palette: { H: '#ffe0a3', t: '#f6bd60', T: '#d08c60', D: '#9c5a33', w: '#ffffff', k: '#2b2d42', r: '#e63946', R: '#9d0208' },
    pixels: [
      '.rrrr...............',
      'rRrrrr.....HHtttt...',
      'rwwwwr...HHtttttttT.',
      'rwwwwr..HtttttttttTT',
      'rrrrRr.HtwkttttttttT',
      '.rrRR..ttkkttttttTTT',
      '..RR...tttttttttTTTD',
      '..RR...TtttttttTTTD.',
      '..RR....TTTTTTTTDD..',
      '.RRRR.....DD..DD....',
    ],
  },
  'unset-sea-star': {
    palette: { H: '#ffc2d1', s: '#ff8fa3', S: '#c9184a', D: '#800f2f', w: '#ffffff', k: '#2b2d42', e: '#e0e0e0' },
    pixels: [
      '........H........',
      '.......sHs.......',
      '.......sss.......',
      '......sssss......',
      'HHsssssssssssSS..',
      '.SsswksswkssS....',
      '..Sskkskksss.....',
      '...SssSSssS......',
      '...Sss..SsS......',
      '..Sss....e.e.....',
      '..SS.......e.....',
      '.SD.........e....',
    ],
  },
  'sealed-scallop': {
    palette: { H: '#ffe5ec', c: '#ffcad4', C: '#e5989b', D: '#b5838d', y: '#ffd23f', Y: '#c98a1a', k: '#2b2d42' },
    pixels: [
      '.......HHcc.......',
      '.....HcCcCcCc.....',
      '...HcCcCcCcCcCc...',
      '..HcCcCcCcCcCcCD..',
      '.HcCcCcCcCcCcCcCD.',
      '.cCcCcCcCcCcCcCcD.',
      'cCcCcCcCyyyCcCcCcD',
      '.DCcCcCcy.yCcCcCD.',
      '..DCcCcyyyyyCcCD..',
      '...DDCcyykyyCDD...',
      '.....DDyYkYyDD....',
      '.......YYYYY......',
    ],
  },
};
