// Portraits for the Reef Workshop's species (see index.js).

module.exports = {
  'stray-module-minnow': {
    palette: { L: '#dcf3fb', f: '#8ecae6', m: '#5aa9cf', F: '#219ebc', D: '#16608a', w: '#ffffff', k: '#14213d', C: '#eef1f4', c: '#adb5bd', g: '#6c757d' },
    pixels: [
      '.............CCc',
      '.............C..',
      '.............cgg',
      '...........CCc..',
      '...........C.g..',
      '....FFF....C.g..',
      '...FFDDF...cgg..',
      '..LDDLffm..FFF..',
      '.LwwkLffmmFFDD..',
      'LLwkkffffmFD....',
      'LLwwwffffmFD....',
      'mLLLffffmmFFD...',
      '.mffffmmmDFFDD..',
      '..mmmmmDD..FDD..',
      '...FDDD.....DD..',
    ],
  },
  'tangled-tree-crab': {
    palette: { R: '#ffb08a', r: '#ff6b4a', o: '#d9442f', O: '#8f2633', T: '#c49a6c', t: '#8a6a4a', u: '#5a3f33', L: '#b5d67a', l: '#6fa04a', w: '#fff4e4', k: '#2a1414' },
    pixels: [
      'R..R.........Ll....Tl.',
      'Rr.Rr.......Tt....Tu..',
      'rRrrro.......Tt..Tu...',
      'TttTttu.....Tu.TttuTt.',
      '.ooro.u....Tu.Tu..Tu.u',
      '...oo..ww.wwwTtTu.Tu..',
      '....oo.kw.kkwTttuTu...',
      '.....o.kw.kkw.Ttuu....',
      '......o.o..o...Tu.....',
      '.....RRRRRRRRRRtuRro..',
      '....RRRRRRRRRrrrrrroo.',
      '..RRrRRRRrrrrrrrrrrooO',
      '.RrrroOwwwwOrrrrrrooO.',
      'RrrrooOOOOOOrrrroooOO.',
      '..ooooorrrrrrooooOOO..',
      '.rRro..ooooooOOOOO....',
      'RrroO.oO..oO..oO..oO..',
      '.oO..oO...oO...oO..oO.',
      '.....O...oO.....O...O.',
    ],
  },
  'collapsed-castle': {
    palette: { h: '#f8e4a6', s: '#e9c46a', S: '#c9a227', d: '#9a7426', D: '#6b4c2c', f: '#e63946', F: '#a4161a', w: '#fffaf0', k: '#2b1d14', c: '#ffb4a2', b: '#8fd3ff' },
    pixels: [
      '...........Dff...',
      '...........DffF..',
      '...........D...b.',
      '........hh..ss.S.',
      '........hhssssSd.',
      '........hsssssSd.',
      '........hwwswwSd.',
      '........hwkswkSd.',
      '...h....hdsssdSd.',
      '..hhs.h.hsdddsSd.',
      '..hsshs.hsssssSd.',
      '.hhsssSShsssssSd.',
      'hh.ssSSShssssSSd.',
      'hshsSSSShsssSSdd.',
      'SsssSSSSSSSSSdddc',
      '.SSSdddddddddddd.',
    ],
  },
  'lint-louse': {
    palette: { H: '#eef0f3', l: '#adb5bd', L: '#7a8290', D: '#4a5163', R: '#ff8f8f', r: '#e63946', q: '#a4161a', w: '#ffffff', k: '#1d2333' },
    pixels: [
      '.D...D.........',
      '..D.D..........',
      '..HHl...HHllL..',
      '.HHlll.HllllLL.',
      'HLLLlLLLLLLLLLD',
      'HwkklwkkllllLLD',
      'lwwwlwwwLLLLLLD',
      'llDllllDlllllLD',
      '.lDwwwwDLLLLLD.',
      '..lDDDDlllllD..',
      '..D.D..D.D.D...',
      '..RRr...RRr...R',
      '.Rr.rq.Rr.rq.Rr',
      'rq...rqq...rqq.',
    ],
  },
  'beached-whale': {
    palette: { h: '#9fd3f2', b: '#4ea8de', B: '#3a6ea5', D: '#26467a', p: '#e2eef7', P: '#a9c2d8', w: '#ffffff', k: '#14213d', W: '#cdeafe', T: '#ff8fab', y: '#f8e4a6', s: '#e9c46a', S: '#c9a227' },
    pixels: [
      '....W...W............',
      '.....W.W........hb.bB',
      '......W..........hbbB',
      '......W...........bB.',
      '.....hhhhbbb......bB.',
      '..hhhhhhbbbbbbb..bbB.',
      '.hhhBBBbbbbbbbbbbbBD.',
      'hhbwwwwbbbbbbbbbBBB..',
      'hbbwkkwbbbbbbbbbBBD..',
      'bbbbbbbbbbbbbbBBBBD..',
      'DDDbbbbbbbbbbBBBDD...',
      'TTpDDDDDbbbBBBDD.....',
      'yTppppPPPPBBDDsss....',
      'yysPPPPPBBDDsssssss..',
      '.yyssssssssssssSSSSs.',
      '..sssSSsssSSssSSSS...',
      '....SSSSSSSSSSSSS....',
    ],
  },
  'old-salt': {
    palette: { R: '#ffa07a', r: '#ff6b4a', o: '#d9442f', O: '#8f2633', w: '#f1faee', W: '#c9d3dc', V: '#8f9bb0', t: '#ffd23f', T: '#c99a1a', k: '#2a1414', e: '#ffffff' },
    pixels: [
      '...............ttt.',
      '..............tktT.',
      '..ww...www....tttT.',
      '...wW.wwWW....tTTT.',
      '..OOO.OOOO.....T...',
      '..eke.ekke....RTr..',
      '...o...o......RrrO.',
      '...o...o.....RRroO.',
      '..RRRRRRRRRRRrroO..',
      '.RRRRRRRRrrrrrro...',
      'RRRRRRrrrrrrrrooO..',
      'rwwwwwwwwwrrrrooO..',
      'wwwWwwWwwWrrrooOO..',
      '.wwWwwWwwWoooooOO..',
      '.wwWwwWwWVoO.oO.oO.',
      '..wWwwWWV.oO..oO.oO',
      '...wWwWV...........',
      '....WVV............',
    ],
  },
};
