// Portraits for the Haunted Wreck's species (see index.js).

module.exports = {
  'flaky-phantom': {
    palette: { H: '#fffdf6', w: '#f4f1ea', g: '#c9c4d6', G: '#968dbb', k: '#1a1a22', W: '#ffffff', d: '#ff5d73', M: '#5c4f7a', R: '#ff8a9a', r: '#ff5d73', E: '#b8324f' },
    pixels: [
      '.......HHHggG........',
      '.....HHHwwwwggG......',
      '....HHHHwwwwwggG.....',
      '...HHwHwwwwwwwggG....',
      '...HwwwwgggwwwwggG...',
      '..HHggwwkkkwwwwggG...',
      '..HwkkwwkWkwwwwwggG..',
      '..gwkWwwkkkwwwwwggG..',
      '..gwkkwwkkdwwwwwgggG.',
      '..GgdwwwwdwwwwwgwggG.',
      '...wwwwwwwwMwwgwwgggG',
      '...HwgwgwgMwgwwwwgggG',
      '.RRRggMMMMggggwwgggGG',
      'RRWRREGGgggGGggwgggG.',
      'rrrrEEG.GgGG.GggggGG.',
      'rWrrEE...GG...GgggG..',
      'rrrWEE.........GggG..',
      'rrrrE...........GgG..',
      '.................GG..',
    ],
  },
  heisenbug: {
    palette: { X: '#f6ffff', w: '#e0fbfc', g: '#a8dadc', G: '#6fa9c0', D: '#4a6f9e', k: '#2b2d42', W: '#ffffff', v: '#b392f0', V: '#7b5cd6', I: '#d8c8ff', S: '#7fd6e0', s: '#4f9fb8' },
    pixels: [
      'I.....I...wwwwwwwwwSss',
      '.g.g.g..wwwwwgggggg...',
      'g.g.gg.wwwwgggVVVVgSss',
      '..g.gg.wwggggVIIIWV...',
      '...gg.wwgggggVIkkkVsss',
      '...g..wggggggVIkkkV...',
      '..XXXXwgggggGVvkkvVs..',
      '.XXwwwwXXggggGVVVVv...',
      'XXwwwwwXwwgggGGGv.....',
      'XGGGGwwwwwgggGv.......',
      'wkkkkkwwwggggggGv.....',
      'wkkkWkwwgggggVVgGv....',
      '.kvvvkgggGgggVkGGGv...',
      '..kkkgGggggggGGGGGv...',
      '....GGGGwwgggGGGvv....',
      '.......GwggvGSSSS.....',
      '........GgD.vsSss.....',
      '........DgD..SSSS.....',
      '........GwD...sss.....',
      '.........DD....SS.....',
      '.................ss...',
      '...................SS.',
    ],
  },
  'race-wraith': {
    palette: { w: '#f1faee', g: '#cdeafe', G: '#8fb8de', D: '#5b7fb5', k: '#1e2235', c: '#8ff0ff', W: '#ffffff', d: '#8d6e63', e: '#b08b78', f: '#5d4037', V: '#1d1b2a' },
    pixels: [
      '..............D.....',
      '.......D.....gDD....',
      '....eewGDeeeggGDDeef',
      '....ewwgGDeggGGGDDee',
      '....wwgggGDDGGGDGDDf',
      '.D.wwggDggGDDGDGGDDf',
      '..DDggDDgggGDGkkGDDf',
      '..kkkgkkgggGDGckGDDf',
      '.wkckgkcgggGDGGGGDDf',
      '.wkkkgkkggggggkkDDDf',
      'wwggggggggggGDGDDDDf',
      'GkWkWkWkggggGDDDDDdf',
      'wgkgkgkgggggGDVDDVdf',
      'gGggggggggggGDVVVVdf',
      '.DgggggggggGGDVVVVdf',
      '..GggggggggGDDVVVVdf',
      '..DgGgGgGGgGDVVVVVdf',
      '...DDGGDDGDDDVVVVVdf',
      '...DeDDDVDDVDVVVVVdf',
      '....eDVVVDVVVVVVVVdf',
      '....edVVVVVVVVVVVVdf',
      '....ffVVVVVVVVVVVVff',
    ],
  },
  'cache-ghoul': {
    palette: { h: '#e8fff8', g: '#b8f2e6', G: '#76c9b8', J: '#3f8f8a', k: '#2b2d42', W: '#ffffff', y: '#f7e36a', c: '#e0a477', b: '#c97b4a', B: '#8a5a3a', N: '#5e3a28', L: '#f4ead8', M: '#a08870' },
    pixels: [
      '....J...J...........',
      '....GJ.GJ.J.........',
      '...hhghhghhGJ......N',
      '..hhhgggggggGJ...bbN',
      '..hhggGGGGggGJ.bbbNN',
      '.hGGggkkkkggGJbbBNN.',
      '.hkkggkWyyggGJBBNN..',
      '.GWygggyyggGGJNNN...',
      '.JgggggggggGJJN.....',
      '..JggggggJgGJ....N..',
      'cggGWJWJJGGgg..BBN..',
      '.GbGbbbbbbGbGBBBBN..',
      'NNNNNNNNNNNNNBBBBN..',
      'cbbbbbcbbbbbBBBBBN..',
      'cbbbbbcbbbbbBBBBBN..',
      'cbbbbbcbLLLLBBBBBN..',
      'cbbbbbcbLMMLBBBBBN..',
      'cbbbbbcbLLLLBBBBBN..',
      'cbbbbbcbbbbbBBBBNN..',
      'cbbbbbcbbbbbBBNNN...',
      'cbbbbbcbbbbbBNN.....',
      'BBBBBBcBBBBBB.......',
    ],
  },
  'zombie-process': {
    palette: { Y: '#e3ffe6', z: '#b9fbc0', Z: '#80ed99', X: '#3fae74', G: '#3fae74', k: '#2b2d42', W: '#ffffff', S: '#ced4da', s: '#adb5bd', T: '#7d8590', U: '#59606b', m: '#7a6a58', n: '#3e342c' },
    pixels: [
      '........WWW...........',
      '...ZZZ.WWWW.YzzZ......',
      '..GkkG.WkWWYzzzzZ.....',
      '..WWkW..WW.zZ..zZTU...',
      '...WW...Z.zZZ.SSZsTU..',
      '....Z...Z.ZZ.SSssssUU.',
      '....Z...zZZ..SsssssUU.',
      '...YzYYYZZX..SsTTTTTU.',
      '.YYYYYYzzzzZXSssSSsTU.',
      'YYzYYzzzzzzzZXsssssTU.',
      'ZzzzzzzzzzzZZXsTTTTTU.',
      'XXXXXXzzzzZZXXsssssTU.',
      '.XXZXZZZZZZXXSsTTTsTU.',
      'YzZXXXXXXXXX.SsssssTU.',
      'zZ...Z...Z...SsssssTU.',
      '.zZ..Z....Z..SsssssTU.',
      'Zz...z....z..TTTTTTTU.',
      '.Y...Y.....YmmmmmmmnU.',
      '.........nnnnnnnnnnnnn',
    ],
  },
};
